### ISSUE TITLE
checkboxes and radio buttons aren't handled correctly in FdfFile class

### ISSUE THREAD

**Issue by talisto** [mikehaertl/php-pdftk#10]
Checkboxes and radio buttons need to be handled differently than strings in the FDF format.  See the forge_fdf_fields() function in this class:

https://github.com/andrewheiss/pdftk-php/blob/master/pdftk-php.php#L226

basically, strings need to be formatted as:

`/V (value)`

and checkboxes/radio buttons need to be formatted as:

`/V /value`

perhaps the FdfFile constructor should take an additional parameter;  the first being an array of values for strings, and the second being an array of values for checkboxes/radio buttons.

**Comment by mikehaertl** [comment]
Hmm, I currently can't test this - but I was pretty sure, that it worked with checkboxes. Also check the travis tests, where a checkbox is inlcuded. Does this maybe only affect some older PDF readers?

If this really needs to be fixed, then I suggest that values for radios/checkboxes must be supplied as `boolean`. Then we can use `is_boolean()` on the field value to identify those fields. What do you think?

**Comment by talisto** [comment]
Your unit tests do include form filling a PDF with checkboxes and radio buttons, but that works because the data.fdf file is actually formatted correctly.  However, the FdfFile class won't generate the same output as data.fdf given the same input data, and there isn't a unit test to check that.

`is_boolean()` would possibly work for checkboxes, but not for radio buttons, because there could be a set of more than two radio buttons which would require more than just true/false values.  I can't really think of any way around this issue other than sending a separate array of data for those values.

**Comment by talisto** [comment]
Hmm, I just realized that you DO have a unit test to fill the form from the FdfFile data, and it does work correctly; I had mistakenly assumed it wasn't working because neither of the checkboxes were checked in the filled form, but that's because the checkboxes need to be set to "On", and the unit test data uses "Yes" and 0.

I'm having trouble filling a different form, which is why I filed this bug report, but the problem may lie elsewhere.  I'll try to figure out why your included form works and my custom form does not.  I'll close this issue for now.  Thanks!

**Comment by mikehaertl** [comment]
Oh, that's good news, thanks. But please keep me updated here if you find anything. You've probably already seen it but I got most of my information about FDF from here: http://blog.tremily.us/posts/PDF_forms/. So I'm by no means an expert on FDFs/PDF handling. It's very possible that there are bugs.
