### ISSUE TITLE
I am trying the function but not working

### ISSUE THREAD

**Issue by fouad1994** [mikehaertl/php-pdftk#101]
Hello

I am working on **PHP Laravel project** I need two function

**first one** to extract all fields ids or names of PDF application form without description question and hints only fields ids to store it in Database.
**second one** to fill the pdf file with a value and save it as a new file
--------------------------------------------------------------------------------
I have installed this tool PDFKT and tried to write this function to get names

// Get data
$pdfpath = public_path( 'application.pdf' );
$pdf = new Pdf($pdfpath);
$data = $pdf->getData();
echo $data;
print_r($data);
// Get form data fields
$pdf = new Pdf($pdfpath);
$data = $pdf->getDataFields();
echo $data;
print_r($data);

but when I run it the page still blank no errors no text no results
---------------------------------------------------------------------------------
and the same when I ran this funtion
// We now use the above PDF as source file for a new PDF

$pdf2 = new Pdf($pdfpath);
$pdf2->fillForm(['name' => 'ÄÜÖ äüö мирано čárka'])
    ->needAppearances()
    ->saveAs(public_path( 'new_application.pdf' ));

Can you help me in that please?

**Comment by mikehaertl** [comment]
Did you check the error with `getError()` as shown in the example here? https://github.com/mikehaertl/php-pdftk#fill-form

Also try to set the command to your `pdftk` executable file as mentioned in the options. https://github.com/mikehaertl/php-pdftk#shell-command

**Comment by fouad1994** [comment]
I checked errors I got this message
Failed without error message: pdftk A="D:\xampp\htdocs\Nawar\public\application.pdf" fill_form "C:\Users\Fouadoo\AppData\Local\Temp\php3D44.tmp.xfdf" output "C:\Users\Fouadoo\AppData\Local\Temp\tmp3D55.tmp.pdf" drop_xfa need_appearances

And I set the command line code I get this error:
The system cannot find the path specified.

I want to ask something  I noticed a comment in Shall Command say:
// 'command' => 'C:\Program Files (x86)\PDFtk\bin\pdftk.exe',
I don't have this exe file it is necessary if yes how to execute it on hosting online????

Thank you

**Comment by mikehaertl** [comment]
Sorry, I can't help you with this. A working `pdftk` executable is a requirement for our library. You have to ask your hoster for support.

**Comment by fouad1994** [comment]
Ok I am working now on local host how to i can make it works with me?
