### ISSUE TITLE
Problem with with checkboxs when use need_appearence

### ISSUE THREAD

**Issue by zaknoel** [mikehaertl/php-pdftk#102]
I am filling pdf form, but in chrome some checkboxes not displaying as checked, in other browsers and Adobe Programs displaying as checked. If i remove needAppearances(), works fine but my Crillic letters are not displaying. Can you help me to solve this problem? 
Attaching pdf file. First two checkboxes are not displaying correctly in chrome
[qqq.pdf](https://github.com/mikehaertl/php-pdftk/files/1673311/qqq.pdf)

**Comment by mikehaertl** [comment]
Sorry, I can't help to debug specific form or character issues unless you can provide more specific information, which PDF feature exactly is broken.

I'm by no means a PDF expert. We already tried our best to come up with code that solves the most common PDF problems. But if something is missing we need deeper information where exactly in the our code you think something can be fixed.
