### ISSUE TITLE
only blank page

### ISSUE THREAD

**Issue by meentix** [mikehaertl/php-pdftk#103]
Hi,

I have a managed virtual server and my hoster installed pdftk succesfully (pdftk 2.02), Iv tested that. They also say that they have installed php-pdftk but I dont get it to work. I have a testscript here: http://meentix.aix-cloud.de/fpdm/phppdftk.php with the following php code:

`use mikehaertl\pdftk\Pdf;

// Fill form with data array
$pdf = new Pdf('tkantrag2.pdf');
$pdf->fillForm([
        'Name'=>'Test',
    ])
    ->needAppearances()
    ->saveAs('fillednew.pdf');

// Check for errors
if (!$pdf->saveAs('fillednew.pdf')) {
    $error = $pdf->getError();
}`

The pdf tkantrag2.pdf exists in the same folder as the script is. But there is no fillednew.pdf created and there is no error message, only a blank page... Dont know why, can you please help me to find the problem. Thanks.

**Comment by mikehaertl** [comment]
You may have to configure the path to `pdftk`. See here: 
https://github.com/mikehaertl/php-pdftk#shell-command

It's also safer to always use full paths instead of only filenames.

**Comment by meentix** [comment]
My code is now:

`use mikehaertl\pdftk\Pdf;

// Fill form with data array
$pdf = new Pdf('/var/www/vhosts/meentix.aix-cloud.de/httpdocs/fpdm/tkantrag2.pdf', [
    'command' => '/usr/bin/pdftk',
    // or on most Windows systems:
    // 'command' => 'C:\Program Files (x86)\PDFtk\bin\pdftk.exe',
    'useExec' => true,  // May help on Windows systems if execution fails
]);
$pdf->fillForm([
        'Name'=>'Test',
    ])
    ->needAppearances()
    ->saveAs('fillednew.pdf');

// Check for errors
if (!$pdf->saveAs('fillednew.pdf')) {
    $error = $pdf->getError();
}`

But unfortunately still blank page, no pdf is created or filled :-(

**Comment by mikehaertl** [comment]
You don't echo the error. If this is your complete script, it will not output anything in case of an error.

**Comment by meentix** [comment]
Ive activated display_errors in php settings and it shows me the following now:

> Fatal error: Uncaught Error: Class 'mikehaertl\pdftk\Pdf' not found in /var/www/vhosts/meentix.aix-cloud.de/httpdocs/fpdm/phppdftk.php:21 Stack trace: #0 {main} thrown in /var/www/vhosts/meentix.aix-cloud.de/httpdocs/fpdm/phppdftk.php on line 21

**Comment by mikehaertl** [comment]
You obviously did not include the [composer autoloader](https://getcomposer.org/doc/01-basic-usage.md#autoloading). I'm sorry, but please understand that I can not provide a full tutorial on PHP basics here. I'll close this issue as this is not a support forum but for reporting bugs.
