### ISSUE TITLE
multiple actions (send and save pdf)

### ISSUE THREAD

**Issue by meentix** [mikehaertl/php-pdftk#104]
Hello,

I would like to save the pdf and send it to the user at the end, how I can do that? Looks like I can only save it on the server or send it, but I would need both actions for one single pdf instance (actually a new option to e-mail the pdf to one or multiple email-adresses would be great).

**Comment by mikehaertl** [comment]
Sorry, this is beyond the scope of this library. Your question is about PHP basics. I can not tutor you on that. This is a bug reporting system.
