### ISSUE TITLE
Doesn't actually work on PHP 5.3

### ISSUE THREAD

**Issue by maxguru** [mikehaertl/php-pdftk#105]
The `composer.json` file claims support for PHP >= 5.3.0, however, the [] array syntax is used at https://github.com/mikehaertl/php-pdftk/blob/master/src/DataFields.php#L110

It is only available in PHP >= 5.4.

Edit: also at https://github.com/mikehaertl/php-pdftk/blob/master/src/DataFields.php#L151

**Comment by mikehaertl** [comment]
@maxguru Good catch, thanks. I've pushed a fix to master. Can you check if everything now works for you on 5.3?

**Comment by maxguru** [comment]
Sorry, I didn't test everything yet.  So far, things are working.
