### ISSUE TITLE
PDFtk not filling out some multiline fields

### ISSUE THREAD

**Issue by jdillman1989** [mikehaertl/php-pdftk#106]
I'm using PDFtk to fill out interactive PDFs from form entries, but some of the fields in the PDF remain blank. It seems to be affecting some of the multiline fields (`FieldFlags: 4096`), but not all multiline fields.

Here's the PDF I'm trying to fill: http://sandcclaims.jdillman.com/idaho.pdf

This is a sample of the field data of the interactive PDF:

	---
	FieldType: Text
	FieldName: Employer Name Address incl zip
	FieldNameAlt: Employer (Name & Address incl. zip)
	FieldFlags: 4096
	FieldValue: 
	FieldJustification: Left
	---
	FieldType: Text
	FieldName: CarrierAdministrator Claim Number
	FieldNameAlt: Carrier/Administrator Claim Number
	FieldFlags: 0
	FieldValue: 
	FieldJustification: Left
	---
	FieldType: Text
	FieldName: Jurisdiction
	FieldNameAlt: Jurisdiction
	FieldFlags: 0
	FieldValue: 
	FieldJustification: Left
	---
	FieldType: Text
	FieldName: Jurisdiction Claim No
	FieldNameAlt: Jurisdiction Claim No.
	FieldFlags: 0
	FieldValue: 
	FieldJustification: Left
	---
	FieldType: Text
	FieldName: Employers Location Address if different
	FieldNameAlt: Employer’s Location Address (if different)
	FieldFlags: 4096
	FieldValue: 
	FieldJustification: Left
	---
	FieldType: Text
	FieldName: Claims Admin Name Address Phone Number
	FieldNameAlt: Claims Admin (Name, Address & Phone Number)
	FieldFlags: 4096
	FieldValue: 
	FieldJustification: Left
	---

Here's what the FDF file looks like:

	%FDF-1.2 1 0 obj<</FDF<< 
	/Fields[
		<</T(Employer Name Address incl zip)/V(Name Test Submit)>>
		<</T(CarrierAdministrator Claim Number)/V(Carrier Test Submit)>>
		<</T(Jurisdiction)/V(Jurisdiction Test Submit)>>
		<</T(Jurisdiction Claim No)/V(Jurisdiction Claim No. Test Submit)>>
		<</T(Employers Location Address if different)/V(Employer’s Location Test Submit)>>
		<</T(Claims Admin Name Address Phone Number)/V(Claims Test Submit)>>
	] >> >>
	endobj
	trailer
	<</Root 1 0 R>>
	%%EOF

And here's a sample of the code I'm using if it helps:

	$data = [
		'Employer Name Address incl zip' => $entry[15],               // multiline blank
		'CarrierAdministrator Claim Number' => $entry[93],            // multiline filled
		'Jurisdiction' => $entry[95],                                 // single line filled
		'Jurisdiction Claim No' => $entry[96],                        // single line filled
		'Employers Location Address if different' => $entry["98.1"],  // multiline filled
		'Claims Admin Name Address Phone Number' => $entry[155],      // multiline blank
	];

	$pdf = new Pdf(get_template_directory().'/pdf-forms/raw/idaho.pdf');
	$pdf->fillForm($data)
	    ->needAppearances()
	    ->saveAs(get_template_directory().'/pdf-forms/flat/idaho.pdf');

Looking for some kind of solution to get all the fields filling, or at least for some way to test why it's not working.

**Comment by mikehaertl** [comment]
@jdillman1989 I wonder why you get a FDF file. The default in `fillForm()` is actually to use a `XfdfFile`.

Regarding your problem I must say that I'm not really a PDF form expert either. All the code in our library is a collection of hints and notes I found here and there or is contributed code. So if some things don't work, you're a bit on your own. I'd be happy to include a fix, in case you find out what's causing your issue.

To test you can always use `pdftk fill_form` from the command line (if you have a Fdf / Xfdf file). You could try to modify the Xfdf / Fdf  content to figure out, when exactly form filling breaks.

**Comment by jdillman1989** [comment]
Looks like there were some weird characters in the field names of the PDF, thanks for your help!
