### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by bilal07** [mikehaertl/php-pdftk#107]
Hi,
when I run Composer I have the following error : 

Root package 'mikehaertl/php-pdftk' cannot require itself in its composer.json
Did you accidentally name your root package after an external package?

what can I do to fix the problem

thank you

**Comment by mikehaertl** [comment]
I have no idea and this is rather a problem with composer and not with this library. Our `composer.json` has nothing special in it: https://github.com/mikehaertl/php-pdftk/blob/master/composer.json
