### ISSUE TITLE
splitting pdf pages

### ISSUE THREAD

**Issue by bilal07** [mikehaertl/php-pdftk#108]
**Hello Michael**

after I run the command (composer install),  I created an index.php file:

<?php

require 'vendor/autoload.php';

use mikehaertl\pdftk\Pdf;

$pdf = new Pdf('test111.pdf');
$pdf->burst('page_%d.pdf');     // Supply a printf() pattern

?>

test111 => it is a pdf file of 4 pages
I have nothing like result and I have no error message

**thank you for your help**

**Comment by mikehaertl** [comment]
Sorry, this is not for asking for support but for reporting bugs. Please understand that I can not spend time on individual support questions. The README should contain everything you need to get started. If not - please hire a PHP professional to help you out.
