### ISSUE TITLE
how to use cat? and save it to public path laravel?

### ISSUE THREAD

**Issue by ccseptian** [mikehaertl/php-pdftk#109]
Pdf {#533
  +ignoreWarnings: false
  #_tmpFile: null
  #_tmpOutputContentType: "application/pdf"
  #_command: Command {#534
    #_command: "pdftk"
    #_files: array:1 [
      "A" => array:2 [
        "name" => "C:\Users\Awesome\AppData\Local\Temp\phpD6A5.tmp"
        "password" => null
      ]
    ]
    #_options: []
    #_operation: null
    #_operationArgument: []
    #_escapeOperationArgument: false
    +escapeArgs: true
    +escapeCommand: false
    +useExec: false
    +captureStdErr: true
    +procCwd: null
    +procEnv: null
    +procOptions: null
    +locale: null
    #_stdIn: null
    #_args: []
    #_execCommand: null
    #_stdOut: ""
    #_stdErr: ""
    #_exitCode: null
    #_error: ""
    #_executed: false
  }
  #_handle: 1
  #_error: ""
  #_output: null
  #_data: null
  #_data_utf8: null
  #_dataFields: null
  #_dataFields_utf8: null
  #_pdf: null
}

**Comment by mikehaertl** [comment]
Sorry, this is not for asking for support but for reporting bugs. Please understand that I can not spend time on individual support questions. The README should contain everything you need to get started. If not - please hire a PHP professional to help you out.
