### ISSUE TITLE
Filled pdf is no longer editable

### ISSUE THREAD

**Issue by qdelettre** [mikehaertl/php-pdftk#11]
I filled a pdf with some data and now the result pdf is no longer editable.

How to keep it editable ?

**Comment by mikehaertl** [comment]
You don't show me a single line of code, so I can't help you.

**Comment by qdelettre** [comment]
I was thinking of a general answer, but here is the kind of thing i am doing on this pdf 

http://www.ameli.fr/fileadmin/user_upload/formulaires/S6200.pdf

```php
require_once 'mikehaertl/php-shellcommand/src/Command.php'; 
require_once 'mikehaertl/php-pdftk/src/Command.php'; 
require_once 'mikehaertl/php-tmpfile/src/File.php'; 
require_once 'mikehaertl/php-pdftk/src/FdfFile.php'; 
require_once 'mikehaertl/php-pdftk/src/Pdf.php'; 
use mikehaertl\pdftk\Pdf;

$file_path = './test.pdf';
$pdf_filling_data = array('field'=>'value');

$pdf = new Pdf($mypdf);
$pdf->allow('AllFeatures')
->needAppearances()
->fillForm($pdf_filling_data)
->saveAs($file_path);

```

Thank you.

**Comment by qdelettre** [comment]
Solved by using a copy of the original file. Still doesn't know the meaning of that but it works.

(Karl Zilles's answer of http://stackoverflow.com/questions/10726664/keep-a-pdf-form-editable-after-filling-it-with-pdftk )

**Comment by mikehaertl** [comment]
Sidenote: You should use the composer autoloader instead of including all those files manually.

https://getcomposer.org/doc/01-basic-usage.md#autoloading
