### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by jsat74** [mikehaertl/php-pdftk#112]
Hi! I downloaded the fiels, installed with composer and create thins example:
require("vendor/autoload.php");
use mikehaertl\pdftk\Pdf;

// Get form data fields
$pdf = new Pdf('filled.pdf');
$data = $pdf->getDataFields();

// Get data as string
echo $data;
 $txt = (string) $data;
 $txt = $data->__toString();

but I get this error:
Call to a member function __toString() on a non-object

my php version is 5.5.27

thank you!

**Comment by mikehaertl** [comment]
You should always check the return type, as documented here: https://github.com/mikehaertl/php-pdftk/blob/master/src/Pdf.php#L334

> @return DataFields|bool data about the PDF form fields or false on failure

You can check the error message with `getError()` on the `$pdf` instance. From your code my guess is, that `pdftk` is not found, so you need to configure it in the `command` option:

https://github.com/mikehaertl/php-pdftk#shell-command
