### ISSUE TITLE
Could not copy PDF from tmp location '/tmp/tmp_php_pdftk_dB3mVO.pdf' to 'filled.pdf'

### ISSUE THREAD

**Issue by mt15199** [mikehaertl/php-pdftk#113]
Hello,

I'm getting this error Could not copy PDF from tmp location '/tmp/tmp_php_pdftk_dB3mVO.pdf' to 'filled.pdf', I installed the script on my VPS and installed PDFTK

My code is below:

```
<?php
require 'vendor/autoload.php';
use mikehaertl\pdftk\Pdf;

$pdf = new Pdf('textfields-with-same-name.pdf', [
    'command' => '/usr/bin/pdftk',
	'useExec' => true
]);

$pdf->fillForm([
        'Text' => 'Lorem ipsum'
    ])
->needAppearances()
->saveAs('filled.pdf');

// Check for errors
if (!$pdf->saveAs('filled.pdf')) {
    $error = $pdf->getError();
	echo $error;
}
?>
```

May I know how to fix  this error I've already added write permission to /tmp and var/tmp folder via Ubuntu terminal?

**Comment by its-stark** [comment]
Liebe Kunden und Geschäftspartner,

vielen Dank für Ihre Nachricht.

Ich bin von Samstag, dem 10.03. bis Dienstag den  21.03. im Urlaub. Ab Mittwoch den 22.03. bin ich wieder für Sie da und beantworte gerne Ihre Nachricht.

Viele Grüße,
Thomas Stark.

**Comment by mikehaertl** [comment]
You obviously have no write permission to the current dir, where you want to write `filled.pdf` to. Please better use a full path to be explicit where exactly you want to write to.

**Comment by mt15199** [comment]
Hi Mike,

Thank you for so much for your fast response.
Your advice solved the issue, I changed directory as below and provided a recursive permission via Ubuntu terminal to destination folder.

`->saveAs($_SERVER["DOCUMENT_ROOT"].'/podio/filled.pdf');`

Thank you again :)
