### ISSUE TITLE
Filled checkboxes the check mark is so small when view in Google Chrome

### ISSUE THREAD

**Issue by mt15199** [mikehaertl/php-pdftk#114]
Filled checkboxes is so small when view in Google Chrome, is there a way to solve this?
The PDF template looks good when view in Google Chrome, the tick mark of checkboxes is fine. But after it was filled out the check mark is so small. However, when downloaded the PDF and opened it with external tool like NitroPDF the check mark is fine.

![{PDF template opened in Google chrome - checkbox mark size is ok](https://user-images.githubusercontent.com/31434956/37522866-41188792-2960-11e8-9e5e-e6ad2caf7a3c.png)
![Filled checkboxes when open with PDF application nitropdf](https://user-images.githubusercontent.com/31434956/37522869-418ba1b4-2960-11e8-9499-52f6b98063cb.JPG)
![Filled checkboxes when open using google chrome](https://user-images.githubusercontent.com/31434956/37523147-04ff5b72-2961-11e8-94d7-4329882c8ded.JPG)

**Comment by mikehaertl** [comment]
Sorry, this has nothing to do with our library. You have to style the PDF with the software that you use to create the PDF. pdftk is only adding data - it does no styling at all.
