### ISSUE TITLE
There is little issue.

### ISSUE THREAD

**Issue by WolfMartin** [mikehaertl/php-pdftk#115]
Please help me.
I am trying to use your source code.
but $pdf->getData() returns false;
in my mind the way to use your source code is wrong on my side.

**Comment by mikehaertl** [comment]
Sorry, I can't provide support for how to use the library. It's all in the README. This here is for reporting bugs.

**Comment by WolfMartin** [comment]
I am beginner on PDF operation.
I downloaded your source code, but i don't know the way to use.

**Comment by WolfMartin** [comment]
I installed composer.

**Comment by WolfMartin** [comment]
your help would be appreciate.

**Comment by mikehaertl** [comment]
Again: I'm sorry, but I can't provide any support. You should probably try to hire a PHP professional to help you out.

**Comment by WolfMartin** [comment]
ok. thanks

**Comment by WolfMartin** [comment]
Hi. i have to install pdftk server?
