### ISSUE TITLE
Using issue.

### ISSUE THREAD

**Issue by WolfMartin** [mikehaertl/php-pdftk#116]
Hi, mikehaertl.
I installed only XAMPP Server and composer.
i used "composer require mikehaertl/php-pdftk";
and i created index.php with code:
<?php
require_once('vendor\autoload.php');
use mikehaertl\pdftk\Pdf;

$pdf = new Pdf('D://test.pdf');
$data = $pdf->getData();
echo $data;
?>

but i didn't get the result.
$data always is false.
i just need to get pdf data.
I think you can help me.
Thanks

**Comment by WolfMartin** [comment]
![image](https://user-images.githubusercontent.com/37792895/37897269-ac682bd8-309a-11e8-8fc8-bd6a6b134628.png)
please check my screenshot

**Comment by mikehaertl** [comment]
I've already explained you, that I can not do any private support. Please respect that and don't abuse this bug tracker for any questions.

**Comment by WolfMartin** [comment]
if i pay for that?
