### ISSUE TITLE
Strange issues

### ISSUE THREAD

**Issue by maxguru** [mikehaertl/php-pdftk#117]
I am perplexed, confused, bewildered, ...

I was testing my code with random PDF files and hit a very strange issue with pdftk and php-pdftk when dealing with encrypted files.

First off, my local system's pdftk claims to be the same version as one running in my docker container based on ubuntu:16.04. However, the behavior seem completely different.

When I am on a local system and I feed it [a random encrypted PDF file I found online](http://www.china-embassy.org/chn/lszj/bgxz/P020130830121570742708.pdf), it refuses to give me fields.

```
# pdftk P020130830121570742708.pdf dump_data_fields_utf8
Error: Failed to open PDF file: 
   P020130830121570742708.pdf
   OWNER PASSWORD REQUIRED, but not given (or incorrect)
Done.  Input errors, so no output created.
```

However, when I am inside my docker container (on my local system), I get a warning in stderr and the fields in stdout,
```
# pdftk P020130830121570742708.pdf dump_data_fields_utf8
WARNING: The creator of the input PDF:
   P020130830121570742708.pdf
   has set an owner password (which is not required to handle this PDF).
   You did not supply this password. Please respect any copyright.
---
FieldType: Text
FieldName: fill_4
FieldNameAlt: 姓 Last name
FieldFlags: 8388608
FieldJustification: Center
---
FieldType: Text
FieldName: fill_5
FieldNameAlt: 中间名 Middle name
FieldFlags: 8388608
FieldJustification: Center
---
...
```
note: ... means there is more output

This is not such a big problem in itself, however, I get more strange behavior differences with php-pdftk code between my local docker container and one in a cloud vm,

Code:
```
$pdf = new \mikehaertl\pdftk\Pdf($this->get_filepath(), $this->get_pdftk_exec_options());
$data = $pdf->getDataFields();
print_r($data);
```

Output from my local docker container running off the same image as the cloud vm docker container,
```
mikehaertl\pdftk\DataFields Object
(
    [_string:mikehaertl\pdftk\DataFields:private] => WARNING: The creator of the input PDF:
   /var/www/Model/../html/files/nuMAk3BqUTPU9Vez5IjmDcwUfzumW6C2w2W4ma3MMOesGwkYtq5adN2Ksq2.pdf
   has set an owner password (which is not required to handle this PDF).
   You did not supply this password. Please respect any copyright.
---
FieldType: Text
FieldName: fill_4
FieldNameAlt: 姓 Last name
FieldFlags: 8388608
FieldJustification: Center
---
FieldType: Text
FieldName: fill_5
FieldNameAlt: 中间名 Middle name
FieldFlags: 8388608
FieldJustification: Center
---
...
    [_array:mikehaertl\pdftk\DataFields:private] => Array
        (
            [0] => Array
                (
                    [WARNING] =>  The creator of the input PDF:
                    [   /var/www/Model/../html/files/nuMAk3BqUTPU9Vez5IjmDcwUfzumW6C2w2W4ma3MMOesGwkYtq5adN2Ksq2.pdf] => 
                    [   has set an owner password (which is not required to handle this PDF).] => 
                    [   You did not supply this password. Please respect any copyright.] => 
                )

            [1] => Array
                (
                    [FieldType] => Text
                    [FieldName] => fill_4
                    [FieldNameAlt] => 姓 Last name
                    [FieldFlags] => 8388608
                    [FieldJustification] => Center
                )
...
```

Output from cloud vm docker container,
```
mikehaertl\pdftk\DataFields Object
(
    [_string:mikehaertl\pdftk\DataFields:private] => WARNING: The creator of the input PDF:
   /var/www/Model/../html/files/NCx8Id3lrIytoVzWOKbMUB5Q4Q5qbDpbqovE12JlMSm9DvWFXoHUkX4gYPR.pdf
   has set an owner password (which is not required to handle this PDF).
   You did not supply this password. Please respect any copyright.
---
FieldType: Text
FieldName: fill_4
FieldNameAlt: 姓 Last name
FieldFlags: 8388608
FieldJustification: Center
---
FieldType: Text
FieldName: fill_5
FieldNameAlt: 中间名 Middle name
FieldFlags: 8388608
FieldJustification: Center
---
...
    [_array:mikehaertl\pdftk\DataFields:private] => Array
        (
            [WARNING] => The creator of the input PDF:
            [FieldType] => Array
                (
                    [0] => Text
                    [1] => Text
                    [2] => Text
                    [3] => Text
                    [4] => Text
                    [5] => Text
                    [6] => Text
                    [7] => Text
                    [8] => Text
                    [9] => Text
                    [10] => Text
                    [11] => Text
                    [12] => Text
                    [13] => Text
                    [14] => Text
                    [15] => Text
                    [16] => Text
                    [17] => Text
                    [18] => Text
                    [19] => Text
                    [20] => Text
...
                )

            [FieldName] => Array
                (
                    [0] => fill_4
                    [1] => fill_5
                    [2] => fill_6
                    [3] => fill_7
                    [4] => fill_8
                    [5] => fill_9
                    [6] => fill_10
                    [7] => fill_11
...
```

There is a number of things to note in the above output,
1. stderr output appers in the DataFields array (probably should be fixed)
2. clearly there is something screwy going on with the php-pdftk code on the cloud vm (see "[WARNING]"; but why not on my local macine? it is the same exact docker image!)
3. `$data` is still usable in the local docker container case but not in the vm case

Any ideas?

**Comment by mikehaertl** [comment]
I can't tell you why things work in some of your setups and not in other. pdftk is not a perfect piece of software and may behave strange in some scenarios. Maybe you also used different versions. To me the most significant message is really **OWNER PASSWORD REQUIRED, but not given (or incorrect)**. So you should provide that password to make that warning go away.

**Comment by maxguru** [comment]
PDFtk outputs fields even with the warning.  It seems to me the correct course of action is to ignore the warning (stderr).

It seems from this code that we need to set `captureStdErr` to `false`,
https://github.com/mikehaertl/php-shellcommand/blob/master/src/Command.php#L40
https://github.com/mikehaertl/php-shellcommand/blob/master/src/Command.php#L329

Thoughts?

**Comment by maxguru** [comment]
Regarding the difference in behavior between vm and local containers, I suspect it is another on of those PCRE bugs perhaps related to the kernel.  I've hit a nasty one a few years ago, so I think it is not entirely out of the question.  Although, I may be wrong.

**Comment by mikehaertl** [comment]
> It seems from this code that we need to set captureStdErr to false

This setting only has an effect if you have set `useExec`, see here:

https://github.com/mikehaertl/php-pdftk#shell-command

You can also set `captureStdErr` this way and see if it makes a difference.

I'd rather try to strip any warnings from the top of pdftk's output. Working on it right now...

**Comment by mikehaertl** [comment]
I've pushed a fix to master. It strips any 'WARNING:...' line plus all following lines starting with a space from the top which leaves only the valid field output.

This is far from perfect, I know as it's assuming that all warnings from pdftk look the same. This does not neccessarily have to be the case. But I couldn't find the relevant sources.

Could you help testing this please?

**Comment by mikehaertl** [comment]
Which version of pdftk are you using? I found the sources for pdftk 2.02 but it seems their warnings are formatted a little different. So maybe we can improve the fix.

**Comment by mikehaertl** [comment]
Ok, wait a second. I now see what you wrote above about `stderr` appearing in `stdout`. This should really never be the case unless you've set `useExec`.

So are you using this option?

**Comment by maxguru** [comment]
Yes, I have it set to use exec().

I am using pdftk in ubuntu:16.04 docker container (2.02).  This is where I get the warning.  My local system's (Gentoo) pdftk claims to be 2.02 as well, however, I get an error instead of warning.

I can help testing.  What exactly do I need to test?

**Comment by maxguru** [comment]
By the way, I tried it with proc_open() and I don't get the warning in DataFields and things are working fine.

**Comment by mikehaertl** [comment]
> By the way, I tried it with proc_open() and I don't get the warning in DataFields and things are working fine.

Then everything is fine. Just don't use `useExec`. It's only a workaround feature in cases where `proc_open()` doesn't work. `useExec` has the drawback, that you can't capture stderr easily. But if you still want to use it, you could have set `captureStdErr` to `false` to avoid stderr appearing at stdout.
