### ISSUE TITLE
am unable to save the PDF.

### ISSUE THREAD

**Issue by adityarw** [mikehaertl/php-pdftk#119]
error details =>ErrorException (E_NOTICE)
tempnam(): file created in the system's temporary directory

**Comment by mikehaertl** [comment]
?

**Comment by gadget00** [comment]
tried to save it in a directory that didn't exist? maybe a typo in your code?

**Comment by mikehaertl** [comment]
I will close issues without even the smallest code example and some details how the error happened - sorry.

**Comment by Avemaar** [comment]
for me the error appeared when in the File.php i tried to manually chaned the $directory variable contant to show to my web application dir_root to test it if it is there a real permission error
