### ISSUE TITLE
Java exception when trying to generate lots of PDFs

### ISSUE THREAD

**Issue by mikefrancis** [mikehaertl/php-pdftk#122]
Hi,

We have a PDF generating API which uses this library. It works great for ad-hoc requests (1, maybe 2 in a short period of time) but when trying to do 10+ at once we get the following error:

```
Unhandled Java Exception in create_output():
ExceptionConverter: Unhandled Java Exception in main():
Aborted (core dumped)
```

I am guessing this is an issue with pdftk but do you know of any similar use cases and how they might have been solved?

**Comment by mikehaertl** [comment]
Sorry, I have no idea. But I agree that this is probably a problem with pdftk itself as our library is totally unrelated to Java. Maybe you can try to reproduce the issue with a simple shell script where you call pdftk in a similar way. AFAIK pdftk is not really maintained anymore, so I can't even recommend where to report any bugs.

Closing this as I don't think it's related to our library.
