### ISSUE TITLE
pdftk on shared hosting

### ISSUE THREAD

**Issue by CarCarlo1977** [mikehaertl/php-pdftk#124]
Hi Mike! thanks for your useful app!
i have a problem in using it on a shared hosting server with laravel.
The following script with exec function works fine:

"<php
error_reporting(E_ALL);
ini_set('display_errors', 1);
echo exec("LD_PRELOAD='/home/zwcafsem/lib/libgcj.so.12' /home/zwcafsem/bin/pdftk  temp.pdf output temp2.pdf");
exit;
?>"

but... how i can set that values in new Pdf function on laravel controller? 
I tried to add 'command' option with following  code but still no success.

$pdf = new Pdf('/pdftemp/temp.pdf',
      [
        'command' => "/home/zwcafsem/bin/pdftk",
        ]);

THANKS!

**Comment by mikehaertl** [comment]
You can try to set the `LD_PRELOAD` value as env var in the `procEnv` option (Documented [here](https://github.com/mikehaertl/php-shellcommand#api)). Something like this:

```
$pdf = new Pdf('/pdftemp/temp.pdf',
[
    'command' => "/home/zwcafsem/bin/pdftk",
    'procEnv' => [
        'LD_PRELOAD' => '/home/zwcafsem/lib/libgcj.so.12',
    ],
]);
```

If this doesn't work then I don't know either. This `LD_PRELOAD` seems to be some kind of hack to make pdftk work. I don't think that we will add support for things like this.

**Comment by CarCarlo1977** [comment]
Mike, still not working... anyway thanks for support!
then... you are saying that i can't put in command string this "LD_PRELOAD='/home/zwcafsem/lib/libgcj.so.12' /home/zwcafsem/bin/pdftk as a shell command?

**Comment by mikehaertl** [comment]
I just don't know. We use [proc_open()](http://php.net/manual/en/function.proc-open.php) to execute pdftk and as it has the option to pass env vars I'd have expected that's the way how to do it correctly. You could also try to set the `useExec` flag which will use [exec()](http://php.net/manual/en/function.exec.php) instead.

Check here for all the options: https://github.com/mikehaertl/php-shellcommand

**Comment by CarCarlo1977** [comment]
Can i set it to true in Command.php on line

public $useExec = false; ?



Carlo Caligiuri

**Comment by mikehaertl** [comment]
It's an option like any other. See the example in the README: https://github.com/mikehaertl/php-pdftk#shell-command

**Comment by jeremyelka** [comment]
hi mike,great app you did!!
i have a probleme ,maybe you can help me...i use the app in localhost and it is working great,
but when i try to use it in the server (not dedicated server) its not working...
