### ISSUE TITLE
pdf-stapler instead of pdftk

### ISSUE THREAD

**Issue by RusAlex** [mikehaertl/php-pdftk#125]
Are you going to implement a pdf-stapler version of your tool ? 

Thanks.

**Comment by mikehaertl** [comment]
I had never heard of it, thanks for the pointer. But so far I have no plans. This would be another package anyway like php-stapler or something, because stapler has different command options.

**Comment by fr3nch13** [comment]
What about phpoffice?

-------------
Brian French
703-507-5383

**Comment by mikehaertl** [comment]
> What about phpoffice?

How is it related to pdftk?
