### ISSUE TITLE
Problems unchecking a button

### ISSUE THREAD

**Issue by jbirch8865** [mikehaertl/php-pdftk#129]
I'm having issues unchecking a box.  My question below is an assumption that I have discovered my problem.  But I could be missing else something here is my logic ->

I have a form that I captured the dump_data_fields and saw the FieldValue of the Button was 'Off'. Then I opened the pdf in Adobe Reader -> checked the box -> saved it and redumped the data fields. Now the FieldValue is 'Yes'. Everything is great. However if I use fillForm(['Button' => 'Off']) the checkbox is still checked. So I opened the file in reader again and unchecked the box. Then dumped the data fields and noticed the FieldValue is missing altogether. It isn't even a key in the field list. Is there anyway to use fillForm() and remove the FieldValue parameter entirely from a valid field?

**Comment by mikehaertl** [comment]
This doesn't look like an issue with our library. You must be missing something. If you still think something is broken, please provide a small example code and PDF that demonstrates the issue.

**Comment by jbirch8865** [comment]
[InspectionSheet.945FTG.pdf](https://github.com/mikehaertl/php-pdftk/files/2309809/InspectionSheet.945FTG.pdf)
Here is the PDF I am working with.  When you open it there are a bunch of checkboxes that are currently checked by default in the "Good" Column.  

[945.txt](https://github.com/mikehaertl/php-pdftk/files/2309819/945.txt)
Here is a text file with the content of pdftk InspectionSheet.945FTG.pdf dump_data_fields

[CompleteInspection2.txt](https://github.com/mikehaertl/php-pdftk/files/2309898/CompleteInspection2.txt)
Here is my code that is supposed to take an incoming POST request and compare the POST keys with the known array of fields 

The outcome should be, after confirming the array that is being sent to fillForm() contains all the button FieldValues are set to 'Off' except 'Engine Service.0.0' that is now set to 'Yes', that all check-boxes are unchecked except Engine Service.0.0 [Which correlates with the "needs service" checkbox for "Engine Performance"].
However after I run the php file on my web-server the PDF file still shows all the previously checked boxes as checked plus the Engine Service.0.0 box.  All the text fields successfully clear but I am trying to find anything that will deselect any of the previously checked boxes so that is where I ran through the logic in my original question and found that Adobe Reader wasn't setting the FieldValue to 'Off' to get the check-boxes to show as unchecked but instead removed the FieldValue altogether.  But using your library I couldn't see how I would be capable of doing this.

Any ideas would be so appreciated.
