### ISSUE TITLE
Radio Buttons Value is not selecting in the editable pdf generating using this tool

### ISSUE THREAD

**Issue by Antara-Mohaniya** [mikehaertl/php-pdftk#130]
Hi,

This is array of pdf that we are getting for the button field :- 
```
 [13] => Array
        (
            [FieldType] => Button
            [FieldName] => MCSA-5875[0].Page1[0].driverPersonal[0].genderGroup[0].genderButtons[0]
            [FieldFlags] => 49152
            [FieldValue] => Off
            [FieldJustification] => Left
            [FieldStateOption] => Array
                (
                    [0] => 0
                    [1] => 1
                    [2] => 2
                    [3] => Off
                )

        )
```
we are using this kind of code for accessing the field value :- 

 ```
$pdf = new Pdf(storage_path('MedicalExaminationReportForm_091616_MCSA_5875.pdf'));
 $pdf->fillForm([
'MCSA-5875[0].Page1[0].driverPersonal[0].genderGroup[0].genderButtons[0]' =>'1',
])
            ->needAppearances()
            ->saveAs(storage_path('filled2.pdf'));

```
we have used different values like 0 , 2 , and off also but no change.
Here i'm attaching the screenshot:- 

![pdf](https://user-images.githubusercontent.com/42766255/44710191-20c91e80-aac9-11e8-8852-bb293ac984af.png)

It's not working please help as soon as possible. 

Thanks.

**Comment by mikehaertl** [comment]
Do you have any chance to rename this field to something simpler? I'm not really an expert on PDF forms so I don't know how the form data must look for weird looking field names like this.

**Comment by Antara-Mohaniya** [comment]
Hi,[https://www.fmcsa.dot.gov/sites/fmcsa.dot.gov/files/docs/MedicalExaminationReportForm_091616_MCSA_5875.pdf]
This is the link of the pdf form that we are using and this has been used by the US government. We cannot rename the field. And actually the problem is not related to the field name as for the following field types such as the checkbox, dropdown, and text everything is working fine they are easily editable but the only problem is with the Radio Button.  Any help is appreciated.

Thanks in advance.

**Comment by mikehaertl** [comment]
I will not find time to look at this. But you could probably help yourself: We need to find out, how the XFDF file must look for this particular case. That's not hard to do. See here, how you create an XFDF file from PHP: https://github.com/mikehaertl/php-pdftk#create-a-xfdffdf-file-from-a-php-array

This is a XML file, so you can edit it with any text editor. Then you can use `pdftk` on the command line like this to fill the PDF from your XFDF file: `pdftk input.pdf fill_form my.xfdf output.pdf`.

Maybe you can also try to fill the form in a PDF reader and save the form data as XFDF. Then you can compare the XFDF file contents and find out, what's wrong.

With this information we can then add a fix to our library here.

**Comment by Antara-Mohaniya** [comment]
It's already in the XFDF format that's why we are able to generate the values and fill them in the existing pdf. But for radio button only it's not working.
Is there any other way out? I'll be glad if you can provide me with any help.
Thanks.

**Comment by mikehaertl** [comment]
You should manually edit the XFDF until you find out, how the form name must be written so that it works.

**Comment by rvarkelen** [comment]
Great library @mikehaertl , thanks. I've just tested this issue and everythings seems to work just fine using version `0.5.0`:

```
$fillable = [
    'MCSA-5875[0].Page1[0].driverPersonal[0].genderGroup[0].genderButtons[0]' => '0'
];

$pdf = new Pdf(resource_path('pdf/mcsa.pdf'));
$pdf->fillForm($fillable)
    ->needAppearances()
    ->saveAs(resource_path('pdf/test2.pdf'));
```
**Results in: M selected**
![afbeelding](https://user-images.githubusercontent.com/548384/48977790-659d2b00-f0a1-11e8-8ba3-500fd7305bfb.png)

```
$fillable = [
    'MCSA-5875[0].Page1[0].driverPersonal[0].genderGroup[0].genderButtons[0]' => '1'
];

$pdf = new Pdf(resource_path('pdf/mcsa.pdf'));
$pdf->fillForm($fillable)
    ->needAppearances()
    ->saveAs(resource_path('pdf/test2.pdf'));
```
**Results in: M and F both selected**
![afbeelding](https://user-images.githubusercontent.com/548384/48977829-43f07380-f0a2-11e8-9dad-8d9b70496fc4.png)

```

$fillable = [
    'MCSA-5875[0].Page1[0].driverPersonal[0].genderGroup[0].genderButtons[0]' => '2'
];

$pdf = new Pdf(resource_path('pdf/mcsa.pdf'));
$pdf->fillForm($fillable)
    ->needAppearances()
    ->saveAs(resource_path('pdf/test2.pdf'));
```

**Results in: F selected**
![afbeelding](https://user-images.githubusercontent.com/548384/48977863-0a6c3800-f0a3-11e8-964d-70b4cc3f9516.png)
