### ISSUE TITLE
Get Output directly

### ISSUE THREAD

**Issue by WoutervanderLoopNL** [mikehaertl/php-pdftk#131]
Hello. 

is it possible when you fill the form of an pdf. you get de output directly of the file. get the encoded string of the pdf, instead of saving the pdf. that would be great.

**Comment by WoutervanderLoopNL** [comment]
nvm, got it from getting the temp file. ;-)

**Comment by WoutervanderLoopNL** [comment]
yeah, that would be great ;-)

**Comment by mikehaertl** [comment]
@WoutervanderLoopNL I've added the method. There's no new release yet, though. Maybe you could have a quick look at the implementation if it works for you? I'd issue a new release right after your confirmation.

**Comment by WoutervanderLoopNL** [comment]
hi, 

yeah i was bussy last days with other thing, i will look into this tonight.

**Comment by WoutervanderLoopNL** [comment]
> @WoutervanderLoopNL I've added the method. There's no new release yet, though. Maybe you could have a quick look at the implementation if it works for you? I'd issue a new release right after your confirmation.

Its working!, thanks. 

you can add it to the new version

**Comment by mikehaertl** [comment]
0.5.0 released, thanks for your help.
