### ISSUE TITLE
Chaining commands fails starting with getDataFields

### ISSUE THREAD

**Issue by c0pp3rt0p** [mikehaertl/php-pdftk#135]
When performing a chain of commands like getDataFields, fillForm, getDataFIelds, the second command fails (fillForm).  I'v followed things back to the temp files that are generated on subsequent commands and it appears they aren't actually being written.  They are there, but of 0 size.  Consequently when the next command runs, it fails to read in the file.

see this [SO article](https://stackoverflow.com/q/52767092/8549479) for more detail.

**Comment by mikehaertl** [comment]
You've seen this note in the README?

> IMPORTANT: You can always only perform one of the following operations on a single PDF instance. Below you can find a workaround if you need multiple operations.

So you can't chain commands.
