### ISSUE TITLE
$pdf->addFile - can not be dynamic 

### ISSUE THREAD

**Issue by tanmayapatra09** [mikehaertl/php-pdftk#136]
$pdf->addFile('url_to_file.pdf'); // This is working
$pdf->addFile($fileUrl); // This is Not working.

Please suggest me where I am wrong 

$pdf = new Pdf();
        foreach ($filesArray as $pdfKey => $pdfUrl) {
            $pdf->addFile($pdfUrl);  **// NOT WORKING**
        }
$pdf->saveAs('C:\xampp\htdocs\project\assets\merged\New_pdf'.$exportFileName.'.pdf');

**Comment by mikehaertl** [comment]
Sorry, but this makes no sense. The problem must be somewhere in your code. Obviously `$pdfUrl` is not correctly defined.
