### ISSUE TITLE
Can it fill image to the form by fillform() or other way?

### ISSUE THREAD

**Issue by letsGitNow** [mikehaertl/php-pdftk#138]
the pdf template has one field of button "image" to be filled. And I pass data array param ["image"=>"/path/to/image.jpg"] to  fillform function. But it doesn't work.Can it fill image to the form by fillform()?

**Comment by mikehaertl** [comment]
Sorry, this is not a support forum but for reporting bugs. If it doesn't work for you, you probably missed something, so please check the README again (i.e. maybe set the path to your `pdftk` executable)
