### ISSUE TITLE
text with RTL direction issue

### ISSUE THREAD

**Issue by MatanMaimon** [mikehaertl/php-pdftk#139]
Hello,
my filled pdf file is good but I write in Hebrew and found that the RTL language is reversed..

There is any fix or workaround for that (without using reversing letter in php or any algorithem like this).

Thanks!

**Comment by mikehaertl** [comment]
I'm sorry, but I just don't know. Maybe RTL is an option you can set on the PDF input fields when you create the form. Unless there's really pdftk option somehwere (we did not write it!), we can't do anything here about it.
