### ISSUE TITLE
Not producing files (sometimes)

### ISSUE THREAD

**Issue by rhousham** [mikehaertl/php-pdftk#14]
Hi I have your script in a loop to create serveral pdf's.
This works most of the time but sometimes no file is made, no reason in the getError.
Nothing back from the exec function (using windows)

All quite odd, going to try just using straight exec with the function see if I get anywhere

**Comment by mikehaertl** [comment]
Please check out this thread (different tool, but same base package php-shellcommand is used). Your problem is probably related: 

https://github.com/mikehaertl/phpwkhtmltopdf/issues/56

The differenc here is, that you can pass the options for the `Command` as second parameter in the constructor.

**Comment by rhousham** [comment]
I think it might be a problem with the actual program, if I just go for the exec($cmd) then it works but there is a lag between it running - even if this is command line and producing the file.

Thus if I call is_file just after it fails.

I have tried a while
while(!is_file(xxxxxxxx)) {
   sleep(4);
}

but php isn't happy with that.
I'll check that post.
Ta's

**Comment by rhousham** [comment]
Yeah it a problem with the program, if you output using stdoutput then some of the files are just blank.
Run it again and they are there, most strange.

**Comment by mikehaertl** [comment]
I can not really help you much. I don't use Windows and can't say, how pdftk behaves there. I'm happy to include any bugfixes, though, if you find out what's wrong there.

**Comment by rhousham** [comment]
Sure - it's a real big pain.

**Comment by mikehaertl** [comment]
I close this for now, as the issue only exists on Windows. I don't intend to include workarounds for all weird PHP + Windows issues. If the suggested workaround with `useExec` doesnt' work, there's not much we can do. If you find a real bug and can provide code to reproduce it each time, feel free to open another issue.

**Comment by rhousham** [comment]
Well if you've read this far you'll want to know the answer, it's not pretty!
I made a bat file like this.
"C:\Program Files (x86)\PDFtk Server\bin\pdftk.exe" "%1" fill_form "%2" output "%3" drop_xfa need_appearances flatten dont_ask verbose
ping 1.1.1.1 -n 1 -w 200 > nul

which when you pass in the files seemed to work 99% of the time, I then do another loop just to check and then pick up any of the remains.

Annoying I know, and that was a pain to work out - but works and is god for time.

UNLEASHING RAGE
432l;1m 432k1ln 4jkl321 43jkl124 jkl321 543l12!!

!
!

Moving on......................

**Comment by rhousham** [comment]
Even then I wrote a cleanup script checking that the file was created and removing from an array.
Messy but it seems to be the only way - thanks for your help.
