### ISSUE TITLE
Installing pdftk command inside docker application

### ISSUE THREAD

**Issue by JeremyMulvihill** [mikehaertl/php-pdftk#140]
My application is running in a docker container and I can seem to get pdftk installed as a container and then have the application recognize it.

**Comment by mikehaertl** [comment]
Not sure what you want from me. This is is for reporting bugs.

**Comment by mikehaertl** [comment]
I can not help you with that decision. Personally I would of course install it in the same container where PHP runs.

**Comment by thyronea** [comment]
add these codes inside your PHP.Dockerfile:

RUN mkdir -p /usr/share/man/man1mkdir -p /usr/share/man/man1

RUN apt-get update

RUN apt-get install -y pdftk
