### ISSUE TITLE
pdftk does not recognise data fields in php

### ISSUE THREAD

**Issue by marcfreiheit** [mikehaertl/php-pdftk#141]
Good evening. 

I'm using your library for a while in a project and it worked fine. Since a couple of days, the php code can't obtain the data fields from a pdf file. I need some assistance in tracking the error.

The related code snippet:
```php
    private function extractSignatureFields($inputFile, $contractTemplateId) {
      $this->getModel("file")->downloadFile($inputFile);

      $inputPath = SOURCE_ROOT . TMP_PATH . $inputFile;

      if (!file_exists($inputPath)) {
         return "File does not exist.";
      }

      $pdf = new Pdf($inputPath);
      $fields = $pdf->getDataFields();
      if (!$fields) {
        return "File does not contain any data fields.";
      }

      ...
}
```
The function returns because no data fields are found. I've checked with Adobe Acrobat that there are named data fields and validated it with the command line `pdftk` program.

When I run `pdftk <file> dump_data_fields > field_names.txt` it works just fine and extracts the data fields. 
result:
```
 ---
FieldType: Text
FieldName: cust.last_name
FieldFlags: 0
FieldJustification: Left
---
FieldType: Text
FieldName: cust.sig Vertrag
FieldFlags: 0
FieldJustification: Left
---
FieldType: Text
FieldName: dist.sig Vertrag
FieldFlags: 0
FieldJustification: Left
```

Screenshot from vdebug:
![screen shot 2018-11-16 at 19 21 37](https://user-images.githubusercontent.com/27914201/48639779-ec347700-e9d4-11e8-9645-1707829c1047.png)

Some data about my setup:
Apache Version | Apache/2.4.29 (Unix) PHP/7.2.1 OpenSSL/1.0.2g
pdftk is installed via composer:
```json
{
    "require": {
        "mikehaertl/php-pdftk": "0.4.4",
        "stripe/stripe-php": "^6.17"
    },
    "require-dev": {
        "robmorgan/phinx": "0.8.1"
    }
}
```

To be honest, I'm not even sure how to properly track down the error. Do you have any hints how to debug my issue? 

Greetings!

**Comment by marcfreiheit** [comment]
Okay, got it. Sorry for the inconveniences. My web server runs inside docker and I forgot to install pdftk inside it. 
Shouldn't that throw an error?

**Comment by mikehaertl** [comment]
The library does not throw exceptions but returns `false` on failure. You can obtain the error message with `$pdf->getError()` afterwards.

**Comment by marcfreiheit** [comment]
Okay. When it should return false? I was able to create a pdf object given the path and ->getDataFields() returned nil. Neither the creation of the object nor the method invocation of getDataFields returned false. 
At least I can see on my debug screenshot that the error array is not empty. I'll check that in future.
