### ISSUE TITLE
needAppearance, umlauts and merge multiple files

### ISSUE THREAD

**Issue by Urst** [mikehaertl/php-pdftk#142]
Hi there!

I know there are quite a few similar issues. But none handles my situation. I tried a few things - nothing worked.
I have multiple pdf-form that i have to fill. I fill them seperatly and some of the text also contains umlauts or other UTF-8 characters. Filling them with needAppearance works quite well.

![image](https://user-images.githubusercontent.com/17613512/48764421-e0380600-ecaf-11e8-98cc-7bb646860a41.png)

![image](https://user-images.githubusercontent.com/17613512/48764439-f04fe580-ecaf-11e8-94b0-b416114d3840.png)

Then i need to merge these pdf files to get one big pdf. And thats where things go wrong. My output-pdf does not contain the umlauts anymore. If i click the inputs they show up, so the data is there.

![image](https://user-images.githubusercontent.com/17613512/48764552-3e64e900-ecb0-11e8-931f-61df942b4eeb.png)

Here is how i merge my good looking pdfs:

![image](https://user-images.githubusercontent.com/17613512/48764663-8a179280-ecb0-11e8-9eca-a6d5129f1f2f.png)

Where $files is an array of paths to my pdfs. So it looks like merging the single pdfs doesn take needAppearance into account or messes with the fonts in the original pdf.

Hope someone can help me - thanks a lot.

**Comment by mikehaertl** [comment]
From experience I know that handling unicode in PDFs can be really tricky. I think in a similar case like yours I've split this up into 2 operations. First merge the PDF files, then feed the final pdf into a new instance and call `needAppearances()` there. `pdftk` seems to ignore the `need_appearance` flag when merging files.

```
$pdf = new($files);
$error = $pdf->execute();
if (!$error) {
   $pdf2 = new($pdf);
   $pdf2->needAppearances();
   $err2 = $pdf2->saveAs();
   ...
}
```

**Comment by Urst** [comment]
Hi Mike,
thank you very much - this worked! Maybe this would be a usefull addition to the documentation though. ;)
