### ISSUE TITLE
How do I install this in Laravel?

### ISSUE THREAD

**Issue by hondaman900** [mikehaertl/php-pdftk#143]
I'm using Laravel 5.5 and installed this package as directed, but I'm getting` "Class 'Vendor\mikehaertl\pdftk\Pdf' not found" `errors. It seems like I'm missing some additional steps to register this fully in Laravel so that I can use it in my controller code. Any suggestions or guidance are very welcome.

**Comment by mikehaertl** [comment]
Please read about how to use composer and how to work with namespaces in PHP. I can't provide help with those basic things.

**Comment by hondaman900** [comment]
Thanks Mike - I completely understand. It turns out my issue wasn't with implementation. That worked fine as a plain PHP composer installation, and when testing with your provided tests it worked fine. The issue was my PDF form (provided from elsewhere) was protected, so I had to unblock it and then it worked great. Because this wasn't apparent I thought the issue must have been in the Laravel usage. Hopefully this feedback will help someone else down the road.

Thank you for this awesome package - very much appreciated
