### ISSUE TITLE
BOM While retrieving saved pdf form

### ISSUE THREAD

**Issue by Surdok** [mikehaertl/php-pdftk#149]
When i try to read from an fdf request that is sent by a pdf form, i get the following out of my saved pdf form that i have used the plugin for :

![image](https://user-images.githubusercontent.com/24224586/53339230-ca715700-3916-11e9-852e-9dc7eca6fec2.png)

I tried getting rid of the BOM using a replace function in php with no luck.

**Comment by mikehaertl** [comment]
> When i try to read from an fdf request that is sent by a pdf form

What do you mean by that? Where does the FDF come from? I'm not sure if we can fix anything here.

**Comment by Surdok** [comment]
The pdf file has an ability to post into a php file. The payload request looks like this :
![inx4g](https://user-images.githubusercontent.com/24224586/53357275-8e51ec80-393e-11e9-8378-ff74db93fd36.png)

When i fetched this payload in my php file, from the pdf that is being filled and generated using the plugin, it gave me the characters similar to the first image. I have made alot of testing and found out that filling the pdf using the plugin's function does that.

**Comment by mikehaertl** [comment]
I still don't think, we can do anything here. You have to make sure, that you have a valid FDF. That's part of the code where you handle the POST request, not our library here. We can only do, what pdftk can do. I assume it can't handly your fdf file either, right?

**Comment by Surdok** [comment]
I agree that handling the POST request doesn't have to do with pdftk, but it has to do with the generated filled pdf that pdftk produces, as if i post a request from the generated filled file, it appends these strange characters for some reason.

My doubt here is that the fill function of pdftk does something that generates these strange symbols.

**Comment by mikehaertl** [comment]
Like I said: We can not do, what pdftk can't do. You have to provide a valid FDF file to pdftk. So you have to do the same for this library.

I'm closing this for now as I don't think it's in the scope of this library to fix file format issues that were not even generated by us.
