### ISSUE TITLE
How to fill out an option field in pdf?

### ISSUE THREAD

**Issue by cdheumann** [mikehaertl/php-pdftk#151]
I can't find out, what to do, to fill out an option field inside an option field group (pdf) with a radio button in my web form. 

1. I've got a pdf with 3 option fields ("neuauftrag", "umzug", "tarifwechsel") inside an option field group ("auftrag")
Screens:
[https://imgur.com/rvGRxJk](url)
[https://imgur.com/0qD09zU](url)
2. In my web form, I've got the same fields as radio buttons inside a group.
3. the mapping (filename.pdf.php) looks like this:

```
$mapping = [
	[
		"name" => "neuauftrag",
		"type" => "Button",
		"htmlInputName" => "neuauftrag",
		"defaultValue" => "Off",
	],
	[
		"name" => "umzug",
		"type" => "Button",
		"htmlInputName" => "umzug",
		"defaultValue" => "Off",
	],
	[
		"name" => "tarifwechsel",
		"type" => "Button",
		"htmlInputName" => "tarifwechsel",
		"defaultValue" => "Off",
	],
....

```

In the .xpdf file, the right option is valued with "On" but in the .pdf, the option field is empty.

```
<field name="neuauftrag">
<value>Off</value>
</field>
<field name="umzug">
<value>Off</value>
</field>
<field name="tarifwechsel">
<value>On</value>
</field>
```

I can't find a manual for radio buttons, is there any? How do I have to create the options field in the pdf and how to do the mapping ...?

**Comment by mikehaertl** [comment]
Sorry, but we don't provide support here apart from what you find in the README. You can also check the `tests/` directory where you find test cases and PDFs for all supported form input types. As far as I remember there was nothing really special about radio inputs.
