### ISSUE TITLE
Support pdftk 3.x

### ISSUE THREAD

**Issue by amfische** [mikehaertl/php-pdftk#152]
Hello, 

What would it take to update this package to support the newer versions of pdftk? 

We are switching to Ubuntu 18.04 and it only allows us to install pdftk-java 3.0.0

**Comment by mikehaertl** [comment]
I didn't know about pdftk-java. They say it's a port of pdftk to Java - and surprisingly they use the tests included in *our* library here to verify that the port is successful :smile: 

> So far all code has been manually translated and it passes the test suite of php-pdftk, but a lot more testing is needed.

So I'd assume it should work out of the box.

**Comment by amfische** [comment]
lol that's funny, and interesting 🤔 makes me think it should work out of the box too.

After playing around in Ubuntu 18.04 we discovered we can install pdftk 2.02 via the snap package manager, so we will stick with 2.x for now.

Thank you!

**Comment by mikehaertl** [comment]
So ... are you saying that it does *not*  work with pdftk-java? If not, is there any error? Or what exactly does not work?

**Comment by mikehaertl** [comment]
Also note this comment about a problem with accessing the tmp directory with the snap version: https://github.com/mikehaertl/php-pdftk/issues/150#issuecomment-467053330

**Comment by amfische** [comment]
Sorry for the delayed response, busy work week.

We thought pdftk-java was our issue because our pdf files were not being created, and failed silently. After some more testing, turns out we had the wrong path for pdftk exe, my mistake! After fixing our mistake, pdftk-java seems to be working smoothly with your package.

Thanks for pointing out the issues with the snap version too 🙏
