### ISSUE TITLE
Cannot generate PDF on windows

### ISSUE THREAD

**Issue by manojmilani123** [mikehaertl/php-pdftk#153]
@mikehaertl  I have been creating fillable pdf using filling the fields that I have in the fillable pdf, but for some reasons it throws the below error. Below is my code. Can you please help me find out the issue?

```
$pdf = new Pdf(public_path().'\NC Sales Tax Form.pdf',["useExec" => true,'command' => 'C:\Program Files (x86)\PDFtk\bin\pdftk.exe']);

$pdf->fillForm([
            'xy_asrp1wf_feid'=>'Testing'
        ]);

if(!$pdf->saveAs(public_path()."/fillable.pdf"))
            die($pdf->getError());
```

Error Generated: Unhandled Java Exception in create_output(): java.lang.ClassCastException: pdftk.com.lowagie.text.pdf.PdfName cannot be cast to pdftk.com.lowagie.text.pdf.PRIndirectReference at 0x0059a84e

**Comment by mikehaertl** [comment]
It seems `pdftk` does not work at all on your system. Note, that we can't fix this. This here is only a PHP wrapper around the executable. So you should first make sure, that it runs on your system.

**Comment by manojmilani123** [comment]
@mikehaertl Yes, it is working. I am attaching a screenshot of the working pdftk binary. Please let me know what else can be the issue.

![screen](https://user-images.githubusercontent.com/3876061/56119918-a7643a80-5f8a-11e9-83a4-50ba10b42b15.png)

**Comment by mikehaertl** [comment]
Well, the error you showed is still generated by pdftk itself. You could create a FDF file with our library (see README) and then try on the command line to fill the PDF just to see if this works.

Though I still see no way we can fix anything here.

**Comment by manojmilani123** [comment]
Ok, than you very much

**Comment by manojmilani123** [comment]
Its giving the same error from commandline. Any ideas on this?

**Comment by mikehaertl** [comment]
Like I said: No idea. I'm not the author of pdftk. If you have the option I'd definitely avoid working on Windows. You could even use a docker container to run your app inside in a Linux environment. But I can't provide any support on this, sorry.
