### ISSUE TITLE
Question about missing binary

### ISSUE THREAD

**Issue by willpower232** [mikehaertl/php-pdftk#154]
We are getting along great with this library but have noticed that if it runs without a valid path to a binary, or the binary is not installed at the path specified, then a PDF is generated anyway.

Obviously that is a deployment issue for us but I am wondering if we should be expecting a particular exception or error as one isn't being raised at the minute that I can tell.

**Comment by mikehaertl** [comment]
Uhm, without any `pdftk` on the system, the creation would surely fail. So I would say you *have* it installed. Maybe there's some default version and you usually use your custom version. As long as a `pdftk` is somewhere in the search path, the library will run.

**Comment by willpower232** [comment]
The library runs but doesn't create any output at all if it can't find the binary.

This is the code I am using as a test
```
@unlink(APPPATH . 'test.pdf');

$pdf = new Pdf(APPPATH . 'path/to/pdf/form.pdf');

$pdf->flatten();
$pdf->saveAs(APPPATH . 'test.pdf');

$content = file_get_contents(APPPATH . 'test.pdf');

var_dump(strlen($content));
```

If `pdftk` is uninstalled from the system, the `file_get_contents` call fails because the file doesn't exist. I would have expected that the library would throw an actual catchable or traceable error.

This problem also appears if you pass an array of config to `new Pdf()` with a `command` option to an obviously incorrect path to `pdftk`.

**Comment by mikehaertl** [comment]
From the README:

```
// Check for errors
if (!$pdf->saveAs('my.pdf')) {
    $error = $pdf->getError();
}
```

**Comment by willpower232** [comment]
Aha thank you!
