### ISSUE TITLE
How do you fill out checkboxes  in pdf form try below php code but not working? 

### ISSUE THREAD

**Issue by saqaw** [mikehaertl/php-pdftk#157]
what i am doing wrong,please guide me.
My pdf fields

FieldType: Button
FieldName: aaaa
FieldFlags: 0
FieldValue: Off
FieldJustification: Left
FieldStateOption: Off
FieldStateOption: Yes

here is my code

``ob_start();
require('fpdf.php');
$pdf = new FPDF();
require('fpdm.php');

$fields = array(
'POPMLSAddress' => $_POST['Text3'],
'POPMLSCity' => ' ',
'POPMLSFullPostal'=> ' ',

//'Temp111'    => $_POST['Text4'],
//'Temp222'    => $_POST['Text5'], 

'FLOBuyerName1'    => $_POST['Text6'],
'FLOBuyerName2'=> ' ',
			
'buyer_brokerage'    => $_POST['Text7'],
'offer_date'    => $_POST['Text8'],
'offered_price'    => $_POST['Text9'],
'amount_1'    => $_POST['Text10'],
'amount_2'    => $_POST['Text11'],
'amount_3'    => $_POST['Text12'],
'aaaa'=> 'Yes'
);

$pdf = new FPDM('check1.pdf');
$pdf->Load($fields, false); // second parameter: false if field values are in ISO-8859-1, true if UTF-8
$pdf->Merge();
$pdf->Output();

ob_end_flush(); 
}

**Comment by mikehaertl** [comment]
Wrong repository? This here is not fpdf.

**Comment by saqaw** [comment]
What i did wrong, please forgive me. Don't close this question or please guide me where do i post it.

**Comment by mikehaertl** [comment]
1. This is not a support forum but an issue tracker for reporting bugs. For questions try stackoverflow or similar.
2. In your code you don't even use our library (php-pdftk) but something else. So not sure why you think this belongs here.
