### ISSUE TITLE
Error in real

### ISSUE THREAD

**Issue by rbaldayo** [mikehaertl/php-pdftk#158]
Localhost is working.
Real server is not working. 

path exists with permissions.

Code:

```
 $path = public_path("tmp/laboral/contrato_{$contractName}_{$trabajador->nif_nie}.pdf");
 $pdf = new Pdftk(public_path("downloads/laboral/{$contractName}.pdf"));
 $pdf->fillForm($nameFields)->needAppearances()->saveAs($path);// or dd('Error');

 DB::commit();

 return Response::download($path)->deleteFileAfterSend(true);
```

Error:

`Symfony\Component\HttpFoundation\File\Exception\FileNotFoundException: The file "/var/www/vhosts/directcobro.com/quipo_codigo/public/tmp/laboral/contrato_Indefinido_06270437Q.pdf" does not exist in /var/www/vhosts/directcobro.com/quipo_codigo/vendor/symfony/http-foundation/File/File.php:37`

**Comment by mikehaertl** [comment]
If the file really existed, you wouldn't get this error, right? Must be something else in your code or still a permission thing.

**Comment by rbaldayo** [comment]
The code is the same in localhost as in real. 

I think it's something about permissions. :(

Thanks for answering.
