### ISSUE TITLE
Example in Pdf::shuffle() docblock appears to be innaccurate

### ISSUE THREAD

**Issue by Erutan409** [mikehaertl/php-pdftk#159]
Looking at [this section](https://github.com/mikehaertl/php-pdftk/blob/ace8311507f398806be78f51a7ae7d9ceb24e9fa/src/Pdf.php#L166-L172), it appears that `cat` is used in lieu of `shuffle` in the example.

**Comment by mikehaertl** [comment]
Fixed, thanks!
