### ISSUE TITLE
background pdf discards form fields

### ISSUE THREAD

**Issue by hkraskian** [mikehaertl/php-pdftk#161]
I am trying to put images in the filled form.
The last thing I tried was to create a pdf by fpdf where the images reside.
Then use that pdf as background for my filled pdf.
But this removes form fields.

**Comment by mikehaertl** [comment]
Sorry, this is not a support forum but an issue tracker to report bugs. Your question is also more about features of `pdftk` itself. We only provide a PHP wrapper to exectue pdftk so I can not answer your question.

**Comment by SailingStonesMedia** [comment]
Hope the following helps someone else when they need this.

If you are setting background or stamp and need to fill the PDF, you need to separate these processes (as far as I can tell) and do them one at a time. My working example is:
```
$data = [
    'foo'=> 'bar',
];
    
$error = [];
$pdf = new Pdf('some-pdf.pdf');
$result = $pdf->fillForm($data)
    ->needAppearances()
    ->flatten()
    ->saveAs('final.pdf');

if ($result === false) {
    $error[] = $pdf->getError();
}

$pdf = new Pdf('final.pdf');
$result = $pdf->stamp('signature-doc.pdf')
    ->saveAs('final-with-sig.pdf');

if ($result === false) {
    $error[] = $pdf->getError();
}
```

Also, I prefer to use stamp for this as when you try and select something from the PDF, when using background it can often select the background as well even though you are only trying to select a few lines of text. Haven't experience this when using stamp.

Thanks for the work you put into this Mike!

**Comment by gorelog** [comment]
If you are setting background or stamp and need to fill the PDF, you need to separate these processes as far as I can tell and do them one at a time. My working example is:
```
$data = [
    'foo'=> 'bar',
];
    
$error = [];
$pdf = new Pdf('some-pdf.pdf');
$result = $pdf->fillForm($data)
    ->needAppearances()
    ->flatten()
    ->saveAs('final.pdf');

if ($result === false) {
    $error[] = $pdf->getError();
}

$pdf = new Pdf('final.pdf');
$result = $pdf->stamp('signature-doc.pdf')
    ->saveAs('final-with-sig.pdf');

if ($result === false) {
    $error[] = $pdf->getError();
}
```

Also, I prefer to use stamp for this as when you try and select something from the PDF, when using background it can often select the background as well even though you are only trying to select a few lines of text. Haven't experience this when using stamp.

Thanks for the work you put into this Mike.

**Comment by hkraskian** [comment]
> If you are setting background or stamp and need to fill the PDF, you need to separate these processes as far as I can tell and do them one at a time. My working example is:
> 
> ```
> $data = [
>     'foo'=> 'bar',
> ];
>     
> $error = [];
> $pdf = new Pdf('some-pdf.pdf');
> $result = $pdf->fillForm($data)
>     ->needAppearances()
>     ->flatten()
>     ->saveAs('final.pdf');
> 
> if ($result === false) {
>     $error[] = $pdf->getError();
> }
> 
> $pdf = new Pdf('final.pdf');
> $result = $pdf->stamp('signature-doc.pdf')
>     ->saveAs('final-with-sig.pdf');
> 
> if ($result === false) {
>     $error[] = $pdf->getError();
> }
> ```
> 
> Also, I prefer to use stamp for this as when you try and select something from the PDF, when using background it can often select the background as well even though you are only trying to select a few lines of text. Haven't experience this when using stamp.
> 
> Thanks for the work you put into this Mike.

Thank you.
