### ISSUE TITLE
Failed withour error

### ISSUE THREAD

**Issue by frankmichelin** [mikehaertl/php-pdftk#166]
Hi I am getting the following error I saw another issue thread but I couldn't solve my issue through it.  Here is my code, can you please help troubleshoot?

Failed without error message: pdftk A="C:\inetpub\leadpost\files\TestTemplate.pdf" fill_form "C:\Windows\Temp\phpD88F.tmp.xfdf" output "C:\Windows\Temp\tmpD890.tmp.pdf" drop_xfa need_appearances

use mikehaertl\pdftk\Pdf;

$pdf = new Pdf('...\files\TestTemplate.pdf');
$pdf->fillForm([
        'PatFullName'=>'Test',
        'DiagBox1_M' => 'Yes',
    ])
    ->needAppearances()
    ->saveAs('...\files\TestTemplateFilled.pdf');
echo $pdf->getCommand()->getOutput();

// Check for errors
if (!$pdf->saveAs('...\files\TestTemplateFilled.pdf')) {
    $error = $pdf->getError();
	echo $error;
}

?>

**Comment by mikehaertl** [comment]
I can't see, that you set the path to `pdftk.exe` anywhere which is probably neccessary on Windows. Please check the README: https://github.com/mikehaertl/php-pdftk#shell-command

Apart from that I can't really provide any help if you want to run this on Windows.

**Comment by frankmichelin** [comment]
Thank you for your response.    I added the path to pdftk.exe... Now I get a "Command failed" error.  I see in the the README: https://github.com/mikehaertl/php-pdftk#shell-command "The class uses php-shellcommand to execute pdftk" does that mean I would have to install "https://github.com/mikehaertl/php-shellcommand" also to make it work?

**Comment by mikehaertl** [comment]
No, that's automatically installed as dependency by composer. I'm sorry, but then I really can't help. The library was never really meant for Windows systems. If you can, you should really develop under Linux. With docker or VMs its not that hard - and you avoid many weird problems.

I'm closing this for now as I can't see an issue with the library itself.

**Comment by IulianDide** [comment]
Add useExec option
 
```
use mikehaertl\pdftk\Pdf as pdfTk;
 $pdfTk = new PdfTk(
            $paths,
            [
                'useExec' => true,
            ]
        );
```

if you get the "command not recognized" restart windows, even if the installer set up the global variable, and windows shell recognizes it, somehow other programs can't use it yet (logging off and back on does not work, you actually need to restart)

**Comment by frankmichelin** [comment]
When i tried that it with pdfTk it did generated  "Fatal error: Uncaught Error: Class 'PdfTk' not found in .."  but it does work :) when I tried 
$pdf = new Pdf(
            $paths,
            [
                'useExec' => true,
            ]
        );
