### ISSUE TITLE
Merging password protected files

### ISSUE THREAD

**Issue by mrdigitalau** [mikehaertl/php-pdftk#168]
Hey there,

Thanks a lot for such a great script.

I am using PHP-pdftk to merge many pdfs into one on my website, these PDFs are uploaded by people.

I am having an issue that sometimes people are uploading passworded PDFs, and therefore when it tries to merge it fails.

Is there any way to check if a pdf is passworded before trying to merge? So I can exclude that PDF from the merge?

Eg.
`$pdf->isProtected `
?

Any suggestion would be greatly appreciated. Thank you.

**Comment by mikehaertl** [comment]
It's probably somewhere in the meta data but I'm not sure. You can get it with `getData()` and then need to parse it. I'd first play around with `pdftk` on the command line to see if it provides that info somewhere. Let me know if that works. Most commands of `pdftk` should be covered by the library but maybe we missed some.

**Comment by mrdigitalau** [comment]
Thanks Mike. I ended up fixing it with your suggestion.

`$pdf->getData() `

returns false if the PDF is passworded.

So all I did was

```
foreach ($files as $file)
{
     $pdf = new Pdf($file->url);
   
     if( $pdf->getData() )
     {
          $pdf->addFile($file->url)
     }
    
}
```

It bypassed the false one and works now! Thank heaps for your fast reply much appreciated mate.
