### ISSUE TITLE
Dropdown options order

### ISSUE THREAD

**Issue by arichercloutier** [mikehaertl/php-pdftk#169]
Hi, I am currently working on a project using your tool (great tool by the way) and was wondering if it is possible to keep the original ordering of the options from dropdowns in forms instead of the extracted options being in alphabetical order. For example, if I extract a dropdown containing the months of the year, they come out starting with april, august ... instead of january, february ...

Many thanks !

**Comment by mikehaertl** [comment]
We can only pass on what the `data_dump_fields` command of `pdftk` gives us. As I see it we don't change the order (see [here](https://github.com/mikehaertl/php-pdftk/blob/master/src/DataFields.php#L51)). Just to make sure you could verify that by calling `pdftk data_dump_fields foo.pdf` on the command line. If the order there is correct please report back so we can fix it.

**Comment by mikehaertl** [comment]
I'm closing this as this is a `pdftk` behaviour we can't fix here. If you think there is something to improve here then feel free to leave another comment.
