### ISSUE TITLE
Field names with some chars aren't accessible

### ISSUE THREAD

**Issue by mcdope** [mikehaertl/php-pdftk#17]
Hi,

I'm trying to fill out a PDF ordering form with messy field names like 

* `Auftraggeber_Straße_Nr`
    * on console list_fields gives `Auftraggeber_Stra&#223;e_Nr`
* `ich wünsche eine monatliche Rechnung in Papierform zu je 250 € je Rechnung`
    * `ich w&#252;nsche eine monatliche Rechnung in Papierform zu je 250 &#8364; je Rechnung`

Yes, seriously - this is what is being thrown on me :D. I have no influence on the pdf so no way to change that. 

I've tried both variants, the non-entity and also the one given on console, without sucess - the field in the generated file is empty. If I output `$pdf->getError()` all I get is `Failed without error message: pdftk A='__testdata/<removed>/pdf/<removed>.pdf' 'fill_form' output '/tmp/tmp_php_pdftk_5S9wQP.pdf' drop_xfa need_appearances`

If you want I can mail you the PDF, but I wouldn't like to put it public here.

Any ideas how to solve that?

**Comment by mikehaertl** [comment]
One thing you could try is to use an original Acrobat Reader, fill in the form there and save the form data as FDF. Then you can open that file and compare it to the output of this library, when you [save the form data as FDF](https://github.com/mikehaertl/php-pdftk#create-a-fdf-file-from-a-php-array). FDF files are actually text files that you can open with a (good!) text editor.

But in general PDF forms are really a huge pain as soon as you have a slightly more complex scenario (UTF-8, special characters, etc.). And pdftk is by far not perfect to fill forms. So it could be that you're out of luck. As I'm not really an expert on PDF forms either, I can only point to to other resources, like here: http://blog.tremily.us/posts/PDF_forms/.

Hope that helps you a little. If you think there's anything that could be improved in the `FdfFile` class, let me know.

**Comment by mcdope** [comment]
Thanks for the tip. I'll check that tomorrow and update you. Will also look if I can fix it in FdfFile then, in case I succeed you will get a pull request soon :)

**Comment by mikehaertl** [comment]
Thanks again. Just released 0.2.2 with your changes included.
