### ISSUE TITLE
Filling Form Multiline Field

### ISSUE THREAD

**Issue by capptn** [mikehaertl/php-pdftk#173]
Hi,

How can I create a line break in a multiline field?

**Comment by mikehaertl** [comment]
Can't you just add `\n` to the string? If that doesn't work I have no idea either.

**Comment by capptn** [comment]
No I've already tried that

**Comment by mikehaertl** [comment]
Found a project where I have a multiline field with linebreaks and it works just fine (using `\n`). Maybe an issue with some field options in the PDF? Check that you can fill the field with linebreaks manually (i.e. in a PDF reader).

**Comment by mikehaertl** [comment]
Closing this as there was no further feedback. If you still think it's something to fix please provide a full (simple) example that reproduces the issue.

**Comment by tobiasreinhard** [comment]
Hi,
"\n" is not working for me.
I have one big input field (with multi-line support), but it always renders the given input as text (e. g. \n, <br>, <wbr>, ...)

```
if (!$pdf->fillForm([
    'Adresse' => $order->customer_id . '\n'. $order->customer_company . $order->customer_name . $order->customer_street .  $order->customer_city . $order->customer_country,
])
```

**Comment by mikehaertl** [comment]
Please use `"` instead of `'` (and more important: read this https://www.php.net/manual/de/language.types.string.php)

**Comment by tobiasreinhard** [comment]
You are a genius.
Thank you, works perfect now!  :)
