### ISSUE TITLE
How to set pdf title ? 

### ISSUE THREAD

**Issue by pascaldls** [mikehaertl/php-pdftk#180]
How to set the pdf title 

tried using 
$pdf
            ->SetTitle($name)

which pdftk support

**Comment by mikehaertl** [comment]
Not sure what you mean. There is no `pdftk set_title` or similar.

**Comment by sdevore** [comment]
I think if you were clever one could make use of this basic workflow and the existing tool and get it to work, but as far as I can tell there isn't a nice simple built in way in pdftk 

https://sejh.wordpress.com/2014/11/26/changing-pdf-titles-with-pdftk/
