### ISSUE TITLE
Provide a way to test our service without creating new PDF every time we launch tests.

### ISSUE THREAD

**Issue by VincentLanglet** [mikehaertl/php-pdftk#181]
I have a `pdfGenerator` class, using this library and I have unitTests of the class.
Actually, every time I run the tests, new pdf are created and stored.

I would like to stop creating pdf during tests. What would you recommend ?

**Comment by NeftaliYagua** [comment]
Analize
`
use mikehaertl\pdftk\Pdf;
header('Content-Type: application/pdf');
header('Content-Disposition: inline; filename="name.pdf"');
$pdf = new Pdf('some.pdf');
$pdf->execute();
echo file_get_contents( (string) $pdf->getTmpFile() );
`

**Comment by mikehaertl** [comment]
Sorry, but this question is out of the scope of this project and it's not a bug report either. I can not help you with architectural questions regarding your specific project.
