### ISSUE TITLE
Populate PDF Form Image field

### ISSUE THREAD

**Issue by cluber22** [mikehaertl/php-pdftk#187]
Is this possible with this library? It may be a fairly new feature in PDF.

**Comment by mikehaertl** [comment]
I have no idea how image form fields work (I didn't even know that they exist). If you can do the reverse engineering work and figure out how the XFDF data must look for images we can think about an implementation.

Here's an example for standard form fields: https://github.com/mikehaertl/php-pdftk/blob/master/tests/files/XfdfFileTest.xfdf

**Comment by cluber22** [comment]
Okay I will look into this shortly.

Thanks

**Comment by liammcdermott** [comment]
For anyone else looking for an image form field in XFDF: I can't find one. What misled me into thinking one exists is that certain PDF software _pretends_ there is such a thing, but when you export your form to XFDF the image upload field won't be included.

The reason the image upload is not included in the XFDF (tested in PDF Studio and Acrobat Pro) is an image upload is actually a form button with some JavaScript that opens a file picker and sets the button's background with the image chosen using that file picker. It's a fake.

The closest thing I can find to a form image upload field is the stamp annotation. It appears this library does not support annotations at all, is that correct?

**Comment by mikehaertl** [comment]
AFAIK pdftk does not support adding annotations, so: No, there's no such feature in php-pdftk either.

Thanks for the update on images. So I'll close this here.
