### ISSUE TITLE
Create a PDF with a fillable field

### ISSUE THREAD

**Issue by davideprevosto** [mikehaertl/php-pdftk#189]
Hi there, I know this is not a forum but I can't understand if it's possible to create a PDF (reading some information from an array), adding a fillable field that will be filled later.

I need to predispose a PDF file that will be "digitally signed" in a second step.

Thank you

**Comment by mikehaertl** [comment]
pdftk (which this library is about) can not create PDFs, only modify existing ones. I have no recommendation for PDF creation tools. The PDF forms I've used so far had all been created with original Adobe tools which are quite pricey but I think you can even create a PDF form with LibreOffice (don't ask me for details on that).
