### ISSUE TITLE
mikehaertl\pdftk\Pdf::backgroundMulti()

### ISSUE THREAD

**Issue by mrbinr** [mikehaertl/php-pdftk#19]
Hi,

I think there is a mistake in your documentation, i've got this error : 

Call to undefined method mikehaertl\pdftk\Pdf::backgroundMulti() in ...

After having a look at your code it seems to be multiBackground instead of backgroundMulti.

Is it right ?

Best Regards

Pascall

**Comment by mikehaertl** [comment]
Correct, thanks. Fixed.
