### ISSUE TITLE
Can't fill data after addFile operation

### ISSUE THREAD

**Issue by dnp1891** [mikehaertl/php-pdftk#190]
I am having 2 fillable pdf file named _abc.pdf_ and _xyz.pdf_. I am filling in detail in these PDFs with **fillForm** function and after filling details merging these file with **addFile** operation and saving it with name _abcxyz.pdf_ 

Now when I am going to fill details in merged file _abcxyz.pdf_ it is giving me error as shown below

> Warning: input PDF is not an acroform, so its fields were not filled.

and data is not being filled in pdf.

**Comment by mikehaertl** [comment]
Have you tried `dropXfa()`? See the comment here: https://github.com/mikehaertl/php-pdftk/blob/793c08b891dc9f197058135e6d5d7439b985a2f7/src/Pdf.php#L483

**Comment by dnp1891** [comment]
Yes I have tried adding `dropXfa()`

**Comment by dnp1891** [comment]
Here is sample code what I am doing till now...

```
$abc = new Pdf('abc.pdf');
// fillForm has by deafaulr dropXfa set to true
$abc->fillForm(['data goes here']);
$abc->saveAs('abc.pdf');

$xyz = new Pdf('xyz.pdf');
// fillForm has by deafaulr dropXfa set to true
$xyz->fillForm(['data goes here']);
$xyz->saveAs('xyz.pdf');

$pdfList = [
	'abc.pdf',
	'xyz.pdf'
];

$pdf = new Pdf($pdfList[0]);
if (count($pdfList) > 1) {
	for ($i = 1; $i < count($pdfList); $i++) {
		$pdf->dropXfa()->addFile($pdfList[$i]);
	}	
}
$pdf->saveAs('abcxyz.pdf');

$abcXyz = new Pdf('abcxyz.pdf');
$abcXyz->fillForm(['data goes here']);
if (!$abcXyz->saveAs($savePath)) {
    $error = $pdf->getError();
    echo $error;
} else {
	echo "Saved";
}
```

**Comment by dnp1891** [comment]
If I use **abc.pdf** and **xyz.pdf** file without **addFile()** I am able to fill in details and file formats are fine in AcroForm itself. Once I merge it with **addFile()** it's giving me this warning.

**Comment by mikehaertl** [comment]
Oh, I see. I think, you're actually missing an operation. `addFile()` is just adding files you want to operate on. If you want to combine them you'd have to call `cat()` afterwards, see here: https://github.com/mikehaertl/php-pdftk#cat

Then in a second step try `fillForm()' (and `dropXfa()`) on the new file.

**Comment by dnp1891** [comment]
Thanks for Information Michael. I will check this and let you know the result.

**Comment by mikehaertl** [comment]
Ok. I found that I forgot that `dropXfa()` is already called implicetely when filling out a form with `fillForm()` by default (you already figured that out according to your code comment).

I would also suggest you try with `pdftk` on the command line. Your problem is not really related to our library but rather on how pdftk deals with things. You can create an Xfda file with your form data with our library that you can use on the command line.

**Comment by dnp1891** [comment]
Ok I am aware of pdftk command lines; I will try the same what I am doing in code with command line and check the result if it is working or not.

**Comment by dnp1891** [comment]
I have tried with command.

**Comment by mikehaertl** [comment]
Ok, so it seems to be a limitation of `pdftk`. I think you agree that we can't fix this in our library. If you find out more e.g. a workaround, feel free to add another comment. But for now I'll close this issue.

**Comment by mikehaertl** [comment]
One more note: In found an older project where I had a similar requirement. In that case I first created 2 instances of `Pdf` to fill in the form data. Then I feeded them into another `Pdf` instance with `addFile()` and used `cat()` to select the pages I want in the final PDF. This worked for me. So it seems that order matters.

**Comment by dnp1891** [comment]
Yes; I guess there may be limitations and If I found anything helpful with this I will share the details.

I am also first filling form with two different object and adding them as you mentioned; but after **addFile** and **cat** it stop filling up form.
