### ISSUE TITLE
QUESTION: Is it possible to read buttons values 

### ISSUE THREAD

**Issue by Nardusgc** [mikehaertl/php-pdftk#192]
Hi,

![Selection_013](https://user-images.githubusercontent.com/3862600/81291288-cb992a80-9069-11ea-9b9c-9ac50e02e1a7.png)

I have a pdf with a couple check boxes. The package reads the field details as follows 

![Selection_012](https://user-images.githubusercontent.com/3862600/81291127-8b39ac80-9069-11ea-9ca9-e90dea084d24.png)

Problem is , I don't see anything that indicates if the checkbox was checked or not? 
I'm I missing something obvious?

**Comment by mikehaertl** [comment]
Should be 'FieldValue' but I'm 100% sure. Just try it out. But please understand that this is not the place to ask questions but only to report bugs, sorry.
