### ISSUE TITLE
Create a pdf from an url.

### ISSUE THREAD

**Issue by VincentLanglet** [mikehaertl/php-pdftk#193]
Hi @mikehaertl ! Thanks for this very useful library.

Usually I use this library to generate pdf from path
```
new Pdf('/tmp/fileName.pdf'); 
```

I needed to download a pdf and fill the pdf thanks to your library. Before I did
```
$url = $this->getPdfUrl();
$temporaryPath = $this->savePdfOnServer($url);
new Pdf($temporaryPath);
```

But I recently try directly with the url
```
$url = $this->getPdfUrl();
new Pdf($url);
```
This solution is far better for me since I don't have to create a file.

And it seems to work for me.

Can you confirm that this should correctly work ?
Don't you think adding an example in the README could be great ? :)

**Comment by mikehaertl** [comment]
Hmm, there's no download logic included in our library. So I assume it's `pdftk` itself which also accepts URLs. You could check if your URL appears in the actual command string used to execute `pdftk` like this:

```php
$pdf = new Pdf($url);
// perform some  $pdf command here, e.g. $pdf->cat(1)

echo (string) $pdf->getCommand();
```

**Comment by VincentLanglet** [comment]
I get 
```
pdftk 'A'='http://10.0.0.8/asv/document/public/voucher/Bon_GP_350E_05_062020.pdf' 'fill_form' '/tmp/php_pdftk_xfdf_m02qyB.xfdf' 'output' '/tmp/tmp_php_pdftk_E528VJ.pdf' 'drop_xfa' 'flatten'
```

If I understand correctly, I should check directly with the pdftk library because in the way your library is made, if it works with pdftk it works with your library. Isn't it ?

**Comment by mikehaertl** [comment]
Correct. But from what you say this already seems to confirm that `pdftk` also works if you use a URL instead of a filename. You can also check that on your command line.

I'll close this for now as there's nothing to fix and I'm not sure if I want to include that into the README as it's not really a documented feature of pdftk, so we can't be sure that it works with all versions.
