### ISSUE TITLE
Problem with getError()

### ISSUE THREAD

**Issue by maxguru** [mikehaertl/php-pdftk#194]
I have noticed a strange issue. I am not exactly sure how it comes about but here is what happens:

```
$pdf = new \mikehaertl\pdftk\Pdf($filepath, ['command'=>"[path-to-exe-here]"]);
$data = $pdf->getDataFields();
if( $data === false )
{
	$error = $pdf->getError();
	if(!$error)
	{
		// this happens! string(0) "" in $error
		$command = $pdf->getCommand();
		$commandExitCode = $command->getExitCode(); // 126
		$commandError = $command->getError(); // sh: [path-to-exe-here]: Permission denied
	}
}
```

The problem here is that $pdf->getError() returns empty string but there is actually an error that needs to be reported (as can be seen from $command).

**Comment by mikehaertl** [comment]
Should be fixed now in latest release 0.8.1. Can you confirm that it works for you now?

**Comment by maxguru** [comment]
Thanks! I'll try it out.

**Comment by mikehaertl** [comment]
Closing this as it should be fixed. Feel free to comment if the issue persists.
