### ISSUE TITLE
Problem with java.lang.IllegalArgumentException: the.name.1.is.too.long.2.characters

### ISSUE THREAD

**Issue by kapiziak** [mikehaertl/php-pdftk#196]
Hi!

I am using this repo in my API which is fetching data from WordPress form.

I am filling PDF using this form's data (inputs, checkboxes etc.) I have done all inputs and it was time to checkboxes. 

Unfortunately:
`Unhandled Java Exception in create_output():
java.lang.IllegalArgumentException: the.name.1.is.too.long.2.characters: 162
   at pdftk.com.lowagie.text.pdf.PdfName.<init>(pdftk)
   at pdftk.com.lowagie.text.pdf.AcroFields.setField(pdftk)
   at pdftk.com.lowagie.text.pdf.AcroFields.setFields(pdftk)`

Long checkbox name from pdf for ex.:

**FieldName: Section 3 - Residence - A2 - If 'Yes' have you lived in the UK and islands for five years before the first day of the first academic year of your course? - Yes
FieldStateOption: Off
FieldStateOption: Section 3 - Residence - A4 - Will your swiss national parent be living in the UK on the first day of the academic year? - Yes
FieldStateOption: Section 3 - Residence - A4 - Will your swiss national parent be living in the UK on the first day of the academic year? - no**

When I am filling this field (checkbox) through fillForm and value is "Off" everything is okay.
But when i insert value "Section 3 - Residence - A4 - Will your swiss national parent be living in the UK on the first day of the academic year? - Yes " error shows.

What should I do? Is there any another methods to fill specific FIeldStateOption without this long name?

**Comment by mikehaertl** [comment]
Actually the field name (or is it the value?) looks pretty weird so if you have any option to change it I would try that. The names/values are not visible anywhere and thus should have technical short names just like variables.

The error comes from pdftk itself (or rather: the lowagie Java library that pdftk uses). We can't do much about it and I don't know any workaround.
