### ISSUE TITLE
There is no option to unpack the pdf file

### ISSUE THREAD

**Issue by albertrajmca** [mikehaertl/php-pdftk#197]
I really like this package as it covers all the major pdf tasks. However, the package has not covered the "unpack_files" command. 

pdftk comment.pdf unpack_files output "some_path"

Thanks

**Comment by mikehaertl** [comment]
Right, I've only implemented the most common commands (i.e. the ones I needed). TBH I've never seen a PDF with file attachments and wouldn't even know how to create one.

The implementation should not be difficult I just can't test it. Could you help me test it? If so I could try a quick implementation.

**Comment by albertrajmca** [comment]
Hi Mikehaertl, 
Thanks for your reply. Really appreciate it.
Let me know once the implementation is done, so I can test it on my machine.

**Comment by mikehaertl** [comment]
@albertrajmca See the MR. For testing you have to fetch the changes manually (or use my branch `issue-197-unpack-files`).  Please let me know if this works for you.

**Comment by albertrajmca** [comment]
It works like a charm.

Thanks a lot

**Comment by mikehaertl** [comment]
Great. I've released 0.9.0 containing this new feature. Thanks for your help.
