### ISSUE TITLE
Error:   Target class [db] does not exist. After installing this library

### ISSUE THREAD

**Issue by miryamfv** [mikehaertl/php-pdftk#199]
My app crashed after installing this library last week and today. I had used it in the past (around 2 months ago) and it was working This is the error I get

`Using version ^0.9.0 for mikehaertl/php-pdftk
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing mikehaertl/php-tmpfile (1.1.4): Loading from cache
  - Installing mikehaertl/php-shellcommand (1.6.1): Loading from cache
  - Installing mikehaertl/php-pdftk (0.9.0): Downloading (100%)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In Container.php line 807:

  Target class [db] does not exist.

In Container.php line 805:

  Class db does not exist

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.`

Any advice or help appreciated

**Comment by mikehaertl** [comment]
This is a composer issue not a bug in our library. I can not help you with that.
