### ISSUE TITLE
Issue with PDF Form unable to sign when filled out with pdftk - workaround

### ISSUE THREAD

**Issue by fr3nch13** [mikehaertl/php-pdftk#20]
So, I'm using this project in an application i'm building.
The application has a pdf form used as a template with empty fields, and a way to digitally sign the form.
When I take the form, and fill it out using php-pdftk/pdftk the resulting new pdf no longer has use of extended features. In Adobe Reader this is the message I get:

`"This document enabled extended features in Adobe Reader. The document has been changed since it was created and use of extended features is no longer available. Please contact the author for the original version of this document."`

This is the code I'm using to generate the end pdf with the form template:
```
$pdf_form_template = '/path/to/pdf_template.pdf';
$pdf_form_filled = '/path/to/pdf_form_filled.pdf';

$pdf = new Pdf($pdf_form_template);
$pdf
	->needAppearances()
	->allow('AllFeatures')
	->fillForm($formData)
	->saveAs($pdf_form_filled);
```
The workaround for this it that I had to combine the resulting filled out pdf form with the pdf form template, then `cat` it and basically remove the pdf form template. This basically allowed me to have the extended features allowed again, so users can sign the filled out pdf form.
Example code:
```
$pdf_form_template = '/path/to/pdf_template.pdf';
$pdf_form_filled = '/path/to/pdf_form_filled.pdf';
$pdf_form_combined =  '/path/to/pdf_form_combined.pdf';

$pdf = new Pdf($pdf_form_template);
$pdf
	->needAppearances()
	->allow('AllFeatures')
	->fillForm($formData)
	->saveAs($pdf_form_filled);

$pdf = new Pdf(array(
	'A' => $pdf_form_filled,
	'B' => $pdf_form_template
));
$pdf->saveAs($pdf_form_combined);

$pdf = new Pdf($pdf_form_combined);
$pdf->cat(1)
	->saveAs($pdf_form_filled);
```

**Comment by mikehaertl** [comment]
Hmm, ok, but I'm not sure, we can do anything about it here. It's a limitation of pdftk. Or do you see any way to improve this library?

**Comment by fr3nch13** [comment]
Maybe add the extra steps with 'cat' automatically? 
Maybe not, but apparently this is an issue (from googling) that is known, but there's no solution out there. (Search the dialogue)
This is more of a workaround than a solution, and I hope it shows up in search engines to help others in my situation.

**Comment by mikehaertl** [comment]
I don't think we can have a proper workaround here. The library is designed that you can do only one pdftk operation per instance. You can streamline this a little if you have a look here: https://github.com/mikehaertl/php-pdftk#how-to-perform-more-than-one-operation-on-a-pdf

Apart from that I think it's really a problem of `pdftk` itself - it's far from perfect.

**Comment by fr3nch13** [comment]
It is, but imo, it's worth mentioning the workaround to allow signing without paying a hearty price to Adobe.

**Comment by fr3nch13** [comment]
Even if just for future googling.

**Comment by mikehaertl** [comment]
Well, we have this here. And there are many more edge cases, not just signing. So we can't cover them all. Anyway I'll close this for now as we can't fix it.

**Comment by fr3nch13** [comment]
All good. I just hope this helps someone else, as I happened to come across this by accident, after a few hours of trying.
