### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by Francis-Njoku** [mikehaertl/php-pdftk#200]
Hi Mike,

I tried to set password to a pdf, but no output, 

What is the code snippet to download pdf

Here's code snippet

`$pdf = new Pdf('/asset/news_book/doc/document.pdf');

        $pdf->allow('AllFeatures')      // Change permissions
            ->flatten()                 // Merge form data into document (doesn't work well with UTF-8!)
            ->compress($device)          // Compress/Uncompress
            ->keepId('first')           // Keep first/last Id of combined files
            ->dropXfa()                 // Drop newer XFA form from PDF
            ->dropXmp()                 // Drop newer XMP data from PDF
            ->needAppearances()         // Make clients create appearance for form fields
            ->setPassword('password')          // Set owner password
            ->setUserPassword('password')      // Set user password
            ->passwordEncryption(128)   // Set password encryption strength
            ->saveAs('new.pdf');

           `

Also what kind of data does $device represent

**Comment by mikehaertl** [comment]
You copied the list of possible options from the README. That makes no sense. I'm not sure what you try to do, but maybe this works:

```
$pdf = new Pdf('/asset/news_book/doc/document.pdf');
// Should set password and then send the file to the browser for download
$pdf->setPassword('secret')->send();
```

Apart from that I can not provide more help. You should just try out things and read the man page of pdftk.

**Comment by Francis-Njoku** [comment]
I just want to download pdf after setting password
