### ISSUE TITLE
Does not send file to browser

### ISSUE THREAD

**Issue by Francis-Njoku** [mikehaertl/php-pdftk#201]
Hi

I just tried this

`$pdf = new Pdf('/asset/news_book/doc/document.pdf');
// Should set password and then send the file to the browser for download
$pdf->setPassword('secret')->send();`

But it didn't send file to browser, am I missing anything?

**Comment by mikehaertl** [comment]
Sorry, but please understand that I can not provide personal help for any problem people try to solve with my library. I've not set a password either, so I just don't know. If my suggestion doesn't work, play around and try to figure it out. I can not do that for you. Also study the source code to figure out how things work. If all you want to do is to add a password to a single file you should use `pdftk` on the command line anyway, not this library.
