### ISSUE TITLE
Unknown error when trying to create new PDF

### ISSUE THREAD

**Issue by wanwin** [mikehaertl/php-pdftk#202]
Hi,

```
$pdf = new Pdf([
            'A' => $path,     
            'B' => $path2
       ]);
       $pdf->shuffle(1, 'end', 'A')    
            ->shuffle(1, 'end', 'B')
            ->send('informe.pdf');
```

I'm trying to create a new PDF file using the previous code but I always get the following error:

`Failed without error message: pdftk "A"="C:\Windows\Temp\F911.pdf" "B"="C:\Windows\Temp\F912.pdf" shuffle A1-1 B1-1 "output" "C:\Windows\Temp\tmpF913.tmp.pdf" (Exit code: 1)`

The curious thing about such error is that, if I copy and paste the returned command in Windows command prompt, the combined PDF is created without any kind of problem.

Could you tell me please if I can debug the error to find what's causing it or maybe you know what's happening?

Thank you in advance.

**Comment by mikehaertl** [comment]
Well ... Windows :roll_eyes: 
You probably need to set the path to `pdftk.exe` (or whatever it's called on that OS). See the notes here: https://github.com/mikehaertl/php-pdftk#shell-command

**Comment by wanwin** [comment]
Thank you so much, it worked like a charm!
