### ISSUE TITLE
pdftk-java support?

### ISSUE THREAD

**Issue by williamfalconeruk** [mikehaertl/php-pdftk#208]
Hi, 

we're looking at upgrading a PHP docker image to a later one and slim it down, but found that alpine >3.8 does not support pdftk, and debian (which we use) doesn't support it in buster. See: 

- https://gitlab.alpinelinux.org/alpine/aports/-/issues/10136 
- https://packages.debian.org/buster/pdftk

However there is a java port here: 

- https://gitlab.com/pdftk-java/pdftk

Are there any plans to make php-pdftk support for the java version or is there an alternative we could use?

Any help you can give is appreciated.

**Comment by mikehaertl** [comment]
If you use their precompiled binary it may just work out of the box - maybe even the Debian package they have. Have you tried it?

**Comment by williamfalconeruk** [comment]
i didn't know about that - i'll take a look!
William Falconer

**Comment by mikehaertl** [comment]
You may have to configure the path to `pdftk` if it's not found:

```php
$pdf = new Pdf('/path/my.pdf', [
    'command' => '/some/other/path/to/pdftk',
]);
```

**Comment by mikehaertl** [comment]
Closing this as there was no further feedback.
