### ISSUE TITLE
"Failed- no file" (on Debian/ GCP server)

### ISSUE THREAD

**Issue by fnimam** [mikehaertl/php-pdftk#211]
Hi Mike-
Thanks for all the great work you have been doing. I am trying to make a web application on a GCP server running on Debian. I am beginning level user of Php/ Mysql etc. The application draws data from Mysql database and fill fields of editable PDF and save completed pdf in a separate folder. It runs fine on my windows PC (with xampp) but when i run it on the server- "failed- no file" message pops up with no pdf file being generated. However the void pdf file comes with the correct file name though.

Here is the code being used- can you please look into it. Thanks again.

Regards,
Ali

<?php
namespace classes;

if(!defined('ACCESSCHECK')) {
      die('Direct access not permitted');
}

use mikehaertl\pdftk\Pdf;

class GeneratePDF_nsc {

           public function generate($data)
           {
                  try {
                        $filename = 'nsc_' .  rand(0001,1000) . '.pdf';   
                        //$pdf = new Pdf('./nsc.pdf');
                        $security= "nsc";
                        $pdf = new Pdf('forms/'.$security.'.pdf');                 
                        $pdf->fillForm($data)
                        ->needAppearances()     
                        ->saveAs( './completed/' . $filename);
                      
                        return $filename;
                  }
                  catch (Exception $e)
                  {
                        return $e->getMessage();
                  }

**Comment by mikehaertl** [comment]
Sorry, but please understand that I can't provide any tutorship and I also can not help debugging your app. Try asking questions on stackoverflow or other support forums.

**Comment by fnimam** [comment]
Hi Mike,
I understand- thanks for your time. I am bery grateful to your team for the product and services are offering to many small operators like us- many thanks.

Ali

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
