### ISSUE TITLE
How to write back MetaData?

### ISSUE THREAD

**Issue by MartinH0** [mikehaertl/php-pdftk#212]
I exported my MetaData to `pdfMetaData.txt` got them with `getData()`

$pdf = new Pdf('/path/my.pdf');
$data = $pdf->getData();

then it wrote it to a TXT file. Looks something like this:

```
InfoBegin
InfoKey: CreationDate
InfoValue: D:20201017112623+02'00'
InfoBegin
InfoKey: Author
InfoValue: Your Name
InfoBegin
InfoKey: Creator
InfoValue: Your Creator
InfoBegin
InfoKey: Producer
InfoValue: Creator version XY
PdfID0: 048e9c7588251c9f805088e0a775fd64
PdfID1: 048e9c7588251c9f805088e0a775fd64
NumberOfPages: 1
PageMediaBegin
PageMediaNumber: 1
PageMediaRotation: 0
PageMediaRect: 0 0 595 842
PageMediaDimensions: 595 842
```
I then modified the Values to fit my needs, but still beeing conform to the syntax.

But how can i now write them back to a existing PDF file?

I could not make it work with `updateInfo()` but also no error.
Sadly there is no example on how to write the exported data back, or how to modify these MetaData in PDFs directly.

Please do not close after the reply, because this way I will not get any notifications.

But as the function `updateInfo()` does exist I wonder how to use it?

**Comment by mikehaertl** [comment]
Something like this should work:

```
$pdf
    ->updateInfo(['Creator' => 'foo bar'])
    ->saveAs($file);
```

There are tests for this and they seem to confim that it works. I've never used it myself, though - but others have with success.

See

 * https://github.com/mikehaertl/php-pdftk/blob/master/tests/PdfTest.php#L331
 * https://github.com/mikehaertl/php-pdftk/blob/master/tests/InfoFieldsTest.php

**Comment by MartinH0** [comment]
Thanks man!!

Little hint:
It seems not to work if you execute multiple times the updateInfo() function..

So if you wanna update multiple infos at all you:

CAN NOT USE:
```
$pdf->updateInfo(['Creator' => 'foo bar']);
$pdf->updateInfo(['Author' => cool guy']);
```

SHOULD USE:
```
$pdf->updateInfo(['Creator' => 'foo bar', 'Author' => cool guy']);
```

Ofc it makes sense, but I dont understand why the first way is not working, but its not a problem.

Thank you!

**Comment by mikehaertl** [comment]
That's an architectural limitiation of this library. Things would get too complex if we allowed to combine several calls to different (or even only the same) method. But there's a note about this in the README:

> IMPORTANT: You can always only perform one of the following operations on a single PDF instance. Below you can find a workaround if you need multiple operations.
