### ISSUE TITLE
Pass PDF between PDFTK & FPDF without saving to disk

### ISSUE THREAD

**Issue by MartinH0** [mikehaertl/php-pdftk#213]
Atm I'm filling Forms with PDFTK and adding an Image with FPDF.
Now I know here I can just get support for PDFTK, but can PDFTK read a PDF directly from FPDF?

Something like:

```
$FPDF = new FPDI();
$FPDF->AddPage();
$FPDF->setSourceFile('../test.pdf');
$tplIdx = $FPDF->importPage(1);
$FPDF->useTemplate($tplIdx);

$pdf = new PDF($FPDF);
```

For not having to store the PDF as a File to the Disk, as this could be slowing down thing. And damaging the HDD on long term.

**Comment by mikehaertl** [comment]
Sorry, this doesn't work. FPDI is not related to this library and we have no plans of supporting this kind of thing.

Actually in the background there's often a temporary file generated anyways because that's how pdftk works (it expects files as input for some options).
