### ISSUE TITLE
How to embed font with PDFTK?

### ISSUE THREAD

**Issue by MartinH0** [mikehaertl/php-pdftk#214]
I now managed to create a usable PDF which does have fillable forms. But as long as it does have forms I can not (with Adobe Acrobat DC Pro) embed the fonts. After they are filled and flattened it works. But actually I dont wanna do this manually.

So I have created the PDF with OpenOffice/LibreOffice and fonts seems to not be embeded as it does have fillable forms.
I just have used the open "Robots" font. Once in bold, once in regular.

Is there a way to embed fonts, or even to clear all other fonts and set ALL fonts to one font? As on mobile and in the browser fonts look different then in Acrobat DC Pro.

After embedding fonts with Acroat (manually) size just gworths by 10-15kb

**Comment by MartinH0** [comment]
Everything works, but not the bold font. It will just be displayed bold when Robots-Bold.ttf is available on the system. But in the browser anyway it will never get dosplayed right.

I used it like this:


```
$pdf = new Pdf('../templates/PDF.pdf');
$pdf->fillForm($data);
$pdf->needAppearances();
$pdf->flatten();
$pdf->saveAs('../archiv/tmp/PDF.pdf');
```

But in the end its missing embedding the fonts. Robots fonts are free to use even commercial.
See --> https://github.com/googlefonts/roboto/blob/master/LICENSE
So there should not be a license-problem of not embedding it.

**Comment by mikehaertl** [comment]
pdftk can't do this for you. You need to embed the font when you create the PDF. Note that LibreOffice et. al. only have limited PDF creation capabilities. To have full control you probably need some Adobe software like Creator (or whatever their PDF tool is called nowadays). There you can define which font is used for form fields.
