### ISSUE TITLE
saveAs() no working .. 

### ISSUE THREAD

**Issue by zigomario** [mikehaertl/php-pdftk#215]
Hello,

my code is simple

`       

```
   $fields = array(
            'check_22' => true,
            'field-test' => 'ok',
        );

 $pdf = new Pdf('modules/test/test_p82.pdf');
        $pdf->tempDir = '/home/admin/web/test/public_html/';
        $pdf->fillForm($fields)
            ->needAppearances()
            ->saveAs('home/admin/web/test/public_html/filled2.pdf');
```
`

i set tempDir cause erreur with open_basedir.

After saveAs, i have no error, but i don't find the file.

I have test some var_dump and i find that i enter in first condition of 👍 

`
    public function saveAs($name)
    {

        if (!$this->getCommand()->getExecuted() && !$this->execute()) {
            // i pass here //
            return false;
        }
        $tmpFile = (string) $this->getTmpFile();

        if (!copy($tmpFile, $name)) {
            $this->_error = "Could not copy PDF from tmp location '$tmpFile' to '$name'";
            return false;
        }
        return true;
    }

`

But i don't understand why .. i suspect missed temporyFile cause my tempDir set .. or not.

Please help.

Thank you

**Comment by mikehaertl** [comment]
You should check the result of `saveAs()` and if it's `false` you should check if there is an error in `getError()`

I also see you missed a `/` at the beginning of your `saveAs()` path.

**Comment by zigomario** [comment]
Thank you very much for this fast response.
I see by th getError that i have miss first step required .. i have no install the package pdftk on my server. :(
sorry
