### ISSUE TITLE
dataField() method is returning empty

### ISSUE THREAD

**Issue by Messhias** [mikehaertl/php-pdftk#216]
Hi when I tried to read the PDF as using my CV as example the command `$pdf->getData()` returns empty.

The file is on attachment to reproduce.

Here the following code:

```
$pdf = new \mikehaertl\pdftk\Pdf(base_path("fb.pdf"));
return $pdf->getDataFields();
```

Thank you

[fb.pdf](https://github.com/mikehaertl/php-pdftk/files/5492234/fb.pdf)

**Comment by mikehaertl** [comment]
Something is probably wrong with your pdf. You should also pass the full path to your file to the `Pdf` instance, not just the base path. Also check if `pdftk fb.pdf dump_data_fields` works on the command line.

**Comment by Messhias** [comment]
> pdftk fb.pdf dump_data_fields

Hi @mikehaertl, unfortunately the command ```pdftk fb.pdf dump_data_fields``` didn't worked out.

Screenshot:

![Screenshot 2020-11-05 at 07 20 43](https://user-images.githubusercontent.com/1161283/98209856-8cc03080-1f37-11eb-8745-72e28767e862.png)


Thank you.

**Comment by Messhias** [comment]
By the way, I created this PDF file using **open office**, does that make any difference?

**Comment by mikehaertl** [comment]
Sorry but please understand that I can't provide help for creating PDFs. And the command line result shows, that it's not related to our library. OpenOffice could work but I'd not be sure. I don't have a recommendation (apart from the original Adobe tools).
