### ISSUE TITLE
Missing fields in getDataFields()?

### ISSUE THREAD

**Issue by bvdham** [mikehaertl/php-pdftk#217]
I've created a simple pdf form, see attachment, [test-form.pdf](https://github.com/mikehaertl/php-pdftk/files/5540724/test-form.pdf) with the following fieldtypes:

- text
- checkbox
- dropdown
- listbox
- radiobutton

when calling the function getDataFields i'm missing some types? Is this correct?
**example code**
```
    public function fields()
    {
        $projectDir = $this->getParameter('kernel.project_dir');
        $uploadDir = sprintf('%s/var/uploads/documents', $projectDir);

        // Fill form with data array
        $pdf = new Pdf(sprintf('%s/test-form.pdf', $uploadDir));
        $error = $pdf->getError();
        //        $data = $pdf->getData();
        $fields = $pdf->getDataFields();
        $fieldsToArray = (array)$fields->__toArray();

        if($fields === false) {
            dump($error);
        }

        dd($fieldsToArray);
    }

```

result in fields is only text, button or choice? What about dropdown or listbox and radio?

![image](https://user-images.githubusercontent.com/7288381/99147501-cb659180-2681-11eb-8e1b-7331f8ec66d5.png)

**Comment by mikehaertl** [comment]
Can you paste the output of `pdftk your.pdf dump_data_fields_utf8` ?

**Comment by bvdham** [comment]
You mean 

```
$pdf = new Pdf(sprintf('%s/test-form.pdf', $uploadDir));      
$fields = $pdf->getDataFields();

dd($fields);
```

```
DocumentController.php on line 42:
mikehaertl\pdftk\DataFields {#512 ▼
  -_string: """
    ---
    FieldType: Text
    FieldName: field_firstname
    FieldFlags: 0
    FieldJustification: Left
    ---
    FieldType: Text
    FieldName: field_lastname
    FieldFlags: 0
    FieldJustification: Left
    ---
    FieldType: Text
    FieldName: field_middlename
    FieldFlags: 0
    FieldJustification: Left
    ---
    FieldType: Button
    FieldName: field_option_high
    FieldFlags: 0
    FieldJustification: Left
    FieldStateOption: Ja
    FieldStateOption: Off
    ---
    FieldType: Button
    FieldName: field_option_average
    FieldFlags: 0
    FieldJustification: Left
    FieldStateOption: Ja
    FieldStateOption: Off
    ---
    FieldType: Button
    FieldName: field_option_low
    FieldFlags: 0
    FieldJustification: Left
    FieldStateOption: Ja
    FieldStateOption: Off
    ---
    FieldType: Button
    FieldName: group_gender
    FieldFlags: 49152
    FieldValue: field_male
    FieldJustification: Left
    FieldStateOption: Off
    FieldStateOption: field_female
    FieldStateOption: field_male
    ---
    FieldType: Choice
    FieldName: list_companies
    FieldFlags: 524288
    FieldValue: Bewindvoering
    FieldValueDefault: Bewindvoering
    FieldJustification: Left
    FieldStateOption: Bewindvoering
    FieldStateOption: Budgetbeheer
    FieldStateOption: PGB Beheer
    FieldStateOption: Pré-bewind
    ---
    FieldType: Choice
    FieldName: dropdown_type
    FieldFlags: 131072
    FieldValue: -- Kies een waarde --
    FieldValueDefault: -- Kies een waarde --
    FieldJustification: Left
    FieldStateOption: -- Kies een waarde --
    FieldStateOption: Kernwaarden
    FieldStateOption: Kwaliteitswaarborging
    FieldStateOption: Werkwijze
    ---
    FieldType: Text
    FieldName: date_appointment
    FieldFlags: 0
    FieldJustification: Left
    """
  -_array: array:10 [▶]
  storage: array:10 [▼
    0 => array:4 [▼
      "FieldType" => "Text"
      "FieldName" => "field_firstname"
      "FieldFlags" => "0"
      "FieldJustification" => "Left"
    ]
    1 => array:4 [▼
      "FieldType" => "Text"
      "FieldName" => "field_lastname"
      "FieldFlags" => "0"
      "FieldJustification" => "Left"
    ]
    2 => array:4 [▶]
    3 => array:5 [▶]
    4 => array:5 [▶]
    5 => array:5 [▶]
    6 => array:6 [▶]
    7 => array:7 [▶]
    8 => array:7 [▶]
    9 => array:4 [▶]
  ]
  flag::STD_PROP_LIST: false
  flag::ARRAY_AS_PROPS: false
  iteratorClass: "ArrayIterator"
}
```

**Comment by mikehaertl** [comment]
I meant the actual output on the command line, when you call `pdftk` manually. We parse that string in `DataFields` so if you're missing fields maybe the parser needs a fix. Maybe you can do some debugging yourself. There's also a test case in `tests/DataFieldsTest.php` that you can modify and try to reproduce your issue.

**Comment by mikehaertl** [comment]
Ok, I see the output from your dump. Actually it works as expected. You'll find the values in the `FieldStateOption` key. For an example see the test I've added here: https://github.com/mikehaertl/php-pdftk/pull/218/files

**Comment by bvdham** [comment]
Now i see 👍  I was thinking wrong, was expected that each checkbox or radio should be one group. But each field is displayed separately. Because web forms work that way.

Last question why is the radio button (group_gender) is merged and the checkbox fields (field_option_high, field_option_average and field_option_middle) not. 

Because how could i map a web form with checkboxes to the pdf form button checkbox type?

**Comment by mikehaertl** [comment]
> Last question why is the radio button (group_gender) is merged and the checkbox fields (field_option_high, field_option_average and field_option_middle) not.

Not sure, what you mean. All those are distinct fields. You see it from the text output. As stated above our library can only parse this text output bring it into a PHP array form. It's a very simple mapping. I can't help much with how to work with that data. It depends a lot on how the PDF form was created (and I'm not really an expert on PDF form internals).

I'm closing this for now. If you think there's something to improve please provide an example output of `pdftk your.pdf dump_data_fields_utf8` and what you think should be the expected result in PHP.

**Comment by janki-ranium** [comment]
Hi I am not getting some data fields while printing out a form. they are texts fields. could you please help?
