### ISSUE TITLE
Combine multiple pdfs into single pdf using mikehaertl library

### ISSUE THREAD

**Issue by mohitbirpankar** [mikehaertl/php-pdftk#219]
use mikehaertl\pdftk\Pdf;
 
$path = resource_path('forms/template.pdf');  //pdf template
$pdf = new Pdf($path);

$form_eec_fields[EmpMapping::FORM_EEC_MAPPING['medical']] = $medical;  //get data into array to fill pdf

$pdf->fillForm($form_eec_fields)
                ->needAppearances()
				->flatten()
                ->send("form_pad-"empname".pdf",1);
				
"We would like to use multiple pdf templates/pdf objects and combine those into a single pdf file."{

**Comment by mikehaertl** [comment]
Did you check for an error message? See README.
