### ISSUE TITLE
Shared hosting

### ISSUE THREAD

**Issue by redgroupny** [mikehaertl/php-pdftk#22]
I apologize if my question is inappropriate. 
Does this php tool help resolve the issues installing PDFtk on a shared hosting server (ie without root access to run commands likes sudo) 

I am trying to run a php app that uses PDFtk on GoDaddy CPanel shared hosting.

**Comment by mikehaertl** [comment]
This tool is just a frontend for the command line tool. So if you don't have `pdftk` installed and have no root access it will not help you.

**Comment by zaplachinsky** [comment]
It works for me on the shared hosting by using already built binary of `pdftk` for Linux:

```php
$pdf = new Pdf($pathToPdfFile, array(
    // e.g. /project/pdftk/bin/pdftk
    'command' => '/path/to/pdftk/binary/file',
    'procEnv' => array(
        // e.g. /project/pdftk/bin (should contain libgcj.so.10)
        'LD_LIBRARY_PATH' => '/path/to/library/folder'
    )
));
```

In this example is used `pdftk` binary from this repository: https://github.com/lob/lambda-pdftk-example/tree/master/bin

No need to install `pdftk` on the server, just to move this two files to some project directory.

It may require to add permissions for execution of `pdftk` file, it can be set from the terminal by `chmod u+x ./pdftk` command (if there is access for this) or from FTP client.

P. S. I'm also run it in this way on the macOS server, just put the already built `pdftk` binary (for macOS) to the project folder and some required `pdftk` libraries, without any kind of installation or root access.

**Comment by victorybiz** [comment]
> It works for me on the shared hosting by using already built binary of `pdftk` for Linux:
> 
> ```
> $pdf = new Pdf($pathToPdfFile, array(
>     // e.g. /project/pdftk/bin/pdftk
>     'command' => '/path/to/pdftk/binary/file',
>     'procEnv' => array(
>         // e.g. /project/pdftk/bin (should contain libgcj.so.10)
>         'LD_LIBRARY_PATH' => '/path/to/library/folder'
>     )
> ));
> ```
> 
> In this example is used `pdftk` binary from this repository: https://github.com/lob/lambda-pdftk-example/tree/master/bin
> 
> No need to install `pdftk` on the server, just to move this two files to some project directory.
> 
> It may require to add permissions for execution of `pdftk` file, it can be set from the terminal by `chmod u+x ./pdftk` command (if there is access for this) or from FTP client.
> 
> P. S. I'm also run it in this way on the macOS server, just put the already built `pdftk` binary (for macOS) to the project folder and some required `pdftk` libraries, without any kind of installation or root access.

Thank you @zaplachinsky your solution worked for me too.

**Comment by programming890** [comment]
> > It works for me on the shared hosting by using already built binary of `pdftk` for Linux:
> > ```
> > $pdf = new Pdf($pathToPdfFile, array(
> >     // e.g. /project/pdftk/bin/pdftk
> >     'command' => '/path/to/pdftk/binary/file',
> >     'procEnv' => array(
> >         // e.g. /project/pdftk/bin (should contain libgcj.so.10)
> >         'LD_LIBRARY_PATH' => '/path/to/library/folder'
> >     )
> > ));
> > ```
> > 
> > 
> > In this example is used `pdftk` binary from this repository: https://github.com/lob/lambda-pdftk-example/tree/master/bin
> > No need to install `pdftk` on the server, just to move this two files to some project directory.
> > It may require to add permissions for execution of `pdftk` file, it can be set from the terminal by `chmod u+x ./pdftk` command (if there is access for this) or from FTP client.
> > P. S. I'm also run it in this way on the macOS server, just put the already built `pdftk` binary (for macOS) to the project folder and some required `pdftk` libraries, without any kind of installation or root access.
> 
> Thank you @zaplachinsky your solution worked for me too.

Please how could I contact you please tell me even freelancers are not able to solve this problem could you please I am building a website for students help I could share more but please me everything is done but when I upload this to the live server it's not generating the pdf
