### ISSUE TITLE
Any approach to make "Ñ" letter appear in pdf?

### ISSUE THREAD

**Issue by juanadamuzsimj** [mikehaertl/php-pdftk#222]
¿Any approach to make "Ñ" letter appear in pdf?

I've seen some people with UTF-8 character problems but not really a solution...

`
$pdf->fillForm($name)->needAppearances();
        $result = $pdf->flatten()->saveAs($out);
`

**Comment by mikehaertl** [comment]
Please understand, that this not a support forum but for reporting bugs. Your question is also answered in the README:

> Note: When filling in UTF-8 data, you should always add the needAppearances() option. This will make sure, that the PDF reader takes care of using the right fonts for rendering, something that pdftk can't do for you. Also note **that flatten() doesn't really work well** if you have special characters in your data.

**Comment by juanadamuzsimj** [comment]
I solved it setting all fields to Arial font and enabling rich text in adobe.
