### ISSUE TITLE
Merge pdf's

### ISSUE THREAD

**Issue by mohitbirpankar** [mikehaertl/php-pdftk#223]
Hi,
I am using laravel and want to merge pdf's from the storage paths using the cat method. Currently, we have a separate job to generate each pdf using send() method in handle method of pdftk library. Below is the code:

 public function handle($employeeid=null)
    {      
            $employeeRecord = Employee::find($employeeid);
            ------
            ------
            ------
            $forms_dir = storage_path('app/forms');
            $sourcefiles = glob(storage_path('app/forms'.$employeeid.'/*.pdf'));
            $path = resource_path('forms/form1.pdf');
            $pdf = new Pdf($path);
            
            $pdf->fillForm($form_w4_fields)
                ->needAppearances()
		->flatten()
                ->send("form_.$employeeid.".pdf",1);
        }
How, I can use send() and saveAs() method(to store the generated pdf physically) based on different parameters in the handle method? and how to merge the stored pdf's in a single pdf.

**Comment by mikehaertl** [comment]
Sorry, I can not provide individual support for project specific questions. What you want to achieve is explained in the README. You may want to look at https://github.com/mikehaertl/php-pdftk#how-to-perform-more-than-one-operation-on-a-pdf
