### ISSUE TITLE
Opening password protected PDF

### ISSUE THREAD

**Issue by skills-up** [mikehaertl/php-pdftk#225]
Hello,

How can I use this to open a password protected PDF and apply various operations on it? I basically want to create a copy of the PDF with a different user password then the source PDF. The typical command for this is:
`pdftk <input.pdf> input_pw <input_password> output <output.pdf> user_pw <user_password>`

I'm currently using unprotected source PDFs with the following code:
```
$pdf = new mikehaertl\pdftk\Pdf( $source_path );
$result = $pdf->setUserPassword( $password )->execute();
$output = file_get_contents( (string) $pdf->getTmpFile() );
```

I've tried playing around with `command` options as well without any results.

Thanks!

**Comment by mikehaertl** [comment]
Try passing files in array format:
```
$pdf = new Pdf([
    'A' => ['file1.pdf', 'pass**word'],
]);
```

**Comment by skills-up** [comment]
Thanks! This worked perfectly.
