### ISSUE TITLE
Kindly help me, PDFTK working locally but not on windows server

### ISSUE THREAD

**Issue by syed1980eer** [mikehaertl/php-pdftk#230]
Hello  @mikehaertl 

I'm new and don't know much about the etiquettes of raising an issue or asking a question on github so please accept my apology in advance. 
Actually from pas few days I have been struggling to solve this and couldn't make it through, that's why thought of query the same here. I'm trying to use PDFTK which work absolutely fine on my local machine but when I use the same simple app on windows-2012 server, it dint work. When I click on download link, it download with the something with the filename in the browser but 'Failed No file' I've attached that image and my app zip folder to check.

Thank you

[PDF_TK.zip](https://github.com/mikehaertl/php-pdftk/files/5932863/PDF_TK.zip)
![download-file](https://user-images.githubusercontent.com/63671831/107042249-fa038c00-67da-11eb-8fe7-3478bfbc00e1.jpg)

**Comment by mikehaertl** [comment]
Sorry, please understand that I can not provide individual support. This here is rather for reporting bugs in our software.

**Comment by MIA-Winnipeg** [comment]
I have the same problem.
and in my opinion, if it has problem working on live server that's means its serious bug and we need solution please

**Comment by MIA-Winnipeg** [comment]
@syed1980eer  did you find solution?
