### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by tertek** [mikehaertl/php-pdftk#233]
Please update the README requirements that this wrapper is not supported on Windows:

`Failed without error message: pdftk "A"="C:\..\template.pdf" dump_data_fields_utf8 (Exit code: 1)`

Also see https://github.com/mikehaertl/php-pdftk/issues/62

**Comment by mikehaertl** [comment]
Well, it is... check the README here: https://github.com/mikehaertl/php-pdftk#shell-command

You need to configure the path to `pdftk.exe` on your system.

**Comment by tertek** [comment]
Maybe you could emphasize a hint for Windows users on a more general level, since I encountered the error while using `getDataFields` method and not the Shell Command. But thank you for the info !

**Comment by mikehaertl** [comment]
The Shell command is the underlying library used to execute any command. As I can not really provide "official" support for Windows, I don't want to encourage use on Windows - even though it *should* work in most cases.
