### ISSUE TITLE
not working on Windows 10

### ISSUE THREAD

**Issue by ronga** [mikehaertl/php-pdftk#234]
I lifted this straight from the readme doc and it doesn't seem to work, I was getting a blank until I added `echo ('error');` in the error checking at the end, at which point I did get an error message:

```
 require_once('C:\PHP8\vendor\autoload.php'); 
    use mikehaertl\pdftk\Pdf;


// Extract pages 1-2 into a new file
$pdf = new Pdf('C:\PHP8\CSA AND IPS IMA 8807.pdf');
$result = $pdf->cat(1, 2)
        ->saveAs('C:\PHP8\CSA1.pdf');
if ($result === false) {
    echo ('error');
    $error = $pdf->getError();
}
```
Any help is appreciated as I've been on this almost a week already.

**Comment by mikehaertl** [comment]
Same as #233 i.e. set `binary` to the path to `pdftk.exe`?

**Comment by ronga** [comment]
For some reason, pdftk.exe was not installed anywhere through composer. I just downloaded it manually and put it in Program Files (x86) as you suggested. Worked like a charm. Thank you sir, your genius piece of work saved us hundreds of man-hours!

**Comment by mikehaertl** [comment]
It's not expected to be installed via composer. See this note in the README:

> The pdftk command must be installed and working on your system

**Comment by ronga** [comment]
I see, I must have missed that. I did see your other thread where you mentioned installing it via composer.

Again, thank you for all the help.
