### ISSUE TITLE
Is there any way to populate a field with datasheet info?

### ISSUE THREAD

**Issue by frankmichelin** [mikehaertl/php-pdftk#235]
I am trying to create an HTML table in PHP and then populate a field on the PDF with a neatly formatted table.  Is this possible?  Any solution suggestions to but datasheet data onto the PDF?

**Comment by mikehaertl** [comment]
pdftk can only fill in forms that are already there in the PDF. It can not add new form elements or other content.

Please also note, that this is not a support forum but a system to report bugs.
