### ISSUE TITLE
multiBackground not showing the fields on the backround ('/path/back_pages.pdf')

### ISSUE THREAD

**Issue by frankmichelin** [mikehaertl/php-pdftk#236]
Per example... 
Add background PDF
Add another PDF file as background.

$pdf = new Pdf('/path/my.pdf');
$result = $pdf->multiBackground('/path/back_pages.pdf')
    ->saveAs('/path/watermarked.pdf');

The path/back_pages.pdf contains fields with data.. but they show up blank on the new watermarked.pdf.
Is there a way that the background pdf with fields can display on the new watermarked.pdf?

**Comment by mikehaertl** [comment]
I don't think pdftk can do that (use filled forms as background, if I understand that right). Our library is just a frontend for pdftk for PHP. So I'm closing this as we can't fix anything here.

**Comment by frankmichelin** [comment]
Okk (yes you understood correctly)
