### ISSUE TITLE
PDFTK not downloading the pdf

### ISSUE THREAD

**Issue by programming890** [mikehaertl/php-pdftk#237]
This is the classes file -
```
namespace Classes;

use mikehaertl\pdftk\Pdf;

class GeneratePDF {

        public function generate($pdfdata)
        {
            $filename = 'pdf_'.rand(2000, 1200000).'.pdf';
            $pdf = new Pdf('./test.pdf');
            $pdf->fillForm($pdfdata)
            ->flatten()
            ->saveAs($filename . '.pdf');
            return $filename;
        }
        
}
```
This is the file where i take the post data from form but its running ok with no errors showing but when i remove `require_once 'classes/PDFClasses.php';` it shows error but if added it's ok it's the above class added. 

```
<?php

require_once 'classes/PDFClasses.php';

require 'vendor/autoload.php';

use Classes\GeneratePDF;

$name = $_POST['name'];
$lname = $_POST['lname'];
$number = $_POST['no'];


                
$pdfdata = [
                'name_field' => $name,
                'lname_field' => $lname,
                'number_field' => $number

           ];


           $pdf = new GeneratePDF;
           $response = $pdf->generate($pdfdata);

           var_dump($response);


?>
```

However my main problem is that it's generating the file name but not downloading or saving any pdf file I find it difficult to understand how this library is not going as I have followed. Here is the video that i have followed for reference - https://www.youtube.com/watch?v=SJNCc2GwREA&t=1032s

Also the pdf is a fillable form with their names.

**Comment by mikehaertl** [comment]
Please check the return value of `saveAs()` as described in the README. If it's false, check, if there is an error message.

From what I see, there's nothing special happening in regard to our library. So I rather suspect a problem somehwere in your own code or maybe a write permission issue. Please note, that I can not provide help in debugging your custom code. I'm closing this, as there's no problem I could reproduce.
