### ISSUE TITLE
saveAs return false.

### ISSUE THREAD

**Issue by fazalhakim426** [mikehaertl/php-pdftk#238]
I'm trying to generate pdf.but return false.please help me.
thanks in advance.

Detail
1.
$pdf = new Pdf('./test.pdf');
var_dump($pdf);
![image](https://user-images.githubusercontent.com/38204785/114784497-bc9c1b80-9d94-11eb-991e-c7314061c3c0.png)
2.saveAs($fileName) return false
code
![image](https://user-images.githubusercontent.com/38204785/114785262-e1dd5980-9d95-11eb-9b81-480417d75da4.png)
output
![image](https://user-images.githubusercontent.com/38204785/114785298-f1f53900-9d95-11eb-9c1c-c8c38e757ef6.png)

**Comment by mikehaertl** [comment]
Sorry, this is not a support forum but for reporting bugs. Please check the README how to check for errors (`$pdf->getError()`). It also seems that you use windows. You probably have to configure the path to `pdftk.exe` in `command` which is also explained in the README.

**Comment by fazalhakim426** [comment]
ok thanks alot
