### ISSUE TITLE
How to pass variable through new keyword in php?

### ISSUE THREAD

**Issue by programming890** [mikehaertl/php-pdftk#239]
I am getting filename using $_GET the filename from url to dynamically fetch the name of the file and here is the class which i am using as instructed by pdftk

```
<?php 
namespace Classes;

use mikehaertl\pdftk\Pdf;

class GeneratePDF {
    
        public function generate($pdfdata)
        {
            $pdfname = 'pdf_'.rand(2000, 1200000).'.pdf';
            $pdf = new Pdf('./test.pdf');

            $pdf->fillForm($pdfdata)
            ->flatten()
            ->needAppearances()
            ->saveAs($pdfname);          
             return $pdfname;
            
        }              
} 

?>
```
Now I want to pass the $_GET['filename'] to the new Pdf('./test.pdf'); so that it always fetch selected file from url.

I have tried using $pdf = new ('.$filename.'); or $pdf = new ('?><?php echo $filename; ?> <?php '); but still it don't work.

**Comment by mikehaertl** [comment]
Sorry, this is not a support forum but a system for reporting bugs. I don't even understand what exactly you try to achieve here. Your code like `$pdf = new ('?> <?php ');` makes no sense to me.
