### ISSUE TITLE
Specify full path to pdftk binary

### ISSUE THREAD

**Issue by bkosborne** [mikehaertl/php-pdftk#24]
The user my webserver runs as doesn't have `/usr/local/bin` in its `$PATH`, which is where the `pdftk` binary is. I could add it to the path, but I wonder why the full path to the binary is not configurable?

**Comment by mikehaertl** [comment]
It is, ist just not full Dokumenten. Try the `command` Option. For more details also check https://github.com/mikehaertl/php-shellcommand

**Comment by bkosborne** [comment]
Ah, indeed. Thanks
