### ISSUE TITLE
PDFTK background not working in php?

### ISSUE THREAD

**Issue by programming890** [mikehaertl/php-pdftk#240]
`$pdf->background('/rawpdf/background.pdf')`

But when I use this in my code it doesn't work I mean the back.pdf is not a background inside my generated pdf.

```
public function generate($pdfdata)
        {
            $pdfname = 'pdf_'.rand(2000, 1200000).'.pdf';
            $pdf = new Pdf("./rawpdf/test.pdf");
            
            $pdf->fillForm($pdfdata)
            ->flatten()
            ->needAppearances()
            ->saveAs("./generated/".$pdfname);            
            return $pdfname;
            
        }
```
In my thought process I think If i use the background then it should be behind the text or can be said over the generated pdf but those things don't happen. Is there anything else that needs to be added to it.

**Comment by mikehaertl** [comment]
Again: Please understand, that this is not a support forum. If you found a bug, please provide a clear example for it. From your code example I don't even understant what you try to tell me: You don't use `background()` at all. So all I can say is, you should probably study the full README again to learn how to use this library.
