### ISSUE TITLE
Compress not working

### ISSUE THREAD

**Issue by vavicheth** [mikehaertl/php-pdftk#241]
Thank you for the wonderful package.
I have some problems with pdf compression.
Here is my code:
```

$pdf = new Pdf(storage_path('tmp/uploads/file.pdf'));
$pdf->compress('compress')->saveAs(storage_path('tmp/uploads/new.pdf'));
```

It doesn't happen for this code.
Please kindly advise me. Thanks

**Comment by mikehaertl** [comment]
Does it work on the command line? And can you check the created command string?

```
$pdf = new Pdf(...);
$pdf->compress();
echo (string) $pdf->getCommand();
```

According to our [test case](https://github.com/mikehaertl/php-pdftk/blob/master/tests/PdfTest.php#L445) the `compress()` option creates the correct `pdftk` command. If that doesn't work, then it's rather a problem with `pdftk`.

**Comment by vavicheth** [comment]
Yes, It is correct (return `pdftk` command). But It's not compressed, the size still big.

**Comment by mikehaertl** [comment]
Does it work if you execute the command manually on the command line?

**Comment by mikehaertl** [comment]
Maybe your expectation is also somewhat incorrect: According to the `pdftk` man page, `compress` will not shrink the size of your PDF. 

```
[compress | uncompress]
              These are only useful when you want to edit PDF code in a text editor like vim or emacs.  
              Remove PDF page stream compression by applying the uncompress filter.
              Use the compress filter to re‐store compression.
```

**Comment by vavicheth** [comment]
Yes. It's working (less than 1MB). Thank you.
Actually, I use pdf annotation js, It's so bigger size (x4). So I try optimizing it. Do you have any idea?

**Comment by mikehaertl** [comment]
If I understand right, there's nothing to fix here and `compress()` works as it should, right? I'm closing this issue then.

I also have no idea how to compress PDFs.
