### ISSUE TITLE
Function goes into an infinite loop

### ISSUE THREAD

**Issue by itsowaisnoor** [mikehaertl/php-pdftk#242]
Hi,

I just tried this package with Laravel 7 and all configurations are done correctly but once I call the function it is going to an infinite loop. No error is displayed.

Here is my code.
`$pdf = new Pdf('backend/assets/myfile.pdf');
        // i am getting my pdf file here (working)
        // dd($pdf); 
        $result = $pdf->fillForm([
            'name_filed' => 'mytext'
        ])
        ->flatten()
        ->saveAs('backend/assets/filled.pdf'); // on this line with saveAs(), this goes to infinite loop
        if ($result === false) {
            $error = $pdf->getError();
        }`
        
I am using MAC OS and also tried to give all permissions to the folder and files.

**Comment by mikehaertl** [comment]
From the code you give I can not see how an infinite loop could occur. Can you please try outside of Laravel? Just to rule out any problem with the framework.

**Comment by itsowaisnoor** [comment]
Thanks for your quick response.

I already tried this in core PHP and the result is the same. It is going to an infinite loop.
Here is my core PHP Code
`$filename = 'pdf_' . rand(2000,1200000) . '.pdf';`
`$pdf = new Pdf('./test.pdf');`
`$pdf->fillForm($data)`
`->flatten()`
`->saveAs( './completed/' . $filename); // here it stuck`

What could be the possible reason?

**Comment by mikehaertl** [comment]
Under the hood we use my php-shellcommand library to execute `pdftk`. We do some nifty things there to capture all the stdout and stderr strings from the command. Do you have a chance to play around with the code here (i.e. comment out parts, etc.):

https://github.com/mikehaertl/php-shellcommand/blob/master/src/Command.php#L418

**Comment by mikehaertl** [comment]
... and maybe easier to test: try to set the `useExec` option to `true`. You can try other options for the shell command i linked above, too.

https://github.com/mikehaertl/php-pdftk#shell-command

**Comment by mikehaertl** [comment]
@itsowaisnoor Any news here?

**Comment by mikehaertl** [comment]
Closing this as there was no further feedback and I was not able to reproduc the issue.

Feel free to add more comments to help clarify then we can reopen the issue.
