### ISSUE TITLE
I added the path in the option parameter but it is not working

### ISSUE THREAD

**Issue by Anichur25** [mikehaertl/php-pdftk#246]
$pdf = new Pdf('my.pdf',[
        'command' => 'usr/bin/pdftk'
     ]);

But this is not working. It does not generate any error or warning

**Comment by mikehaertl** [comment]
You forgot the leading `/` in your path: `/usr/bin/pdftk`

**Comment by Anichur25** [comment]
You're right Mike. But if i use 'command' => '/usr/bin/pdftk' still it is not working. It throws an error like 'sh:1, usr/bin/pdftk not found'

**Comment by mikehaertl** [comment]
Well, then probably `pdftk` ist not installed or it's the wrong path or PHP is not allowed to execute pdftk. Maybe you have the same issue as #245. 

But please understand that I can not provide support for installing pdftk on your system. Like statet in the readme: Having pdftk installed and available for PHP is a requirement.
