### ISSUE TITLE
using PDFTK on OVH or o2switch

### ISSUE THREAD

**Issue by yeheland** [mikehaertl/php-pdftk#247]
Hi !

am I obligated to use 'command' => 'C:\Program Files (x86)\PDFtk Server\bin\pdftk.exe', even with composer  ?,

because i need to use it on a website but i dont find how since i need this pdftk.exe

thanks for your help

**Comment by mikehaertl** [comment]
Sorry, this is not a support forum. Please understand that I can not provide any help on how to set up your system.

You need to find out where the `pdftk.exe` is installed on your system and set this in `command` as shown in the README.

**Comment by yeheland** [comment]
it's a question on your library not a  support.

Is PDFTK could work on a website or not ? beacuse on a web hosting i  cant get the path of a pdftk.exe since i cant download there a program

**Comment by mikehaertl** [comment]
This library is not restricted in any way. If `pdftk` (or `pdftk.exe` on Windows) is installed and executable from a PHP script then it should work.

You should ask your web hoster for support.

**Comment by yeheland** [comment]
So this command line is not mandatory ? 

'command' => 'C:\Program Files (x86)\PDFtk Server\bin\pdftk.exe',

**Comment by mikehaertl** [comment]
On Windows it usually is required. Again: You need to set the correct path to `pdftk.exe` and I don't know that path for your system. I also don't know how to install pdftk on your server. But that's a requirement for our library. So it's your job to find out how to do that (or ask your web hoster for help).
