### ISSUE TITLE
UTF8 chars

### ISSUE THREAD

**Issue by juklicekjan** [mikehaertl/php-pdftk#25]
Hi Mike,

my by you can help me - whatever I do I can't fill UTF8 characters to form fields (my name for example: Juklíček). I have installed pdftk 2.02.

Have you some idea where is problem? Thank you

**Comment by mikehaertl** [comment]
Have you added `needAppearances()`? There are some limitations to pdftk and UTF-8. You can check this lengthy discussion here for more details: #4.

**Comment by mikehaertl** [comment]
Closing this now, as there was no further feedback.
