### ISSUE TITLE
PDF set working / second PDF set not working

### ISSUE THREAD

**Issue by JBurkeDux** [mikehaertl/php-pdftk#252]
Has anyone encountered an issue where 4 PDFs were created, the first two work perfectly and the second set does not? In the second set, the field values do not display (and the PDF settings look identical). Thanks for any insights.

**Comment by mikehaertl** [comment]
Please understand that this is not a support forum but a system for reporting bugs. If you think something needs a fix please provide a clear and short (!) code example and maybe a PDF file that demonstrates the issue. If we can't reproduce the issue we can't provide any help.
