### ISSUE TITLE
"input PDF is not an acroform, so its fields were not filled" in form previously edited and filled

### ISSUE THREAD

**Issue by willpower232** [mikehaertl/php-pdftk#255]
I have a template PDF form which can be filled in by this library however one of the pages is a long table and it is possible for the user to want more rows than are available.

I have modified the generation code to repeat and fill the page in question and an even longer form is generated.

Unfortunately, one of the final steps is to later fill in a couple of other fields but now I am informed that it is no longer an acroform.

This used to work and the form is indeed still editable but apparently it has been mangled at some level during this update and can no longer be filled in.

Do you have any ideas as to where I can investigate next?

**Comment by mikehaertl** [comment]
I can't really help you how to create a PDF that uses acroform. This very much depends on the software you use to create the PDF but I can't tell you which one is best. I never had to deal with that and always got PDFs that used the right form format. Maybe also check #39.

**Comment by willpower232** [comment]
The PDF is fine, the only thing that has changed is using this library to re generate it one additional time.

I had to start doing something like this (borrowed from the readme)

```php
use mikehaertl\pdftk\Pdf;

// Extract pages 1-5 and 7,4,9 into a new file
$pdf = new Pdf('/path/my.pdf');
$pdf->cat(1, 5)
    ->cat([7, 4, 9]);

// We now use the above PDF as source file for a new PDF
$pdf2 = new Pdf($pdf);
$result = $pdf2->fillForm(['name' => 'ÄÜÖ äüö мирано čárka'])
    ->needAppearances()
    ->saveAs('/path/filled.pdf');
if ($result === false) {
    $error = $pdf->getError();
}
```

Does doing this mean that the PDF is no longer a form after being saved to disk?

**Comment by mikehaertl** [comment]
I didn't say that your PDF is "not fine" (whatever that means). PDF is a complex format and forms can be embedded there in different ways. Our library is quite innocent - it only wraps calls to `pdftk`. And `pdftk` can't handle PDFs without a form in acroform format. That's what your error message says and that's all I can say. I don't know how or why this happens or did not happen before.

Why it works with the code you pasted? I have no idea. Again: If - at all - someone is to blame, it's `pdftk` - not our library. 

And regarding your question: As long as you don't `flatten()` the form (which I avoid by any means, as - again - pdftk can't handle e.g. UTF-8 characters) the form should still be there.

**Comment by marcvinyals** [comment]
@willpower232 See https://gitlab.com/pdftk-java/pdftk/-/issues/95

**Comment by czcpf** [comment]
@willpower232 @mikehaertl

I ran into the same problem this week. I was using pdftk 2.02  on MacOSX which I installed using the .pkg file  PDFtk Server from https://www.pdflabs.com/tools/pdftk-server/

The issue doesn't seem to have anything to do with php-pdftk as mentioned by the author but with pdftk itself.  I can't be certain of the underlying issue but what I noticed was the following:

For this example, lets assume file.pdf mentioned below has a form in it with a field `LegalBusinessName` on page 2

```php
$pdf = new Pdf('path/to/file.pdf');
$data = $pdf->getDataFields();
file_put_contents('data/upload/fileDataFields.json',json_encode($data,JSON_PRETTY_PRINT));
```
data/upload/fileDataFields.json
```json
{
    "0": {
        "FieldType": "Text",
        "FieldName": "LegalBusinessName",
        "FieldFlags": "0",
        "FieldValue": "",
        "FieldJustification": "Left"
    },
}
```
Updating the pdf without doing any combining works  with no errors. 

```php
$pdf = new Pdf('path/to/file.pdf');
$result =  $pdf->fillForm(['LegalBusinessName' => 'Works LLC'])
    ->needAppearances()
    ->saveAs('path/to/newfile.pdf');

// Always check for errors
if ($result === false) {
    $error = $pdf->getError();
    echo $error;
}
```
However, if you try the following or other combinations thereof it will error out when you try to fill in the form

```php

$pdfTemplate = new Pdf('path/to/file.pdf');
$pdfTemplate->cat(2,null); //extract only page 2

$pdfTemplate2 = new Pdf('path/to/file.pdf');
$pdfTemplate2->cat(2,null); //extract only page 2

$pdfLocation1 = new PDF($pdfTemplate); //create new pdf with only page 2
$pdfLocation2 = new PDF($pdfTemplate2); //create new pdf with only page 2

$pdf = new Pdf([
    'A' => $pdfLocation1,
    'B' => $pdfLocation2
]);

// THE COMBINED FILE IS SUCCESSFULLY SAVED. NO ERRORS YET
$result =  $pdf->needAppearances()
    ->saveAs('path/to/newfile.pdf');

// Always check for errors
if ($result === false) {
    $error = $pdf->getError();
}

$pdf = new Pdf('path/to/newfile.pdf');

// THIS FAILS
$result =  $pdf->fillForm(['LegalBusinessName' => 'Works LLC'])
    ->needAppearances()
    ->saveAs('path/to/newfile.pdf');

// Always check for errors
if ($result === false) {
    $error = $pdf->getError();
    echo $error;
}
```
OUTPUT
"Warning: input PDF is not an acroform, so its fields were not filled."

If we take a look at newfile.pdf that was written when we combined the two pages into one file we see that during the merge operation it actually created a new field 1.LegalBusinessName

```php
$pdfTemplate = new Pdf('path/to/newfile.pdf');
$data = $pdfCombined->getDataFields();
file_put_contents('data/upload/newFileDataFields.json',json_encode($data,JSON_PRETTY_PRINT));
```
data/upload/newFileDataFields.json
```json
{
    "0": {
        "FieldType": "Text",
        "FieldName": "LegalBusinessName",
        "FieldFlags": "0",
        "FieldValue": "",
        "FieldJustification": "Left"
    },
    "1": {
        "FieldType": "Text",
        "FieldName": "1.LegalBusinessName",
        "FieldFlags": "0",
        "FieldValue": "",
        "FieldJustification": "Left"
    },
}
```
For some reason, pdftk 2.02 doesn't like either this field name format #.<fieldName> or falsely flags this error when calling fillForm

SOLUTION:

uninstall pdftk from your OS X and install pdftk-java instead (ie. brew install pdftk-java). This is a drop-in replacement as far as I can tell and seems to be well maintained as @marcvinyals mentioned. pdftk-java seems a bit slower but it fixes this bug. I hope it helps.
