### ISSUE TITLE
Getting Tab Order of fields

### ISSUE THREAD

**Issue by RyanEwen** [mikehaertl/php-pdftk#257]
Hi there,

When getting a list of fields from a PDF file, they are returned in the order that they were last written/modified within the source file.

Is it possible to get the "tab order" of the fields, so that I can display the fields in the same order as they appear in the source file? Acrobat allows you to order the fields so that when the tab key on keyboard is pressed, the cursor jumps to fields in a specific order. This order is much more useful than the way they're currently ordered. Acrobat also seems to group them by page, allowing you to get a list of fields per-page instead of just overall.

**Comment by mikehaertl** [comment]
We can only use the information provided by `pdftk`. The field data is generated from the output of `pdftk some.pdf dump_data_fields`. Could you check if you find the information you want is somewhere in pdftk's output? If it's there we may have to fix our parser. If not there's nothing we can do.

**Comment by RyanEwen** [comment]
Thanks for the quick response - pdftk is lacking the information in its output. I'll reach out to them instead!

**Comment by Daphne816** [comment]
@RyanEwen , did you ever find out a way around this? I'm struggling with the same issue.
