### ISSUE TITLE
Github discussion for this repository

### ISSUE THREAD

**Issue by janstieler** [mikehaertl/php-pdftk#259]
Hi,
would you activate the Github discussion function for asking Questions about PHP-PDFtk?
So you can separate the unwanted problems questions from the issue tracker.

Cheers

**Comment by mikehaertl** [comment]
Please understant that I can not provide more help or assistance. Discussions need to be maintained and I don't want to do that. Actually there should not be so much to discuss here anyway. Most questions are rather about pdftk itself so they should be handled there.
