### ISSUE TITLE
HELP  ERROR: drop_xfa need_appearances

### ISSUE THREAD

**Issue by ssaenz2014** [mikehaertl/php-pdftk#26]
Hi, I need your help. On computers with 64bit it works ok, but 32bit displays the following error:

pdftk A = 'form.pdf' fill_form '/tmp/php_pdftk_fdf_nKls23.fdf' output '/tmp/tmp_php_pdftk_RmwzAP.pdf' drop_xfa need_appearances

code:
        $ form = 'form.pdf';
         $ file = 'test.pdf';
         $ data = array (
             'name' => 'Jürgen Carka čČćĆđĐ мирано'
             'email' => 'test@email.com'
             'checkbox 1' => 'Yes',
             'checkbox 2' => 0,
             'Radio 1' => 2
         );

         $ pdf = new PDF ($ form);
         $ pdf-> fillForm ($ data);
         $ pdf-> needAppearances ();
         $ pdf-> send ($ file);

         echo (string) $ pdf-> getTmpFile ();
         echo (string) $ pdf-> getCommand ();

**Comment by mikehaertl** [comment]
I can't see any error message in your post.

**Comment by ssaenz2014** [comment]
This is the mistake and does not work the send ():

"Failed without error message: pdftk A='form.pdf' fill_form '/tmp/php_pdftk_fdf_ptjokU.fdf' output '/tmp/tmp_php_pdftk_xprlwS.pdf' drop_xfa need_appearances"

code PHP:
 $form = 'form.pdf';
        $file = 'test.pdf';
        $data = array(
            'name' => 'Jürgen čárka čČćĆđĐ мирано',
            'email' => 'test@email.com',
            'checkbox 1' => 'Yes',
            'checkbox 2' => 0,
            'radio 1' => 2,
        );

        $pdf = new Pdf($form);
        $pdf->fillForm($data);
        $pdf->needAppearances();
        $pdf->send($file);


        if (!$pdf->send()) {
                echo $pdf->getError();
        }

**Comment by mikehaertl** [comment]
Is there some output in stdout? `echo $pdf->getCommand()->getOutput()`

**Comment by ssaenz2014** [comment]
No, not return

**Comment by mikehaertl** [comment]
Then I don't really know. Maybe you use an older version of pdftk on that server?

**Comment by ssaenz2014** [comment]
but why 32bit Windows computers displays error, however in 64bit works

**Comment by mikehaertl** [comment]
So you are on Windows? You could try to set the `useExec` option, it sometimes helps on Windows. If this doesn't help, I have no idea. The best option is, not to use Windows.

**Comment by ssaenz2014** [comment]
I could make it work. I removed the line:
  $ Pdf-> needAppearances ();
