### ISSUE TITLE
File attachments?

### ISSUE THREAD

**Issue by mtaki14** [mikehaertl/php-pdftk#263]
Is there a method for attaching a file to a pdf? Upon looking at the available methods in the wrapper I couldn't see one that is applicable.

**Comment by mikehaertl** [comment]
@mtaki14 I've implemented `attachFiles()` now. Could you help testing this please? You have to pull the `issue-263-attach-file` branch. The syntax is like:

```php
<?php
$pdf = new Pdf('/some/file.pdf');

// Add files at the document level
$pdf->attachFiles(['/path/to/file']);

// alternatively with a page number:
$pdf->attachFiles(['/path/to/file'], 5);

$pdf->saveAs('/some/out.pdf');
```

**Comment by mtaki14** [comment]
That's great to hear!

Unfortunately I'm currently busy and I'll be unable to get to this for the next 1-2 weeks but I'll let you know as soon I do.

**Comment by mtaki14** [comment]
Hi, sorry for the delay.

After doing some brief testing:

-  attachFiles at document level seems to work as expected, which is great.
- after testing attachfiles with a page argument and opening the resulting file in Adobe Acrobat, I could see that it adds the files as a comment with a pin icon (see attached screenshot). Is it possible to make the placement a bit more consistent? As you can see the pin placement is not alligned. I'm not sure how much control you have over this.

![image](https://user-images.githubusercontent.com/7987430/142605111-480cf312-bfa7-4dcb-a1c2-82f83dae6c1f.png)

**Comment by mikehaertl** [comment]
> I'm not sure how much control you have over this.

Well as usual: If `pdftk` can't do it - php-pdftk can't do it either. If you find out how to get what you want with `pdftk` on the command line then let me know here and I see if we can add it.

But from the man page I would assume that there's no other option:

> attach_files <attachment filenames | PROMPT> [to_page <page number | PROMPT>]
>                 Packs arbitrary files into a PDF using PDF's file attachment features. More than one attachment may be listed after attach_files. Attachments are added at the document level unless the op‐
 >                tional to_page option is given, in which case the files are attached to the given page number (the first page is 1, the final page is end). For example:
>
 >                pdftk in.pdf attach_files table1.html table2.html to_page 6 output out.pdf

**Comment by mikehaertl** [comment]
@mtaki14 If you agree and have no further suggestions I would now merge this and create a new release.

**Comment by mtaki14** [comment]
Yeah, no further suggestions from my part, feel free to merge

**Comment by mikehaertl** [comment]
Ok, 0.11.0 is out including this new feature. Thanks for your help!
