### ISSUE TITLE
Failed without error message: pdftk "A"="1.pdf" dump_data_utf8 (Exit code: 1)

### ISSUE THREAD

**Issue by Orxan80dd** [mikehaertl/php-pdftk#265]

**Comment by mikehaertl** [comment]
With such little information it's impossible to help.

**Comment by Orxan80dd** [comment]
require_once("sources/pdftk_v/vendor/autoload.php");
use mikehaertl\pdftk\Pdf;

try {
// Get data
$pdf = new Pdf('1.pdf');

$data = $pdf->getData();
echo '<pre>';
print_r($pdf);
echo '</pre>';
if ($data === false) {
    $error = $pdf->getError();
}

// Get form data fields
$pdf = new Pdf('1.pdf');
$data = $pdf->getDataFields();
if ($data === false) {
    $error = $pdf->getError();
}

// Get data as string
echo $data;
$txt = (string) $data;

// Get data as array
$arr = (array) $data;
$field1 = $data[0]['Field1'];


	} 
catch (\Exception $e) {
	echo '<pre>';
  	print_r($e);
   echo '</pre>';
}
and get this result

mikehaertl\pdftk\Pdf Object
(
    [ignoreWarnings] => 
    [tempDir] => 
    [_tmpFile:protected] => 
    [_tmpOutputContentType:protected] => application/pdf
    [_command:protected] => mikehaertl\pdftk\Command Object
        (
            [_command:protected] => pdftk
            [_files:protected] => Array
                (
                    [A] => Array
                        (
                            [name] => 1.pdf
                            [password] => 
                        )

                )

            [_options:protected] => Array
                (
                )

            [_operation:protected] => dump_data_utf8
            [_operationArgument:protected] => Array
                (
                )

            [_escapeOperationArgument:protected] => 
            [escapeArgs] => 1
            [escapeCommand] => 
            [useExec] => 
            [captureStdErr] => 1
            [procCwd] => 
            [procEnv] => 
            [procOptions] => 
            [nonBlockingMode] => 
            [timeout] => 
            [locale] => 
            [_stdIn:protected] => 
            [_args:protected] => Array
                (
                    [0] => "A"="1.pdf"
                    [1] => dump_data_utf8
                )

            [_stdOut:protected] => 
            [_stdErr:protected] => 
            [_exitCode:protected] => 1
            [_error:protected] => Failed without error message: pdftk "A"="1.pdf" dump_data_utf8 (Exit code: 1)
            [_executed:protected] => 
        )

    [_handle:protected] => 1
    [_error:protected] => Failed without error message: pdftk "A"="1.pdf" dump_data_utf8 (Exit code: 1)
    [_output:protected] => 
    [_data:protected] => 
    [_data_utf8:protected] => 
    [_dataFields:protected] => 
    [_dataFields_utf8:protected] => 
    [_pdfs:protected] => 
)
