### ISSUE TITLE
Failed without error message: pdftk "A"="1.pdf" dump_data_utf8 (Exit code: 1)

### ISSUE THREAD

**Issue by Orxan80dd** [mikehaertl/php-pdftk#266]
I use this code
<pre>
require_once("sources/pdftk_v/vendor/autoload.php");
use mikehaertl\pdftk\Pdf;

try {
// Get data
$pdf = new Pdf('1.pdf');

$data = $pdf->getData();
print_r($pdf);
if ($data === false) {
    $error = $pdf->getError();
}
	} 
catch (\Exception $e) {
	
  	print_r($e);
}

</pre>
and get this result 
<pre>
mikehaertl\pdftk\Pdf Object
(
    [ignoreWarnings] => 
    [tempDir] => 
    [_tmpFile:protected] => 
    [_tmpOutputContentType:protected] => application/pdf
    [_command:protected] => mikehaertl\pdftk\Command Object
        (
            [_command:protected] => pdftk
            [_files:protected] => Array
                (
                    [A] => Array
                        (
                            [name] => 1.pdf
                            [password] => 
                        )

                )

            [_options:protected] => Array
                (
                )

            [_operation:protected] => dump_data_utf8
            [_operationArgument:protected] => Array
                (
                )

            [_escapeOperationArgument:protected] => 
            [escapeArgs] => 1
            [escapeCommand] => 
            [useExec] => 
            [captureStdErr] => 1
            [procCwd] => 
            [procEnv] => 
            [procOptions] => 
            [nonBlockingMode] => 
            [timeout] => 
            [locale] => 
            [_stdIn:protected] => 
            [_args:protected] => Array
                (
                    [0] => "A"="1.pdf"
                    [1] => dump_data_utf8
                )

            [_stdOut:protected] => 
            [_stdErr:protected] => 
            [_exitCode:protected] => 1
            [_error:protected] => Failed without error message: pdftk "A"="1.pdf" dump_data_utf8 (Exit code: 1)
            [_executed:protected] => 
        )

    [_handle:protected] => 1
    [_error:protected] => Failed without error message: pdftk "A"="1.pdf" dump_data_utf8 (Exit code: 1)
    [_output:protected] => 
    [_data:protected] => 
    [_data_utf8:protected] => 
    [_dataFields:protected] => 
    [_dataFields_utf8:protected] => 
    [_pdfs:protected] => 
)

</pre>

**Comment by Orxan80dd** [comment]
actually i need change links in pdf file and resave

**Comment by mikehaertl** [comment]
Is `pdftk` installed? Can you execute it from PHP? E.g. try `exec('pdftk')`. If there's no error message then in 99% it's a problem that the library can not execute `pdftk`.

**Comment by mikehaertl** [comment]
> actually i need change links in pdf file and resave

You can't do that with `pdftk`. Check the README and `man pdftk` to see the available features.

**Comment by Orxan80dd** [comment]
i  use exec('pdftk'); and no any error message 
install this with composer 
command
composer require mikehaertl/php-pdftk

**Comment by Orxan80dd** [comment]
> 
> 
> > actually i need change links in pdf file and resave
> 
> You can't do that with `pdftk`. Check the README and `man pdftk` to see the available features.

i can't extract file as array, change links and save as new file?

**Comment by mikehaertl** [comment]
Have you seen the requirements in the README?

> Requirements
> The pdftk command must be installed and working on your system

This library is not `pdftk` - we only provide frontend for PHP. You need to install it yourself.

**Comment by mikehaertl** [comment]
Please understand that I can not provide personal assistance on how to install required software or how to setup this library. There's plenty of information out there.

I'm closing this as there is no bug.
