### ISSUE TITLE
/usr/bin/pdftk: Java configuration directory /etc/java was ignored because configuration file /etc/java/java.conf does not exist

### ISSUE THREAD

**Issue by suhan-gajjar** [mikehaertl/php-pdftk#267]
Im using pdftk and get an issue about that it was working fine before but something causing that issue 

[17:33] Tejas Gajjar
     [_stdErr:protected] => /usr/bin/pdftk: Java configuration directory /etc/java was ignored because configuration file /etc/java/java.conf does not exist
/usr/share/java-utils/java-functions: line 213: /usr/bin/build-classpath: No such file or directory
Error: Could not find or load main class com.gitlab.pdftk_java.pdftk

**Comment by mikehaertl** [comment]
Can you use `pdftk` on the command line? 

Is think that this is rather an issue for `pdftk` - our class here is only a PHP frontend for the CLI tool.

**Comment by suhan-gajjar** [comment]
@mikehaertl any suggestion here for me to resolve this?

**Comment by suhan-gajjar** [comment]
using `pdftk` in command line gives me below error

```
/bin/pdftk: Java configuration directory /etc/java was ignored because configuration file /etc/java/java.conf does not exist
/usr/share/java-utils/java-functions: line 213: /usr/bin/build-classpath: No such file or directory
Error occurred during initialization of VM
Unable to allocate 65536KB bitmaps for parallel garbage collection for the requested 2097152KB heap.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by mikehaertl** [comment]
I have no idea. You should better ask at the pdftk project. We can't solve this here.
