### ISSUE TITLE
Squares instead of symbols after merging

### ISSUE THREAD

**Issue by velial31** [mikehaertl/php-pdftk#268]
Hello, after `cat()` 2 or more files, squares are displayed instead of Cyrillic. However, when you click on the field, the characters are displayed normally (I suspect that there is a problem with the fonts). When filling out the form, there is no such problem.
I use `needAppearances()`, but its no help on the merging.

**Comment by mikehaertl** [comment]
It's a problem with the fonts used in your PDF. This can't be fixed by pdftk. You need to edit the PDF and ensure that the correct fonts are used. I can't provide any help or guidelines on how to do that as I'm not a PDF expert either.

**Comment by marcvinyals** [comment]
@velial31 newer versions of pdftk-java have an option to replace fonts in a PDF, this may help when filling a form. But there should not be any font problems when simply merging two PDFs. If you can provide examples of files that cause problems, please open an issue at https://gitlab.com/pdftk-java/pdftk/-/issues and I will be happy to help.

**Comment by mikehaertl** [comment]
@marcvinyals Thanks, I didn't know about the font replacement feature. I should probably consider adding this to our library too.

**Comment by velial31** [comment]
Found out what the problem was. The solution from this discussion https://github.com/mikehaertl/php-pdftk/issues/142 helped. 
When you use `cat()`, `needApperances()` does not work. It might be worth adding this to the documentation. 
Here is my code that worked:
```
        $pdf = new \mikehaertl\pdftk\Pdf([
            '1.pdf',
            '2.pdf'
        ]);
        $pdf->execute();

        $pdf2 = new \mikehaertl\pdftk\Pdf($pdf);
        $pdf2->needAppearances();
        $pdf2->saveAs('final.pdf');
```
