### ISSUE TITLE
Print Arabic language issue 

### ISSUE THREAD

**Issue by arvind-1989** [mikehaertl/php-pdftk#269]
Print Arabic language issue when use flatten() method

**Comment by mikehaertl** [comment]
This is not possible with pdftk as far as I know. In any case it's nothing we can fix here as this is just a PHP frontend for `pdftk`. You could try to open a feature request at [pdftk-java](https://gitlab.com/pdftk-java/pdftk).

**Comment by mohaninfosec** [comment]
Hello @mikehaertl , Is there any alternative to print Arabic content in form fileds.

**Comment by mikehaertl** [comment]
Sorry, I have no other recommendations. The only workaround that I know is usually to not use `flatten()` when you fill a form.

**Comment by arvind-1989** [comment]
Hello @mikehaertl is that possible placeholder are disable mode when rendered pdf means when pdf are saved can't to edit at placeholder value

**Comment by mohaninfosec** [comment]
@mikehaertl Can we get the positions for form fileds?

**Comment by mikehaertl** [comment]
Sorry, please understand that this is not a support forum. Please check the README for available features. I also did not implement `pdftk` so I can't answer specific PDF questions. Please check `man pdftk` for available options. 

Regarding placeholders: That's way out of scope of what pdftk can do to my knowledge. And for position of form fields see `getDataFields()` - not sure if the information is included there.
