### ISSUE TITLE
Support utf-8 AND flatten..

### ISSUE THREAD

**Issue by Marcpepe** [mikehaertl/php-pdftk#27]
Hi,

This works and displays accented characters :

    $pdf = new Pdf('form.pdf');
    $pdf->fillForm(array('name'=>'ÄÜÖ äüö мирано čárka'))
        ->needAppearances()
        ->saveAs('filled.pdf');

This doesn't..

    $pdf = new Pdf('form.pdf');
    $pdf->fillForm(array('name'=>'ÄÜÖ äüö мирано čárka'))
        ->needAppearances()
        ->flatten()
        ->saveAs('filled.pdf');

I know this might be normal, since you're using fonts to render accented characters. But do you see a way around this ?

Great work and thanks for sharing this!

**Comment by mikehaertl** [comment]
Unfortunately this is a limitation of pdftk. You can read the whole story (and read about a possible workaround with mcpdf) here: https://github.com/mikehaertl/php-pdftk/issues/4

**Comment by skyinsurance** [comment]
I am using pdftk server in my application sometimes it is unable to generate pdf and it returns an error 
mikehaertl\pdftk\Pdf Object ( [ignoreWarnings] =>false)
here is my code 
$pdf = new Pdf ( $filepath,['command' => '/usr/local/bin/pdftk','useExec' => true,]);
$pdf->fillForm ( $arr_full_data )->compress()->flatten()->saveAs ( $save_file );
Please let me know is there any problem in it
