### ISSUE TITLE
Chrome adds .html file extension to pdf file

### ISSUE THREAD

**Issue by loeffe1** [mikehaertl/php-pdftk#271]
This only happens in chrome and whether I am setting headers manually or not, doesn't make a difference. Instead of downloading a pdf file, chrome will add .html to the file. The created file is a valid pdf file after removing the .html extension.

This is what my code looks like with manual set headers:

```
$pdf = new Pdf($tmp . '/pdf/form.pdf', [
    'command' => '/usr/bin/pdftk',
]);
$pdf->tempDir = $tmp;

$name = 'test.pdf';
$pdfFile = $pdf->fillForm($pdfData)
    ->needAppearances()
;

$result = $pdfFile->send($name, false, array(
    'Content-Type' => 'application/pdf',
    'Content-disposition' => 'inline; filename="' . $name . '"',
    'Cache-Control' => 'public, must-revalidate, max-age=0',
    'Pragma' => 'public',
    'Expires' => 'Sat, 26 Jul 1997 05:00:00 GMT',
    'Last-Modified' => \gmdate('D, d M Y H:i:s') . ' GMT'
));
```

Comparing the headers of Chrome on my desktop machine and via Browserstack on a mobile device, it turn out Chrome on Android sends a text/html; charset=utf-8 Content-Type header

**Comment by mikehaertl** [comment]
Hmm, can you do me a favour and check the code in [php-tempfile](https://github.com/mikehaertl/php-tmpfile/blob/master/src/File.php#L95) that we use? It's very simple. 

It would help if you could you create a PHP file (without our libraries) that uses the same headers as we use in tempfile. Then play around with the settings and see if you find a setting where the download works for you.

**Comment by loeffe1** [comment]
Adding and exit() after creating the file fixed it. Turns out my CMS was sending additional headers that Chrome on Windows and Firefox generally apparently were ignoring while Chrome on Android didn't.
