### ISSUE TITLE
Failed without error message

### ISSUE THREAD

**Issue by rashidchachar** [mikehaertl/php-pdftk#274]
Hello,
I am working on this package using laravel. 
this is my code.
  $file = public_path('pdf-form.pdf');
  $pdf = new Pdf($file);

  $data = $pdf->getDataFields(false);
  
  i got this error every time 
  "Failed without error message: pdftk "A"="D:\xampp\htdocs\laravel\myproject\public\pdf-form.pdf" dump_data_fields (Exit code: 1)"

**Comment by mikehaertl** [comment]
It seems you are on Windows and did not configure the path to `pdftk.exe`. Check the README: https://github.com/mikehaertl/php-pdftk#shell-command

**Comment by rashidchachar** [comment]
Thanks for the response @mikehaertl 
yes i m on Windows nd figured it out without installing pdftk on my local system it will not gonna work so i installed it on my local and it works fine. but know i am going to live my project on shared hosting how could i install pdftk on shared hosting i m little bit confused here.

**Comment by mikehaertl** [comment]
Sorry, I can not help you with that. You need to find out yourself how to install pdftk on your target system. Please understand that this is not a support forum but a system to report bugs.
