### ISSUE TITLE
FieldStateOption array order

### ISSUE THREAD

**Issue by iagorc** [mikehaertl/php-pdftk#276]
Hi:

I have a problem when i try to access to the data values of FieldType Button when i use the function getDataFields with arrays.

I dont understand how it works. Sometimes FieldStateOption array gets one order of the values and sometimes others.

Could you explain to me what criteria is used in the order in which the information is represented in these arrays?

Thanks, best regards.

**Comment by mikehaertl** [comment]
The order should be the same as you see it in `pdftk dump_data_fields_utf8 file.pdf`. If this is not the case could you paste:
* the output of that command
* what you get in PHP
* what you would expect

**Comment by iagorc** [comment]
I have a pdf with a ButtonType that contains 3 values: option1, option2 and option 3, in this order. When i dump the result i get this:
![image](https://user-images.githubusercontent.com/20191528/146909873-22b108fa-de3a-47bb-901c-a9a7b9874bc4.png)
I dont understand why this array is not ordered at the same way of my Button in pdf
This is the first element of my ButtonType:
![image](https://user-images.githubusercontent.com/20191528/146910216-cd6c7791-9137-4930-af4a-44b4d10a28bb.png)

Thanks

**Comment by mikehaertl** [comment]
We have no control in which order `pdftk` returns the fields. It's probably the order that they are stored in the internal PDF format. In any case this is rather an issue for pdftk, not for our library here.
