### ISSUE TITLE
Exit code: 3

### ISSUE THREAD

**Issue by awanish786** [mikehaertl/php-pdftk#277]
Using same package in Zend 2 and core php , there it is working fine but in laravel everything looks fine as used previously still getting following error- 

Failed without error message: pdftk "A"="form.pdf" "fill_form" "C:\Users\dell\AppData\Local\Temp\php3691.tmp.xfdf" "output" "C:\Users\dell\AppData\Local\Temp\tmp36D0.tmp.pdf" "drop_xfa" "flatten" "need_appearances" (Exit code: 3)

**Comment by mikehaertl** [comment]
It seems you use it on windows and have not configured the path to `pdftk.exe` in the `command` option: https://github.com/mikehaertl/php-pdftk#shell-command
