### ISSUE TITLE
Need help to make it work.

### ISSUE THREAD

**Issue by kuflievskiy** [mikehaertl/php-pdftk#28]
Hi!
We tried to use this library on our dev server..
PHP 5.5.9
pdftk 2.02

And it doesn't work properly. Could you please check if it is common problem or just on our side.

We saw that files in the /tmp directory were created but they could not be copied correctly.

We tried to set chmod($this->_fileName, 0777 ); after the line
https://github.com/mikehaertl/php-pdftk/blob/master/src/FdfFile.php#L50 and then we saw another error : 

https://github.com/mikehaertl/php-pdftk/blob/master/src/Pdf.php#L492 - not defined varriable

Please reply... Thanks in advance.

**Comment by mikehaertl** [comment]
I've fixed the error message, thanks. Your problem seems to indicate a permission problem. The error message should tell you now, which file could not be copied.

**Comment by kuflievskiy** [comment]
> Your problem seems to indicate a permission problem.

Yes, it the problem was on the our side.
Thanks for the help! Closing...
