### ISSUE TITLE
[Question] Flatten just specific form fields?

### ISSUE THREAD

**Issue by Jannomag** [mikehaertl/php-pdftk#284]
Hi,
I finally got php-pdftk working for filling a pdf. It works flawlessly but I'm looking for a way to flatten just specific form fields instead of flatten the whole document.
Is this even possible?

**Comment by mikehaertl** [comment]
This is a question about `pdftk`. We can only wrap the features provided by pdftk. To my knowledge there are no options to `flatten`, so there's probably no way to only flatten a part of a form.

**Comment by Jannomag** [comment]
Well, I couldn't find an answer so I tried asking you because you worked with pdftk way more than me. Anyways, sadly pdftk seems to have no option for this at all. Thanks!
