### ISSUE TITLE
Cannot access pdf file in laravel

### ISSUE THREAD

**Issue by jans147** [mikehaertl/php-pdftk#285]
Hello I'm new to laravel but i need to set password in confidential pdf files inside the laravel public directory. Luckily I found this package but it seems that I cannot access the pdf file.

I tried to run this code:

$filePath = public_path('test.pdf');
  
        $pdf = new Pdf($filePath);

        $password = 'password';
        $userPassword = 'password1';
  
        $result = $pdf->allow('AllFeatures')
                        ->setPassword($password)
                        ->setUserPassword($userPassword)
                        ->passwordEncryption(128)
                        ->saveAs($filePath);

        dd($filePath, $result, $pdf->getError());

        return $result;

and I get this result in with dd():

^ "C:\Users\Johnvic\Desktop\uro 2\FINAL\otr_system\public\test.pdf"
^ false
Failed without error message: pdftk "A"="C:\Users\Johnvic\Desktop\uro 2\FINAL\otr_system\public\test.pdf" "output" "C:\Users\Johnvic\AppData\Local\Temp\tmp890D.tmp.pdf" allow AllFeatures "owner_pw" "123456" "user_pw" "123456a" "encrypt_128bit" (Exit code: 1)

Any help would be much appreciated. Thanks!

**Comment by mikehaertl** [comment]
On Windows you usually need to set the path to the `pdftk.exe` in the `command` option. See https://github.com/mikehaertl/php-pdftk#shell-command
