### ISSUE TITLE
Unable to find file with diacritics in the filename.

### ISSUE THREAD

**Issue by jadamec** [mikehaertl/php-pdftk#286]
Hi there,
it's unable to find files with diacritics in its name.

For example, for the file named **001- Form Čučoriedka 06-2022.pdf** it shows an error **_Unable to find file._** (even it exists and path is correct).

How to fix this, please?

**Comment by jadamec** [comment]
#4

**Comment by mikehaertl** [comment]
From what I remember you had to do a couple of things to make this work. In any case the environment where you execute that command has to support a unicode aware locale (check with  `locale -a` and check e.g. for something like `en_US.utf8` or `de_DE.utf8`).

You then need to make sure, that the command is executed with that locale. You may also have to pass this as environment variable to `proc_env()`. You can do both via options: 

```
$pdf = new Pdf($file, [
    'locale' => 'en_US.utf8',
    'procEnv' => [
        'LANG' => 'en_US.utf-8',
    ],
]);
```
Related:  https://github.com/mikehaertl/php-shellcommand/issues/7

**Comment by jadamec** [comment]
Thanks, but adding this didn't solve the issue.

**Comment by mikehaertl** [comment]
Did you check for the right locale? Also try to echo the command and see if it works manually on the command line:

```
echo $pdf->getCommand()->getExecCommand();
```

**Comment by jadamec** [comment]
Oh well.. I was using a wrong locale, now it works perfectly! Thanks. :)
