### ISSUE TITLE
Issue with checkbox

### ISSUE THREAD

**Issue by GigaYahaa** [mikehaertl/php-pdftk#287]
Hello, have a html form with lot of check box and i want to link them to the pdf which i created some checkbox too with Adobe acrobat
is it possible ?
I really need this help pls for my work....

Thanks

**Comment by mikehaertl** [comment]
Please understand that this is not a support forum but a bug reporting system. I can not provide support on how to build your project or how to use this library beyond what is explained in the README.

**Comment by mikehaertl** [comment]
A checkbox is a form field like any other. The field has an (internal) name and option value and is filled as shown in the README:

```
$pdf = new Pdf('/full/path/to/form.pdf');
$result = $pdf->fillForm([
        'some_chebox_name'=> 1,  // whatever the option value is in your PDF
    ])
    ->needAppearances()
    ->saveAs('filled.pdf');
```

Try `pdftk my.pdf dump_data_fields_utf8` to get a list of all fields and their names and option values.

That's really all help I can provide.
