### ISSUE TITLE
Install in shared hosting

### ISSUE THREAD

**Issue by neutralchung** [mikehaertl/php-pdftk#288]
Hello, I would like to know is there any way not to install pdftk in the system. We have a project which need to launch on shared hosting server. So I can install any executable file of the pdftk. How can I still run this plugin for my project? Thank you so much

**Comment by mikehaertl** [comment]
No, `pdftk` is strictly neccessary as the library is only a wrapper for it. 

Please understand that I can not provide any further help on how to set up your system or how to install pdftk. You should consult your hoster if there are restrictions.
