### ISSUE TITLE
Wrong diacritic characters filled

### ISSUE THREAD

**Issue by jadamec** [mikehaertl/php-pdftk#289]
Hi there, why my diacritic characters are wrongly filled into fields, please? From the **+ľščťžýáíé** I got this in Google Chrome (also when trying to print via Adobe Acrobat Reader):
![Snímka obrazovky 2022-06-16 125756](https://user-images.githubusercontent.com/19595874/174055870-1d203e3f-8e52-4467-9e3f-45e1eacb7858.jpg)

When filling directly from Adobe Acrobat Reader, these characters work correctly...

```
$pdf = new Pdf('/Šablóna 014.pdf', [
  'locale' => 'en_US.utf8',
  'procEnv' => [
    'LANG' => 'en_US.utf-8',
  ],
]);

$pdf->fillForm([
    'name' => '+ľščťžýáíé'
  ])
  ->needAppearances()
  ->send('Šablóna 014 vyplnené.pdf');
```

**Comment by mikehaertl** [comment]
This is very likely rather a problem with wrong fonts embedded in the PDF. We can't fix this. You have to edit the PDF and use a font that includes those characters.

**Comment by jadamec** [comment]
It has a basic Helvetica font set (supports all characters). As I said, when filling directly from Adobe Acrobat Reader.. everything is good.

**Comment by mikehaertl** [comment]
Also check out this comment where someone says, that the default font Helvetica will *not* support all characters: https://github.com/mikehaertl/php-pdftk/issues/4#issuecomment-691846192

From my own projects I know that everything works fine if the PDF is created with the right font embedded. I just can't provide any help on this as I always got the PDFs from someone else and never had these problems.

**Comment by jadamec** [comment]
Thank you for your time! Changing font from Helvetica to Arial fixed this problem.
