### ISSUE TITLE
Form radio button had change with template

### ISSUE THREAD

**Issue by maxdang29** [mikehaertl/php-pdftk#290]
I have form
![image](https://user-images.githubusercontent.com/44836904/177237813-2727c186-0431-4ca5-bf5a-944b9848088b.png)
and prepare form like this 
![image](https://user-images.githubusercontent.com/44836904/177237921-578eca2d-610f-4813-a1d4-5c026d48f863.png)

I generate the pdf
$pdftk->fillForm(['applicant__1__own_property' => 'Yes'])
            ->flatten()
            ->needAppearances();

it change to 
![image](https://user-images.githubusercontent.com/44836904/177238696-bedb40d4-b3fa-47fa-8881-1cf496c19336.png)

My expectation is to stay the same as before, I don't know what happen?

**Comment by mikehaertl** [comment]
I don't really know but you may have passed the wrong values when you fill the form. They can often be different from the field labels. Check with `pdftk xyz.pdf dump_data_fields` and look for `FieldValue`.

Apart from that I have no other idea. pdftk can not modify the form layout. So it could also be that something is wrong with your PDF form.
