### ISSUE TITLE
This doesn't seem to be working from browser

### ISSUE THREAD

**Issue by laurie-fletcher** [mikehaertl/php-pdftk#30]
It doesn't work from browser, but it works fine from terminal.

Here is the code:

```
<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);

require_once __DIR__ . '/config.php';
require_once __DIR__ . '/vendor/autoload.php';

$formData = array(
    'Doctor' => 'Alexsei Kusnetsov',
    'Receptionist' => 'Tatiana Pitters',
    'Name' => 'Linda Ullesburg',
    'PersonalNumber' => '197303051663',
    'StreetAddress' => '3 Acddreai Asie',
    'PostalCode' => 'P39283',
    'DaytimePhone' => '0234165432',
    'MobilePhone' => '39872347292',
    'Date' => '2011/12/32',
    'Signature' => 'Alexsei Kusnetsov'
);

use mikehaertl\pdftk\Pdf;

$pdfFile = __DIR__ . '/form.pdf';
$saveAs = sprintf(__DIR__ . '/output.pdf');

$pdf = new Pdf($pdfFile);

$pdf
    ->fillForm($formData)
    ->allow('Printing')
    ->flatten()
    ->dropXfa()
    ->dropXmp()
    ->needAppearances()
    ->saveAs($saveAs);
```

it does generate a pdf file when I run it on terminal by using `php generate.php`, but when i run it on browser like `http://localhost/generate.php`, it doesn't generate anything nor errors. I am using Mamp Pro 3.4, Google Chrome, and Terminal on Mac OS 10.10 Yosemite.

I need it to run from web browsers.

**Comment by mikehaertl** [comment]
Sorry but I can not debug your server setup. If it works from the console, it's not a problem with the library itself but something with your server configuration.
