### ISSUE TITLE
RuntimeException - Please help

### ISSUE THREAD

**Issue by sanjoyroy** [mikehaertl/php-pdftk#302]
Please help I am unable to install and getting the runtime exception below:
PS C:\inetpub\dms.xyz.com.au\application\libraries> composer require mikehaertl/php-pdftk
[RuntimeException]                                                                                                             
  require-dev.mikey179/vfsStream is invalid, it should not contain uppercase characters. Please use mikey179/vfsstream instead.  
*Note: please note that I have already installed the composer before running the command.

**Comment by mikehaertl** [comment]
Sorry, your issue is not related to our library but rather seems like some problem with composer. I can not provide help with that.
