### ISSUE TITLE
File doesn't get saved to the path provided !

### ISSUE THREAD

**Issue by senuradp** [mikehaertl/php-pdftk#303]
Hi, I used pdf-tk to merge 2 pdf documents and when I try to save it, it doesn't get saved to the path provided.  I have attached the code I have used, below. Your help would be highly appreciated. TIA.

                $pdfTk = new PdfTk($pdf1, $pdf2);

                $now = DateTime::createFromFormat('U.u', microtime(true));

                $fileName = 'merged_' . $now->format('Y-m-d H:i:s.u') . '.pdf';

                $pdfTk->saveAs(public_path('letters/' . $fileName));

                return APIHelper::makeAPIResponse(true, 'Files merged successfully', 'letters/merge.pdf', 200 );

**Comment by mikehaertl** [comment]
You have not called any operation. In your case you need to add `cat()`. 

You should also check the return value of `saveAs()` and if it's false check for errors with `getError()`.

**Comment by senuradp** [comment]
> You have not called any operation. In your case you need to add [cat()](https://github.com/mikehaertl/php-pdftk/blob/master/src/Pdf.php#L138).
> 
> You should also check the return value of `saveAs()` and if it's false check for errors with `getError()`.


If possible could you where I should add cat() ? 

And... the return value is false :|

**Comment by mikehaertl** [comment]
https://github.com/mikehaertl/php-pdftk/blob/c856d2da0749df07354696801261465fba563a9c/src/Pdf.php#L157-L160

Sorry, I can not provide more help than this. Please check the manual and study the code to get a better understanding.
