### ISSUE TITLE
Cannot install via composer

### ISSUE THREAD

**Issue by Style87** [mikehaertl/php-pdftk#304]
When I attempt to install via composer I get the error below. This is the only package in my list that doesn't install.
```
$ composer require mikehaertl/php-pdftk

In RemoteFilesystem.php line 477:

  The "?pagelen=100&fields=values.name%2Cvalues.target.hash%2Cnext&sort=-target.date" file could not be downloaded: Failed to open stream: No such file or directory
```
Any idea why this is happening?

**Comment by mikehaertl** [comment]
No, sorry. And I can't see how this is related to a bug in our library. Must be something with composer.
