### ISSUE TITLE
PDF file is not generating

### ISSUE THREAD

**Issue by hndanao** [mikehaertl/php-pdftk#305]
I've used your exact codes and installed composer just like you did in youtube video, but still no file is being generated. There's no file also in the completed folder. Im using windows. I tries removing the access method because the error says direct access not permitted as the error message. I replaced it with require generatepdf. I got to the thanks page and downloaded the "said" file but it has no file. How to fix this? I made it work on a different laptop months ago and i got this error too but i forgot what i did and it certainly is not in phpshell command. Thankyouu

**Comment by mikehaertl** [comment]
> I've used your exact codes and installed composer just like you did in youtube video, ...

Not sure what you mean, I don't provide any youtube video. Maybe you should ask the author.

I can also not provide any personal assistance on how to set up the library. You need to make sure that pdftk.exe is installed and on Windows you probably have to configure the path to it in the `command` option (see https://github.com/mikehaertl/php-pdftk#shell-command). If it still doesn't work it must me some Windows related issue. I can't help with that.
