### ISSUE TITLE
Update textfield name id in Form

### ISSUE THREAD

**Issue by jonathan-vandal** [mikehaertl/php-pdftk#308]
Hello,

I have a form to fill but all textfield name id are are not intuitive so I'd like to rename them. 
e.g: I have a key named "undefined_2" I have to rename it into "customser_address"

It's possible to do this with this library ? I see there is updateInfo() method but I don't know how to use it.

Thanks !

**Comment by mikehaertl** [comment]
I don't think this is possible with pdftk. Please also understand that this is not a support forum but a system to report bugs.
