### ISSUE TITLE
Fields depending on radio button not shown

### ISSUE THREAD

**Issue by Centridox** [mikehaertl/php-pdftk#309]
HI, I have a form in which some fields only appear when a specific radio button is checked. When "checking" this, the values entered in the depending fields are still "white". After opening the PDF and clicking a radio button again, but now in the reader, the values are shown.

Strange thing, when using the option on a Mac, in Safari, all values are shown. It's all about the attached PDF

Any suggestions? 
[MyForm.pdf](https://github.com/mikehaertl/php-pdftk/files/11415197/MyForm.pdf)

**Comment by mikehaertl** [comment]
I'm sorry, but I can not provide any assistance with PDF form related questions like this. Our library can only fill in data into well-prepared PDF forms. If the forms don't behave as expected then the PDF may need to be authored in a different way. That's out of the scope of this lib.
