### ISSUE TITLE
Fill_Form when using custom fonts in the input PDF is not working

### ISSUE THREAD

**Issue by meena-kasi-optus** [mikehaertl/php-pdftk#31]
Hello,

Please could you help me fix the issue below.

I am programmatically filling in a input pdf form fields with a dynamically generated .fdf file using pdftk.

 pdftk /path/input_form.pdf fill_form /path/data.fdf output /path/output_form.pdf flatten

Some of the text that needs to be filled in needs to use a specific licensed custom font.

I get the following error message when I use licensed fonts in my input_form.pdf.

On running the below command, I get the error below.

" pdftk /path/input_form.pdf fill_form /path/data.fdf output /path/output_form.pdf flatten"

ERROR MESSAGE:
----------------------------
Unhandled Java Exception in create_output():
java.lang.ArrayIndexOutOfBoundsException: 0
   at pdftk.com.lowagie.text.pdf.DocumentFont.fillEncoding(pdftk)
   at pdftk.com.lowagie.text.pdf.DocumentFont.doType1TT(pdftk)
   at pdftk.com.lowagie.text.pdf.DocumentFont.<init>(pdftk)
   at pdftk.com.lowagie.text.pdf.AcroFields.getAppearance(pdftk)
   at pdftk.com.lowagie.text.pdf.AcroFields.setField(pdftk)
   at pdftk.com.lowagie.text.pdf.AcroFields.setFields(pdftk)

However, when I switch my input PDF to use the font like "Times New Roman", the filled in output PDF gets generated fine.

Below is my code:
-----------------------

//Input PDF
$input_pdf = public_path().'/input_form.pdf';

//Input FDF
$input_fdf = public_path().'/data.fdf';

//Output PDF
$output_pdf = public_path().'/output_form.pdf';
                 
$pdf = new Pdf($input_pdf);
$pdf->fillForm($input_fdf)
        ->flatten()  
        ->saveAs($output_pdf);  

How could I get my output form to get filled in with the custom licensed font without any errors.

Any help would be much appreciated.

Thank you.

**Comment by mikehaertl** [comment]
This seems to be a problem with pdftk itself. Does it work on the command line, if you use `pdftk` without this tool? If not, then I can't do much about it.

**Comment by mikehaertl** [comment]
Closing this, as there was no further feedback.

**Comment by cpreach** [comment]
Reopening this. I have the exact same issue. PDFTK creates all pdf's when used standard fonts in input form. If i choose a custom font it is not working. Any Idea on this?

**Comment by bounoable** [comment]
Don't know why it won't work but this workaround makes it work: https://stackoverflow.com/a/44442957/7852108

But for me, it won't use the right font but a default one.

**Comment by mikehaertl** [comment]
I'm sorry, but font issues are really nothing we can fix here. I know it's a pain - dealing with PDFs always is. Personally I'm not really an expert either but I remember having to dive into PDF internals some time ago. You can check the discussion in #4 where you can follow my learning process. Maybe it helps.

**Comment by elpeyotl** [comment]
@bounoable this solves the issue, but the preflight settings (settings for printing etc.) change if you save the pdf in preview. We decided to use the standard fonts and it is working pretty well. 

as @mikehaertl says, dealing with PDF's is always a pain. ;) 

@mikehaertl thank you for this nice little plugin!
