### ISSUE TITLE
Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by JohnnyLouweret** [mikehaertl/php-pdftk#315]
Getting the following on php8.1
    
Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated

 ```
   $result = $pdf
            ->fillForm($data) <------ here

    protected function xmlEncode($value)
    {
        return defined('ENT_XML1') ?
            htmlspecialchars($value, ENT_XML1, 'UTF-8') :
            htmlspecialchars($value);
    }
```

Anything we can do about this?

**Comment by mikehaertl** [comment]
It seems you have `null` as values in your `$data`. Can you confirm that? If that's the case, we can probably just skip those values.

**Comment by JohnnyLouweret** [comment]
Not entirely sure right now, but it seems more likely that some values in the array have null values as I cannot return null.

```
->fill($data->toArray())
function toArray(): array
```

```
[
    'firstName' => null,
    'lastName' => 'some name'
]
```

**Comment by mikehaertl** [comment]
Can you check if the fix in PR #316 works for you?

**Comment by mikehaertl** [comment]
@JohnnyLouweret Is there any news here? Were you able to test it?

**Comment by mikehaertl** [comment]
Closing this as there was no further feedback.
