### ISSUE TITLE
setPassword function disable external links

### ISSUE THREAD

**Issue by kapdom** [mikehaertl/php-pdftk#319]
Hi. 

When I use function setPassword then all external links in pdf are disabled. 
How can I keep links active after protect file by password.

![Screenshot from 2023-11-08 10-27-26](https://github.com/mikehaertl/php-pdftk/assets/41866018/0632ff7f-f916-4747-bbb9-6439c709014e)

**Comment by mikehaertl** [comment]
Sorry, I can not help you with questions like this: This is caused by `pdftk` itself, not our library. I'd suggest you reproduce the problem on the command line and then report the problem at pdftk.
