### ISSUE TITLE
Problems with Checkboxes

### ISSUE THREAD

**Issue by asteinbr** [mikehaertl/php-pdftk#32]
First thank you for your work.

I discovered a problem in my environment with php-pdftk and checkboxes in a PDF form.
My code is following:

    <?php
    echo "testPdftk.php started...<br>";
    
    require_once('vendor/autoload.php');
    
    ini_set('display_errors', 1);
    ini_set('display_startup_errors', 1);
    
    use mikehaertl\pdftk\Pdf;
    
    $data = array(
        'name' => 'Jürgen čárka čČćĆđĐ мирано',
        'email' => 'test@email.com',
        'checkbox 1' => 'Yes',
        'checkbox 2' => 0,
        'radio 1' => 2,
    );
    
    $pdf = new Pdf('form.pdf', [
        'command' => "/home/usr1/.toast/armed/bin/pdftk",
        'useExec' => true
    ]);
    $pdf->fillForm($data);
    $pdf->needAppearances();
    $pdf->saveAs('filled.pdf');
    
    echo "<br><a href='filled.pdf'>Output</a>";

So, I am using some extracts of your testcase. 
The result is that no checkbox is checked. I also checked your output file 'https://github.com/mikehaertl/php-pdftk/blob/master/tests/files/filledform.pdf' from the testcases, there is the same output, no checkbox checked, but for my understanding the code-line

    'checkbox 1' => 'Yes'

should check the checkbox, which is not checked, though.

Is this desired or a possible bug?
My environment is following: PHP 5.6.12 and pdftk 2.02.

Thank you in advance.

**Comment by mikehaertl** [comment]
You need to make sure, that the value you set for the checkbox field in the array is the same as what you defined as option value in the PDF. In Acrobat this is what you see if you open the checkbox properties and go to "Options -> Export Value". If you use `pdftk my.pdf dump_data_fields` you should see that value under `FieldStateOption:`.

**Comment by asteinbr** [comment]
Thank you for this information. I could manage it now, the checkbox is checked.

So I just changed 

    'checkbox 1' => 'Yes'

to

    'checkbox 1' => 'On'

respectively

    'checkbox 1' => 'Off'

Thanks again!

**Comment by jbirch8865** [comment]
I could be wrong but I'm having issues unchecking a box.  
I have a form that I captured the dump_data_fields and saw the FieldValue of the Button was 'Off'.  Then I opened the pdf in Adobe Reader -> checked the box -> saved it and redumped the data fields.  Now the FieldValue is 'Yes'.  Everything is great.  However if I use fillForm(['Button' => 'Off']) the checkbox is still checked.  So I opened the file in reader again and unchecked the box.  Then dumped the data fields and noticed the FieldValue is missing altogether.  It isn't even a key in the field list.  Is there anyway to use fillForm() and remove the FieldValue parameter of a valid field?

**Comment by its-stark** [comment]
Liebe Kunden und Geschäftspartner,

vielen Dank für Ihre Nachricht.

Ich bin von Samstag, dem 18.08. bis Montag den  03.08. im Urlaub. Ab Dienstag den 04.8. bin ich wieder für Sie da und beantworte gerne Ihre Nachricht.

Viele Grüße,
Thomas Stark.
