### ISSUE TITLE
Initilizing PDF with remote file

### ISSUE THREAD

**Issue by Aniket-IN** [mikehaertl/php-pdftk#321]
Hi, 
Thank you for the amazing library.

I was wondering, is there any way to initilize the PDF object with a remotely stored PDF file? 
In my case, the form file is stored in a S3 bucket. 

So, can I directly use that? 
Like if I get the file contents or something?

Thank you.

**Comment by mikehaertl** [comment]
The library only works with local files. So you have to download the PDF file first and then pass it to the lib.
