### ISSUE TITLE
Fluent usage of methods 

### ISSUE THREAD

**Issue by dennobaby** [mikehaertl/php-pdftk#322]
Example:
I'm doing this:
```
$pdf->getDataFields();
  ... some more code...not related to $pdf
 $pdf->fillForm($array);
```

i get: 
```
[Exception]                     
  Operation was already executed 
```

Further method-calls should work without reinstantiate the library.

**Comment by mikehaertl** [comment]
I guess you've seen the note [here](https://github.com/mikehaertl/php-pdftk?tab=readme-ov-file#operations):

> IMPORTANT: You can always only perform one of the following operations on a single PDF instance. Below you can find a workaround if you need multiple operations.

Making this work would require a rewrite of the library. As this project is basically already in maintenance mode for a while  this change is not going to happen, sorry.
