### ISSUE TITLE
shared libraries loading issue

### ISSUE THREAD

**Issue by soorajthekkepatt** [mikehaertl/php-pdftk#323]
/home4/jcharson/bin/pdftk: error while loading shared libraries: libgcj.so.10: cannot open shared object file: No such file or directory

**Comment by mikehaertl** [comment]
Nothing we can fix here. If pdftk can not be executed from PHP (or not at all) we can't do anything. Maybe some security restriction or maybe you installed the wrong version of pdftk for your system.

Also first make sure that you can run pdftk on the command line.
