### ISSUE TITLE
getDataFields returning false, differs from pdftk command line tool.

### ISSUE THREAD

**Issue by psrivongse** [mikehaertl/php-pdftk#33]
Running this code in MAMP server on my local machine. 

I cannot seem to get any output from getDataFields, however using pdftk command line it works just fine. Any thoughts?
```
$pdf = new Pdf('sample.pdf');
$data = $pdf->getDataFields(); // returning false
```
```
pdftk sample.pdf dump_data_fields output fields.txt
```

**Comment by mikehaertl** [comment]
Do you get any error in `$pdf->getError()`?

**Comment by psrivongse** [comment]
Sorry, I've been out of town and haven't had a chance to get back to you. I don't get anything from. It ends up being an empty string.
```
$pdf->getError()

**Comment by mikehaertl** [comment]
Hmm, then I'm not sure what's happening. Did you configure the path to `pdftk`? See the `command` option. It's described at the end of this section: https://github.com/mikehaertl/php-pdftk#options

**Comment by psrivongse** [comment]
Setting the proper command path fixed my issue. Thanks Mike!

**Comment by jimmy0699** [comment]
have same issue, but setting `command` option not help, i setting it from results of `which pdftk`

**Comment by mikehaertl** [comment]
Did you check `getError()`? If that's empty, I can't really help. You could check the generated command string that you can get with `echo (string) $pdf->getCommand()` and verify that the path to pdftk is right. Also try if you can execute `pdftk` from PHP with a simple `exec(/path/to/pdftk)`.
