### ISSUE TITLE
Fill form removes input's format

### ISSUE THREAD

**Issue by psjavi** [mikehaertl/php-pdftk#330]
Hi, I've a PDF template with custom fonts, colors and so on

If I edit the pdf in my computer (without the fonts installed) the pdf peserves the fonts but when I fill the pdf by code, the format dissapear.

What is wrong?

Thanks in advance.

**Comment by mikehaertl** [comment]
That's probably a problem with pdftk itself. It's nothing we can fix here. You can try to report the issue at pdftk - but should first be able to reproduce it on the command line.
