### ISSUE TITLE
global data connection lost

### ISSUE THREAD

**Issue by FVZGmbH** [mikehaertl/php-pdftk#331]
I created a xfa pdf with LiveCycle Designer (static type). I have 2 pages, each has the field "KNR". I connected them by setting the fields data connection to "use global". If I change ones value, the other will be changed too. Fine.
Now I use pdftk to pre-fill some fields using fillForm() (finally there's a toString())

The fillForm() method eliminates the data connection between these 2 fields (even if I dont fill this field with pdftk). It seems, that the xfa structure is responsible for this.
In "normal" pdf you can point a field just by name "KNR". So they probably stay connected. In xfa you need to go thru the whole structure like "Formular1[0].#page[0].KNR[0]" & "Formular1[0].#page[1].KNR[0]". I cant find a flag or sth like that to reconnect them.

A workaround with JS was not successful, seems JS is eliminated during pdftk process.

Is there a way to solve this problem?

**Comment by FVZGmbH** [comment]
Holy...  I was testing for about 3 days to get rid of the problem. After I wrote the issue I found the solution.
call ->fillform($data, $encoding, $dropXfa) with $dropXfa = false because default is true

I hope this won't cause new issues

**Comment by mikehaertl** [comment]
It sounds like your problem is rather in pdftk itself than in our library. Maybe you can confirm if you use pdftk on the command line. If you have the same problem there you should report your problem to the pdftk project. This here is just an (independent) PHP wrapper for that utility.

**Comment by FVZGmbH** [comment]
I'll try - is there a way to output the final command and the fdf file which seems to be just a temporary file?

**Comment by mikehaertl** [comment]
Yeah, there is some magic going on behind the scenes and our library creates temporary files for dynamic data because `pdftk` expects files as input.

The final command (including those temp file args) could be fetched with `$pdf->getCommand()->getExecCommand()`.

But you can easily create an instance of an `FdfFile` yourself, though. Something like this should work:

```php
<?php
$fdfFile = new FdfFile(['someVar' => 'someValue']);
$fdfFile->saveAs('/path/to/output.fdf');
```

**Comment by FVZGmbH** [comment]
Mhh... my tests seem to figure out, thats it's pdftk itself.

As you commented @Pdf.dropXfa(), you'll need to drop xfa to fill a xfa based pdf, but dropping xfa will cause connection loss between global linked fields...
Unfortunately this makes sense because of the different fieldNames.

Do you know a way to rename them dynamically? With your tool? Maybe this could be a way to solve the problem.

**Comment by mikehaertl** [comment]
I don't think it's possible with pdftk. And our library has no additional functionality on top of pdftk.

So if you agree I will close this issue for now as there's nothing to fix for us here.
