### ISSUE TITLE
dyld[17509]: Library not loaded: /opt/homebrew/opt/icu4c/lib/libicuio.73.dylib

### ISSUE THREAD

**Issue by msomoye** [mikehaertl/php-pdftk#332]
I have been trying to run "composer require mikehaertl/php-pdftk", but I keep getting the following error:

dyld[17509]: Library not loaded: /opt/homebrew/opt/icu4c/lib/libicuio.73.dylib
  Referenced from: <139D175A-03FF-30B0-926E-B3B5282021FF> /opt/homebrew/Cellar/php@8.0/8.0.30_1/bin/php
  Reason: tried: '/opt/homebrew/opt/icu4c/lib/libicuio.73.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/icu4c/lib/libicuio.73.dylib' (no such file), '/opt/homebrew/opt/icu4c/lib/libicuio.73.dylib' (no such file), '/opt/homebrew/Cellar/icu4c@76/76.1_1/lib/libicuio.73.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/icu4c@76/76.1_1/lib/libicuio.73.dylib' (no such file), '/opt/homebrew/Cellar/icu4c@76/76.1_1/lib/libicuio.73.dylib' (no such file)
Abort trap: 6

What would you advise I do?

**Comment by mikehaertl** [comment]
That error sounds completely unrelated to our library. It rather looks like a broken installation of PHP on your system. Try searching on the web for the error message.
