### ISSUE TITLE
sh: pdftk: command not found

### ISSUE THREAD

**Issue by philipmustang** [mikehaertl/php-pdftk#34]
I did install pdftk server on my Mac and the pdftk command runs without problems on any folder.

However, while using your tool, I got the error: sh: pdftk: command not found 

$pdf = new Pdf('t4.pdf');
$pdf->fillForm('t4_data.fdf')
            ->saveAs('T4filled.pdf');
var_dump($pdf->getError());

Could you please help me with this?

Thank you very much.

**Comment by mikehaertl** [comment]
Check the `command` option. You find an example at the end of this section here: https://github.com/mikehaertl/php-pdftk#options

**Comment by DanceSC** [comment]
I am getting the same error: 
Error: sh: pdftk: command not found
Do I need to install pdftk separately and reference that installation? Or is the 
    'command' => '/some/other/path/to/pdftk', a path that I can reference in /php-pdftk-master/ ?

**Comment by mikehaertl** [comment]
> Do I need to install pdftk separately and reference that installation?

Yes, it must be installed on our system. If it's not in your search path, you'll also need to configure the path in `command`.

**Comment by shafrazlk** [comment]
i have downloaded the package via composer and the pdftk is also installed (C:\Program Files (x86)\PDFtk). Then tried to use the package as in example but when i do **$pdf->getData()** it returns a "**false**" value only. Below is my code
```
use mikehaertl\pdftk\Pdf;

$pdf = new Pdf('E:\IIS_PROJECTS\KPV\public\documents\test.pdf', [
				    'command' => 'C:\Program Files (x86)\PDFtk\bin\pdftk.exe',
				    'useExec' => true,
				]);
```

What am i doing not correct here? Any guidance highly appreciated.

**Comment by mikehaertl** [comment]
This probably has to do with this issue here: https://github.com/mikehaertl/php-shellcommand/issues/1.

**Comment by shafrazlk** [comment]
Hi Mike,

Actually it was working once i restarted the machine. And i didn't required to include option parameters.

Thanks for the quick reply.

**Comment by emaguana** [comment]
I have the same error. I updated laravel 5 to 5.1 and now I get:sh: pdftk: command not found
Might you help me??

**Comment by roddyguy22** [comment]
Same problem. I installed PDFTK and Mike's library and everything worked fine. I rebooted my server (centos 6) and get the "Command not Found" error. Runs fine using SSH command line. Stumped.

**Comment by roddyguy22** [comment]
I figured out my problem. The autoloader in my framework wasn't working correctly and I was missing a file. (make sure all files are being included). 

I also used the command options Mike mentioned:

		$pdf = new Pdf($pdf_file, [
			'command' => '/usr/local/bin/pdftk',
			'useExec' => true,
		]);

Everything working fine now. Hope this helps someone.

**Comment by emmettculley** [comment]
I know this is an old thread, but...  It turns out that pdftk rpms are not available for anything newer than fedora 19.  It there another way to use your Laravel plugin?

**Comment by feenes** [comment]
pdftk is really kind end of life. You might have to change the application to use another toolkit like for example stapler https://pypi.org/project/stapler/

**Comment by divdax** [comment]
Do you guys know which tool is well maintained to merge pdf's? I need to merge PDF-A (3 pages) with PDF-B (1 page) as background für every page in PDF-A.
