### ISSUE TITLE
Compatible File Types

### ISSUE THREAD

**Issue by sandy0201** [mikehaertl/php-pdftk#36]
Hi,

Does pdftk only merge multiple PDF files into one PDF?
Is it possible to merge DOC and DOCX files as well into a PDF?

Thank you.
Kind regards.

**Comment by mikehaertl** [comment]
I'm sorry, but please understand that this is not a support forum. If you have questions about the capabilities of pdftk please do some research (i.e. google for it). I can only provide help if something is broken with this extension.

**Comment by fr3nch13** [comment]
👏
