### ISSUE TITLE
Duplicate page and pge count

### ISSUE THREAD

**Issue by sebastienOD** [mikehaertl/php-pdftk#37]
Hi, 

first thank you for your very good work on pdftk and specially fillform.
I hope it's the right place to post a question.
I'm trying to use your cat function in order to duplicate page without success.
Trying to create a function like this : 
public function duplicatePage($pageNumber,$where)

but i can't get it working with cat and if i  wan't to loop  through pages, i need the number of pages and i c'ant get it.
Could you tell me if i miss something?

thx

**Comment by mikehaertl** [comment]
Not sure how I can help you. The `cat()` method is quite self explaining. If you need the number of pages, you can use `getData()` and check for `NumberOfPages` there. Just note that you can't reuse the same `Pdf` instance after you called `getData()`.

**Comment by sebastienOD** [comment]
Thank you for your answer, i found NumberOfpages and i also discover that i can't reuse the same Pdf.
It's now working.
Thank you for your work,
