### ISSUE TITLE
Centos 7

### ISSUE THREAD

**Issue by fulldecent** [mikehaertl/php-pdftk#38]
We love this product and have used it on Centos 6 very happily.

Please let me know if there are any practical solutions for installing this on Centos 7 which you are aware of.

Thank you.

**Comment by mikehaertl** [comment]
Sorry, I've never used  Centos so I can't help out.

**Comment by fulldecent** [comment]
For reference: if anyone else is interested, I am continuing discussion at https://github.com/documentcloud/docsplit/issues/123

**Comment by fulldecent** [comment]
Cross reference. I am raising a bounty to get pdftk and php-pdftk to run on CentOS 7. Other enterprise users that depend on php-pdftk and are prevented from upgrading to the latest CentOS because of this are invited to follow progress below.

> https://github.com/fulldecent/pdftk
