### ISSUE TITLE
Input PDF is not an acroform

### ISSUE THREAD

**Issue by shafrazlk** [mikehaertl/php-pdftk#39]
Hi,

I am trying to fill a pdf form but i get an error saying **Warning: input PDF is not an acroform, so its fields were not filled.**

I checked the original pdf file for form fields and found the field names are not straight forward. For example the one of the field name is **form1[0].#subform[6].TelephoneNumber[0]**

Is there any work around to fill a form in such a pdf document?

Thank you

**Comment by mikehaertl** [comment]
That's a pdftk specific question. I'm not sure, if I remember it correctly, but I think it was like this.

There are 2 form formats with PDF: AcroForm and XFA. pdftk can only use AcroForms. But a PDF can contain both form formats.

You should google for pdftk + acroform. Also mabe this helps: http://stackoverflow.com/questions/17226484/pdftk-and-xfdf-file-not-filling-in-form

**Comment by shafrazlk** [comment]
Yes Mike, you are correct.

For the time being i was able to use the original XFA formatted PDF to create new AcroForm formatted PDF file with my own fields. Then managed to use your package.

Thank you for the response.
