### ISSUE TITLE
Missing characters

### ISSUE THREAD

**Issue by Niproblema** [mikehaertl/php-pdftk#4]
Hello i am using part of your code. FfdfFile class with following code(only the part with characters): 

```
   if ($directory === null) {
        $directory = sys_get_temp_dir();
    }
    $filename = $filename;
    $fields = '';
    foreach ($data as $key => $value) {

        $utf16Value = mb_convert_encoding($value,'UTF-16BE', $encoding);

        // Escape parenthesis
        $utf16Value = strtr($utf16Value, array('(' => '\\(', ')' => '\\)'));
        $fields .= "<</T($key)/V(" . chr(0xFE) . chr(0xFF) . $utf16Value . ")>>\n";
    }
```

Problem is that some characters are missing like "čćđ", on the other hand there are "šž", which is nice but i need them all... I have tried few things but i can't quite get more characters working. If i open created .fdf file in notepad i can see an empty space where "č" should be. I am using .fdf file to fill out pdf and at the places with missing characters there is a blank spot..

**Comment by naduvko** [comment]
Sorry for digging in this old issue, but can you help me how to substitute pdftk with mcpdf?
Command is working  from shell. Tried with passing command with constructor, but it's not working, and there's no debug to see what can be wrong.

**Comment by mikehaertl** [comment]
@naduvko I've never used `mcpdf` but you coud try to configure `java -jar mcpdf.jar` as `command` option. See the bottom of the README.

**Comment by naduvko** [comment]
I tried but it didn't work. Hope that @Niproblema can help.

**Comment by maxpoland** [comment]
Hi,

I am using mcpdf, when I try flatten option it doesn't show filled form data.
please help

**Comment by deshario** [comment]
Is there any solution that .. we can use utf8 chars and flatten also ... Is there any other lib except pdftk that can fill forms...

**Comment by naduvko** [comment]
I modified Command class to use this [MCPDF](https://github.com/m-click/mcpdf) and it works!

**Comment by deshario** [comment]
@naduvko  Do u have examples ... Can u share with me. Thankx bro

**Comment by naduvko** [comment]
https://github.com/mikehaertl/php-pdftk/blob/ace8311507f398806be78f51a7ae7d9ceb24e9fa/src/Command.php#L20
change to `protected $_command = 'java -jar /mcpdf.jar';`

https://github.com/mikehaertl/php-pdftk/blob/ace8311507f398806be78f51a7ae7d9ceb24e9fa/src/Command.php#L176
change to `$this->addArg(' ',$file['name']);`

https://github.com/mikehaertl/php-pdftk/blob/ace8311507f398806be78f51a7ae7d9ceb24e9fa/src/Command.php#L197
change to `$this->addArg(' > ',$filename, false);`

**Comment by deshario** [comment]
@naduvko I had download mcdf-0.2.4.jar from [here](https://github.com/m-click/mcpdf) and rename it into mcdf.jar and keep this file into same dir where Command.php located ... but when i test it says : 

### Error : Command failed

![image](https://user-images.githubusercontent.com/11426727/57938317-2b934000-78f2-11e9-8a57-334d9bd4fbf4.png)

![image](https://user-images.githubusercontent.com/11426727/57938396-4d8cc280-78f2-11e9-9af0-b9f7bfff0104.png)


**Is there something missing from me**

**Comment by deshario** [comment]
@naduvko I had download **mcpdf-0.2.4-jar-with-dependencies.jar** from [here ](https://github.com/m-click/mcpdf#getting-started) and rename it into mcdf.jar and keep this file into same dir where Command.php located 

![image](https://user-images.githubusercontent.com/11426727/57941218-90ea2f80-78f8-11e9-96c1-419070f68b33.png)

![image](https://user-images.githubusercontent.com/11426727/57940940-c4788a00-78f7-11e9-80a7-e7dfb38ff122.png)


![working](https://user-images.githubusercontent.com/11426727/57941062-10c3ca00-78f8-11e9-9374-e73d35dff5ee.PNG)


### but when i test it says => Error : Command failed

![image](https://user-images.githubusercontent.com/11426727/57941163-61d3be00-78f8-11e9-8e38-6da7d2c9321a.png)


** Is there something missing from me**

**Comment by deshario** [comment]
**If i change my code from**  
` $pdf = new Pdf($sourceFile, ['command' => $pdftk_path, 'useExec' => true]);`  
 **To**
`  $pdf = new Pdf($sourceFile);`

![image](https://user-images.githubusercontent.com/11426727/57941492-4b7a3200-78f9-11e9-8a3d-08037748181c.png)

**Comment by deshario** [comment]
@naduvko 

**If i change my code from**  
` $pdf = new Pdf($sourceFile, ['command' => $pdftk_path, 'useExec' => true]);`  
 **To**
`  $pdf = new Pdf($sourceFile);`

![image](https://user-images.githubusercontent.com/11426727/57941492-4b7a3200-78f9-11e9-8a3d-08037748181c.png)

**Comment by deshario** [comment]
@naduvko I had download **mcpdf-0.2.4-jar-with-dependencies.jar** from [here ](https://github.com/m-click/mcpdf#getting-started) and rename it into mcdf.jar and keep this file into same dir where Command.php located and also replace 3 lines of command as u said 

![image](https://user-images.githubusercontent.com/11426727/57941218-90ea2f80-78f8-11e9-96c1-419070f68b33.png)

![image](https://user-images.githubusercontent.com/11426727/57940940-c4788a00-78f7-11e9-80a7-e7dfb38ff122.png)


![working](https://user-images.githubusercontent.com/11426727/57941062-10c3ca00-78f8-11e9-9374-e73d35dff5ee.PNG)


### but when i test it says => Error : Command failed

![image](https://user-images.githubusercontent.com/11426727/57941163-61d3be00-78f8-11e9-8e38-6da7d2c9321a.png)


### But If i change my code from
` $pdf = new Pdf($sourceFile, ['command' => $pdftk_path, 'useExec' => true]);`  
 **To**
`  $pdf = new Pdf($sourceFile);`

![image](https://user-images.githubusercontent.com/11426727/57941492-4b7a3200-78f9-11e9-8a3d-08037748181c.png)

** Is there something missing from me**

**Comment by naduvko** [comment]
Why don't you prepare an fdf and try the command via command line?

**Comment by lopandpe** [comment]
When you create a new form in acrobat, the default font used in all text fields is Helvetica, where those characters don't exist. 

You need to edit your form, and change thee font family manually. PDFTK will use that font.

**Comment by OmarShaker97** [comment]
> @naduvko I had download **mcpdf-0.2.4-jar-with-dependencies.jar** from [here ](https://github.com/m-click/mcpdf#getting-started) and rename it into mcdf.jar and keep this file into same dir where Command.php located and also replace 3 lines of command as u said
> 
> ![image](https://user-images.githubusercontent.com/11426727/57941218-90ea2f80-78f8-11e9-96c1-419070f68b33.png)
> 
> ![image](https://user-images.githubusercontent.com/11426727/57940940-c4788a00-78f7-11e9-80a7-e7dfb38ff122.png)
> 
> ![working](https://user-images.githubusercontent.com/11426727/57941062-10c3ca00-78f8-11e9-9374-e73d35dff5ee.PNG)
> 
> ### but when i test it says => Error : Command failed
> ![image](https://user-images.githubusercontent.com/11426727/57941163-61d3be00-78f8-11e9-8e38-6da7d2c9321a.png)
> 
> ### But If i change my code from
> ` $pdf = new Pdf($sourceFile, ['command' => $pdftk_path, 'useExec' => true]);`
> **To**
> ` $pdf = new Pdf($sourceFile);`
> 
> ![image](https://user-images.githubusercontent.com/11426727/57941492-4b7a3200-78f9-11e9-8a3d-08037748181c.png)
> 
> ** Is there something missing from me**

I am currently struggling with the same issue as yours. Did you solve it?

**Comment by naduvko** [comment]
Missing arguments doesn't mean that it works actually.
Try it with real form and check the results.

**Comment by markfoodyburton** [comment]
Struggling with this.
I've generated a form using latex - the form is (as predicted) being filled using a helvetica font. I'm trying to place a €.

I have exactly the same issue as the OP. (If I 'click' on the field (e.g. without the pdf being flattened) then 'as if by magic' the character is there). - It does look, as several have said, that there is missing font info - it seems the € sign makes it into the PDF.

[An interesting aside: I used PDFtk to uncompress the result, and discovered that the character is entirely missing from the output (it's replace by a single byte (00)). I am guessing/hoping this is an issue with PDFtk uncompress.]

I have also tried (on the compressed output from php_pdftk of course)
```
gs  -o foo.pdf -sDEVICE=pdfwrite -dEmbedAllFonts=true  invoice.pdf 
GPL Ghostscript 9.27 (2019-04-04)
Copyright (C) 2018 Artifex Software, Inc.  All rights reserved.
This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:
see the file COPYING for details.
Processing pages 1 through 1.
Page 1
Loading NimbusSans-Regular font from /usr/share/ghostscript/9.27/Resource/Font/NimbusSans-Regular... 5177104 3564991 2760272 1363212 3 done.
```
Net result, the previously un-flattened pdf is now flattened (a good thing), and uses a better font for the filled-in text (good), but still no € sign.

Any other ideas?

**Comment by markfoodyburton** [comment]
For me, I now have it working reliably :

To be clear, I am using Latex and hyperref to generate my form. I happen to be on an apple. If I open the resulting form in Preview I can click on the elements and fill them in.

Simply by clicking and filling _ALL_ elements, then the form works, and "special" characters such as € can be automatically filled in. ALL the pre-filled data will be deleted when the form is filled (even if there is nothing to fill).

Note - a field that is used more than once has to be filled in _ALL_ the places it's used (even if that means adding some extra characters or whatever).

I have given up trying to understand why, but it worked for me - your millage WILL vary !
