### ISSUE TITLE
Merging and filling multiple documents

### ISSUE THREAD

**Issue by aa411853** [mikehaertl/php-pdftk#40]
I'm working on a package of loan documents.  I've got 7 different PDFs to merge, fill, and send to user's browser.

If I try to run fillForm() on a merged document I get the not an acroform error.  However the function works fine on all the documents individually.

Here's what I've got currently:

            $package = new Pdf();
            foreach ($forms as $key => $description) {
                $package->addFile('pdfTemplates/deals/' . $key . '.pdf');
            }

            $mergedPackage = new Pdf($package);
            $mergedPackage->fillForm($formVars)
                //->needAppearances()
                ->flatten()
                ->send('package');

Any ideas for a better workflow short of processing each form individually, and then merging at the end of the process?

**Comment by mikehaertl** [comment]
You didn't run a command on your `$package`. In your case you have to call `->cat(1,'end')` for each file you add. You also have to use aliases when you add the files. See here: https://github.com/mikehaertl/php-pdftk#cat

**Comment by aa411853** [comment]
Thanks!  I tried with this approach and was able to combine the files, but was still unable to fill in data with the combined file (received error 'not an acroform').  I ended up filling the forms individually, saving to a folder and then combining all the files at the end separately.

**Comment by mikehaertl** [comment]
Yeah, pdftk is really far from perfect. You could also try to add `->dropXfa()` on the combined file first. Maybe there's still a XFA form in the PDF (the newer form format), that pdftk doesn't like.
