### ISSUE TITLE
Pdftk not found

### ISSUE THREAD

**Issue by emaguana** [mikehaertl/php-pdftk#45]
I have the same error. I updated laravel 5 to 5.1 and now I get:sh: pdftk: command not found
Help me!

**Comment by mikehaertl** [comment]
Did you configure the path to your `pdftk` binary as discussed in the other issue #34?

**Comment by emaguana** [comment]
Thanks for the quick reply!. But where I find binary ? In the Vendor folder or necessarily you have to be in a folder on the server with an executable ?
Thank you

**Comment by mikehaertl** [comment]
Please note the second bold line of the README:

> **The pdftk command must be installed and working on your system.**

So you have to install `pdftk` on you system and tell this library, where to find it.
