### ISSUE TITLE
Warning: input PDF is not an acroform, so its fields were not filled.

### ISSUE THREAD

**Issue by Deno028** [mikehaertl/php-pdftk#47]
I got this message when I fillForm my Pdf file.

This is my code: 

 $pdf = new Pdf(self::PDF_TEMPLATE_PATH);
 $pdf->cat(1,1)
            ->fillForm(array('ABN'=>'Thanh Lam -  Doc 123','A6' => 'ABC','1A'=>'1A'))
            ->needAppearances()
            ->saveAs('../temp_upload_dir/_filled.pdf');

**Comment by mikehaertl** [comment]
Please see #39.
