### ISSUE TITLE
Compression not working

### ISSUE THREAD

**Issue by ladrua** [mikehaertl/php-pdftk#48]
I am calling the `->compress('compress')` on my object, but it does not seem to compress the file. Am I using it right, or do you have some more documentation about this option?

**Comment by mikehaertl** [comment]
Did you call `saveAs()` in the end? Also what does `echo (string) $pdf->getCommand()` give you?

**Comment by fr3nch13** [comment]
You've created such an amazing tool, it sucks that you have to deal with the developers that tl;dr, the docs and code, then have issues. :-/

**Comment by ladrua** [comment]
I did run saveAs, and it seems the compression was working, but the effect was so small I didn't notice. My 5.1MB file went down to 5MB. Thanks anyway. And very sorry this issue rubbed you the wrong way @fr3nch13

**Comment by fr3nch13** [comment]
All good. I've been following his project for a while, and most of his attention has gone to people just didn't pay attention. :-p
It's better placed elsewhere.
