### ISSUE TITLE
Installation/Configuration

### ISSUE THREAD

**Issue by eagle2097** [mikehaertl/php-pdftk#5]
First off, I am really grateful for your work on php-pdftk.  I searched all over for the right software for my project and this seems to really fit the bill perfectly.  You've implemented all the necessary functions of pdftk that I need and more.  Excellent work!

I'm starting off with some testing and I was wondering if there was further documentation regarding installation and configuration of the source codes.  In particular, are there specific configurations necessary for each server's pdftk installation?  I'm also not completely literate on the subject of aliases.  What would be helpful for me is a quick paragraph about how to implement a quick test of the codes on a shared web server environment to ensure everything is working correctly.  I noticed there is a CommandTest.php and PdfTest.php file, but I'm not sure how to use those.

What I've done so far is copy the Command.php, FdfFile.php, and Pdf.php to a working directory along with my other test files.  However, I'm not exactly sure how to configure the "use" function.

**Comment by jotasprout** [comment]
Thank you so much, @EddyRespondek, for those instructions! They don't seem cumbersome at all and I'm very grateful because I didn't think "use composer" was "really straightforward."

**Comment by rudddy** [comment]
Hello
How to install pdftk? it is not in composer
