### ISSUE TITLE
PDF not being saved, no error output

### ISSUE THREAD

**Issue by mikerockett** [mikehaertl/php-pdftk#50]
I'm using Laravel to encrypt/protect a PDF created by Snappy (wkhtmltopdf wrapper). Unfortunately, however, the secured PDF is not being created, nor am I able to stream it to the browser. `pdftk` is available on my path.

Here's a segment of my code - could I perhaps be doing something wrong?

```php
$router->get('snappy/{view?}', function($view = false) {
	// Return view if specified
	if ($view == true) return view('pdf-templates.snappy-test');

	// Create QR Code
	$qrc = new Endroid\QrCode\QrCode();
	$qrc->setText('http://<redacted>/docv/tr.test')
		->setSize(200)
		->setPadding(10)
		->setErrorCorrection('high')
		->setLabel('Scan to Verify Document')
		->setLabelFontSize(11)
		->save(public_path('assets.app/png/barcode-test.png'));

	// Create PDF
	$pdf = PDF::loadView('pdf-templates.snappy')
		->setPaper('a4');
	$pdf->save(storage_path('tests/snappy.pdf'), true);

	// Secure PDF
	$pdfs = new mikehaertl\pdftk\Pdf(storage_path('tests/snappy.pdf'));
	$pdfs->setPassword('test')
		->passwordEncryption(128)
		->saveAs(storage_path('tests/snappy_s.pdf'));
});

```

**Comment by mikerockett** [comment]
Right, figured that out quickly enough. Changing `command` and `useExec` did it. Any reason as to why there was no error output?

**Comment by mikehaertl** [comment]
You should check the return value of `saveAs()`. If it's `false` you can get the error from `getError()`. I should add an example to the README.md.

**Comment by mikerockett** [comment]
Interestingly, if I revert and take `command` and `useExec` out of the equation, adding a `getError` check, it seems to work, so now I'll never know what the problem was. That said, I have changed output paths - that could have been the issue (but I don't see how).

Going to close this for now. Thanks for pointing me in the right direction. :+1:
