### ISSUE TITLE
Error with generate file PDF

### ISSUE THREAD

**Issue by abhuanco** [mikehaertl/php-pdftk#54]
ErrorException in FdfFile.php line 59: mb_convert_encoding() expects parameter 1 to be string, array given

**Comment by mikehaertl** [comment]
Can you give a code example please? It seems you passed form data like this:

```
$data = [
    'field1' => 'some value'
    'field2' => ['x', 'y','z'], // this is not supported!
];
```

**Comment by abhuanco** [comment]
Oops if is correct.
$info = [
            'category' => [
                ...
                'image' => '...',
                'video'=>'...'
            ]
        ];
Now delete the sub lists and it works fine.

Thank you very much for your help.
