### ISSUE TITLE
Hierarchical data not supported

### ISSUE THREAD

**Issue by yuloh** [mikehaertl/php-pdftk#55]
It's possible to have nested data in an XFDF file, like explained [here](https://partners.adobe.com/public/developer/en/xml/XFDF_Spec_3.0.pdf).

These array keys:

```
Address.Name
Address.Street
Address.CityState 
```

Should return this XFDF:

``` xml
<fields>
 <field name="Address">
   <field name="Name">
     <value>Adobe Systems, Inc.</value>
   </field>
   <field name="Street">
     <value>345 Park Ave.</value>
   </field>
   <field name="CityState">
     <value>San Jose, CA 95110</value>
   </field>
<fields> 
```

I'm pretty sure this is what /Kids are used for in #29, since my hierarchical form data uses /Kids if represented as XDF.

**Comment by mikehaertl** [comment]
@yuloh Sounds useful. I've done a quick implementation on master. Maybe you could help test this?

**Comment by yuloh** [comment]
I pulled master and I've been testing it.  it works on some input but not all.  Here is an example of what causes it to fail:

```php
$xfdf = new mikehaertl\pdftk\XfdfFile(['name2.0' => 'Matt', 'Age4.0.1', '26']);
 $xfdf->saveAs('ex.xfdf')
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<xfdf xmlns="http://ns.adobe.com/xfdf/" xml:space="preserve">
    <fields>
        <field name="name2">
            <field name="0">
                <value>Matt</value>
            </field>
        </field>
        <field name="0">
            <value>Age4.0.1</value>
        </field>
        <field name="1">
            <value>26</value>
        </field>
    </fields>
</xfdf>
```

**Comment by mikehaertl** [comment]
Well, how should we know, if `Age4.0.1` is a nested field or a valid input name? I assume, that dots are not allowed in PDF fields names. Would you agree? I couldn't find anything in the document you posted.

**Comment by mikehaertl** [comment]
@yuloh I also think, your data is invalid. You need to have an associated array of keys/values. But you have a simple list here: `..., 'Age4.0.1', '26']`.

**Comment by yuloh** [comment]
Whoops, just realized I had a `,` instead of a `=>` in my input array.  Disregard my previous comment, it's working great.

Yeah, I'm pretty sure dots are not allowed as field names and always mean it's nested input.

**Comment by mikehaertl** [comment]
Released 0.3.1 with this update. Thanks for your help!

**Comment by mikehaertl** [comment]
@yuloh As you see from #64 this change now makes problems if we have field names like `1.1.0`. After some thinking I wonder if we really need to support dot notation at all. Why can't we simply pass the data as nested array:

```
$data = [
    'Address' => [
        'Name' => 'Peter',
        'Street' => ...
]
```

What do you think?

**Comment by yuloh** [comment]
Hello,

I'm pretty sure the dot notation is standard for representing nested fields. Iirc that is what pdftk outputs too.

[This Adobe document discusses it](https://www.google.com/url?sa=t&source=web&rct=j&url=http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/naming.pdf&ved=0ahUKEwilrN_f2IzRAhXHPiYKHR-ICRoQFggzMAM&usg=AFQjCNFSif8nkcF366lJr9rMU-GeGReZEA&sig2=i5I0eAaJKN30IUqu9y4_mA). I will try and find a more official reference. 

Maybe Adobe uses a standard escaping format?

**Comment by mikehaertl** [comment]
@vielhuber It really seems, that dots in PDF form field names are reserved for nested fields. So I'm not sure, if it's a good idea to name your fields like `1.2.3`. On the other hand I'm not sure, why we really need to also use dot notation on the PHP side of things. Here a nested array would be the much better representation of such data. 

@yuloh Do you have a use case, why you also need dotted names in the PHP array? Why can't we simply use an array like shown above? It would still create exactly the same Xfdf file.

**Comment by yuloh** [comment]
I found this in the [ PDF spec:](http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf)

> For a field that is the child of another field, the fully qualified name is 
formed by appending the child field’s partial name to the parent’s fully qualified 
name, separated by a period (.): 
parent’s_full_name.child’s_partial_name
For example, if a field with the partial field name PersonalData has a child whose 
partial name is Address, which in turn has a child with the partial name ZipCode, 
the fully qualified name of this last field is 
PersonalData.Address.ZipCode

> 116. Beginning in Acrobat 3.0, partial field names cannot contain a period.

So it sounds like the period is reserved and shouldn't be used field names.
