### ISSUE TITLE
Get number of pages in PDF

### ISSUE THREAD

**Issue by chadpriddle** [mikehaertl/php-pdftk#56]
I read in another issue that there is NumberOfPages? But I can't find it in the source

```
   	$pdf = new Pdf('pdf/inspection.pdf');
	$total_pages = $pdf->getData()->NumberOfPages();

        echo $total_pages;
```

Is this possible? I dumped the $pdf->getData() and see the NumberOfPages string but how do i extract it a single variable?

**Comment by mikehaertl** [comment]
There's no dedicated method. You could use `preg_match()`. It's really beyond the scope of this library but something like this should work:

```
$data = $pdf->getData();
if (preg_match('/NumberOfPages: (\d+)/', $data, $m)) {
    $number = $m[1];
}
```

**Comment by demotascha** [comment]
@mikehaertl Thanks.
