### ISSUE TITLE
Not generate the PDF file and no warnings

### ISSUE THREAD

**Issue by elysiopires** [mikehaertl/php-pdftk#59]
Hello Mike!

Before anything, congrats for your grate work with php-pdftk.

I'm trying to combine two pdf files. But the script runs with laravel 5.1 and doesn't show any error or warning. I installed the pdftk_server-2.02-mac_osx-10.6-setup package for macOS and test the command on terminal and works fine.

Here is my piece of code:
$pdfMerge = new Pdf;
        $pdfMerge->addFile(base_path('storage/app').'/doc1.pdf', 'A');
        $pdfMerge->addFile(base_path('storage/app').'/'.$folder.'/imgapostila.pdf', 'B');
        $pdfMerge->cat(1, 'end', 'A')                // pages 1-5 from A
        ->cat(1, 'ed', 'B')             // pages 2,3 and 7 from C
        ->saveAs(base_path('storage/app').'/'.$folder.'/apostila.pdf');

Could you help me?

Thx,
Elysio Pires

**Comment by mikehaertl** [comment]
What does `saveAs()` return and is there an error afterwards in `$pdfMerge->getError()`?

**Comment by elysiopires** [comment]
Hello Mike!

Sorry for the late reply, after many tries I discover that first was the problem with finding the executable and then the version pdftk_server-2.02-mac_osx-10.6-setup doesn't work fine with MacOS El capitan so I have to install the version pdftk_server-2.02-mac_osx-10.11-setup and everything goes ok!

As an advice, you could edit the readme to show this information about how to see the errors.

Thank you for your attention and the package, this is really nice and preserve all features of the pdf!

Sincerely,
Elysio Pires

**Comment by mikehaertl** [comment]
> As an advice, you could edit the readme to show this information about how to see the errors.

That already happened ;).
