### ISSUE TITLE
Can not set the same password on setPassword and setUserPassword

### ISSUE THREAD

**Issue by iCodr8** [mikehaertl/php-pdftk#60]
```
$password = 'blabla1!';
$pdf = new Pdf('source.pdf');
$pdf->setPassword($password);
$pdf->setUserPassword($password);
$pdf->saveAs(encrypted.pdf);
```

It is not possible to set the same password on ```setPassword()``` and ```setUserPassword()```. if it is the same, the generation will fail. But why?

**Comment by mikehaertl** [comment]
Does it work on the command line with `pdftk`? Remember that this library is just a wrapper. If something doesn't work with "raw" pdftk it will also not work here.

**Comment by mikehaertl** [comment]
Closing this as there was no further feedback.
