### ISSUE TITLE
Laravel 5.2 * Call to undefined method mikehaertl\pdftk\Pdf::isDeffered()

### ISSUE THREAD

**Issue by NenadDomuz** [mikehaertl/php-pdftk#61]
This basic code generates the error
It could be I'm missing something

```
$pdf = new Pdf($file, [
            "command" => "/usr/bin/pdftk",
            "useExec" => true
        ]);

        $pdf->fillForm(array(
            "Date" => "TEST"  // form field inside the pdf is called Date
        ))
            ->needAppearances()
            ->saveAs("new.pdf");
```

**Comment by mikehaertl** [comment]
This method is not called anywhere in our code. So the problem must be in other parts of your code or Laravel.

**Comment by NenadDomuz** [comment]
That's what I missed, thanks for pointing that out, 
The error actually points to Laravel method which checks if the provider is deferred.

Even after creating the deferred service provider, my application stalls -> **port state:** CLOSE_WAIT  

I guess I have to do more in-depth debugging, do you have any suggestions maybe ?

**Comment by mikehaertl** [comment]
Sorry, not really. I'd `grep` or google for that `isDeffered()` call. Maybe something in Laravels autoloader (if it has any).
