### ISSUE TITLE
Generating base64

### ISSUE THREAD

**Issue by kendrickkesley** [mikehaertl/php-pdftk#63]
Hi can this libray generate base64 for the pdf? because I don't want to save it in the server, just generate and pass it through ajax call

Thanks!

**Comment by mikehaertl** [comment]
There's always a temporary file created on the server which will be removed automatically if you don't save it. You can access it via `$pdf->getTmpFile()`. It's an instance of this class here: https://github.com/mikehaertl/php-tmpfile

You can use it to create the base64.

**Comment by sentiasa** [comment]
@mikehaertl - Can you please give an example for this?

I tried 

```
$path = $pdf->getTmpFile()->getFileName(); // returns "/tmp/tmp_php_pdftk_JgwtED.pdf"
```

But if I try `file_get_contents($path)` on it, it returns `""`
