### ISSUE TITLE
Fields with "." inside

### ISSUE THREAD

**Issue by vielhuber** [mikehaertl/php-pdftk#64]
Hello!

I have several hundreds fields with names like:

1.1
1.1.1
1.1.2
...

pdftk seems to have problems here and can't fill them (they are empty).

The reason for this is the following code part in src/XfdfFile.php:
` 

           // Key can be in dot notation like 'Address.name'

            $keys = explode('.', $sanitizedKey);
            $final = array_pop($keys);
            if (count($keys)===0) {
                $fields[$final] = $sanitizedValue;
            } else {
                $target =& $fields;
                foreach ($keys as $part) {
                    if (!isset($target[$part])) {
                        $target[$part] = array();
                    }
                    $target =& $target[$part];
                }
                $target[$final] = $sanitizedValue;
            }
`

Is the only solution for me to change all of those hunderds of field names to e.g. "1,1,1" (with comma) or is there another solution?

Thanks in advance!

**Comment by mikehaertl** [comment]
Hmm, this is an impact of #55. I'm not sure, what's a good way to solve this. We could add another constructor parameter like `$separator = '.'`. But the constructor signature is already quite bloated so I'd prefer if we could avoid it.

On the other hand, the only other solution that comes to mind is to use a static class property like:

```
public static $fieldSeparator = '.';
```

So you could do:

```
XfdfFile::$fieldSeparator = '|';
$xfdf = new XfdfFile(...);
```

Not really nice, either. Any suggestions?

**Comment by vielhuber** [comment]
```
$pdf = new Pdf('form.pdf');
$pdf->disableHierarchicalData(); // add this
$pdf->fillForm(array('1.2.3'=>'works'))->flatten()->saveAs('filled.pdf');
```

**Comment by mikehaertl** [comment]
@vielhuber I've reopened #55. Maybe we reconsider the way we implemented support for nested data. Instead of dot notation we could simply pass an array. Waiting for some feedback from @yuloh there, who requested this feature.

**Comment by yuloh** [comment]
Where are the fields names coming from?  Are these generated by Acrobat?

**Comment by mikehaertl** [comment]
@vielhuber As discussed in #55 it really seems like dot names are not allowed, because if you have `1.1.1` as a field name, you can't use `1.1`, as this is then the "group" name. So it would probably not even work if we remove this feature. But maybe you can verify this by commenting out the problematic section in our code.

**Comment by vielhuber** [comment]
@mikehaertl I'm sorry, you are right. The names are not as mentionned 1 and 1.1 and 1.1.1 but 1.1, 1.2, 1.3, ... it seems that this works only because the other cases didn't happen.

So it seems that you can close this issue.

Do you know how to mass rename the fields inside a pdf? I have several thousands of them and this will be a real pain. I will perhaps use for the new labels "1,1" or "1*1" or some other separator.

**Comment by mikehaertl** [comment]
> Do you know how to mass rename fields inside a pdf?

Sorry, no idea. Good luck!

**Comment by vielhuber** [comment]
Follow up: Here is a small script to bulk rename field names:
https://vielhuber.de/blog/pdf-formularfelder-massenweise-umbenennen/
