### ISSUE TITLE
Highlighted inputs

### ISSUE THREAD

**Issue by Cosmologist** [mikehaertl/php-pdftk#65]
Have problem with this pdf. I successfully fill the form, but when i open it with reader (chrome, foxit reader, acrobat reader) the input not filled - when focus in the input then then text showed, when i remove focus then text hiding. If i add any symbol to the input (space, for example) - input value showed correctly.
[test.pdf](https://github.com/mikehaertl/php-pdftk/files/754587/test.pdf)

**Comment by mikehaertl** [comment]
Please check this section of the README: https://github.com/mikehaertl/php-pdftk#fill-form

You may have to set `needAppearances()` on the PDF. I can not really give you more support here as this is a limitation of pdftk itself. You can also search the issues here for "utf". We already discussed this several times and there may be other workarounds.
