### ISSUE TITLE
Problem with needAppearances

### ISSUE THREAD

**Issue by David91vlc** [mikehaertl/php-pdftk#66]
Hello, I Have a problem using needAppearances.

I try with this code:

```
		$dirPdf = public_path().'/uploads/PDFBase/SOLICITUD_PRUEBAS_APTITUD.Mod.04.pdf';
		
		$pdf = new Pdf($dirPdf);
		$pdf->fillForm(array(
			"DNINIE" => "12345678X"
			))
		->needAppearances()
		->send();
```
But when I use needAppearances the page shows this error:

> Error: Unexpected data in output section: need_appearances Exiting. Errors encountered. No output created. Done. Input errors, so no output created.

If i remove needAppearances, the browser shows the document. I Tried with saveAs instead of send, but the result is same.

Any suggestion?

Thanks

**Comment by mikehaertl** [comment]
Please check the man page (`man pdftk`) of pdftk if it supports this option. Maybe you have to update to a later version if it doesn't.

**Comment by David91vlc** [comment]
In man pdftk i don't find any information for needAppearances. 

I installed yesterday typing: 

> apt-get install libstdc++
> apt-get install libapt-pkg

Afther that I type in my laravel project this:
> php composer require mikehaertl/php-pdftk

This is the steps I realized. How to upgrade the version?

Thanks

**Comment by mikehaertl** [comment]
Sorry, I can not help you with upgrading pdftk. Please simply google this for you operating system, I'm sure you'll find it out. You should look for version 2.x of pdftk.

**Comment by David91vlc** [comment]
Hi, Mike, thanks for your reply.

I updated the pdftk to version 2.02. Now, when I use the needAppearances not show error but no display the special characters well. 

![image](https://cloud.githubusercontent.com/assets/6285379/22736600/2cbae7b0-edff-11e6-855f-b8aebca142bc.png)

I type "caña" but show it.

Any idea?

Thanks

**Comment by mikehaertl** [comment]
Probably a font issue. Make sure, that the font in that input field supports that character. If that doesn't help, I don't know either. Maybe try with a fresh PDF first or try another tool to create/edit your PDF forms.

Maybe also check #4 where we had a lengthy discussion about similar issues. #53 also has some interesting details about PDF internals. 

Personally I'm able to use UTF-8 characters in my PDF forms, so I know that it works if the PDF form is set up correctly.
