### ISSUE TITLE
Problem with special characters (Other issue is closed)

### ISSUE THREAD

**Issue by David91vlc** [mikehaertl/php-pdftk#67]
Hi, Mike, thanks for your reply.

I updated the pdftk to version 2.02. Now, when I use the needAppearances not show error but no display the special characters well.

![image](https://cloud.githubusercontent.com/assets/6285379/22736932/20eca4b2-ee01-11e6-93d8-5b35b98cb3a4.png)

I type "caña" but show it.

Any idea?

Thanks

**Comment by mikehaertl** [comment]
See comment in #66. Closing this as it's not an issue we can fix here.
