### ISSUE TITLE
 sometimes it is unable to generate pdf

### ISSUE THREAD

**Issue by skyinsurance** [mikehaertl/php-pdftk#68]
sometimes it is unable to generate pdf and it returns an error
mikehaertl\pdftk\Pdf Object ( [ignoreWarnings] =>false)
here is my code

$pdf = new Pdf ( $filepath,['command' => '/usr/local/bin/pdftk','useExec' => true,]);
$pdf->fillForm ( $arr_full_data )->compress()->flatten()->saveAs ( $save_file );

Please let me know is there any problem in it

**Comment by chodges** [comment]
Yes I'm having the same issue

**Comment by mikehaertl** [comment]
> ... and it returns an error

And what is the error?

**Comment by skyinsurance** [comment]
we are getting this error

{"ignoreWarnings":true};

thanks



*Thank you,*

*Sampath Narayanan*
*88 <813-999-2152>8-663-6503 ext 1011*
*sampath@skyinsurancetech.com <sampath@skyinsurancetech.com>*

*Sky **Insurance Technologies*
www.skyinsurancetech.com

* <http://skyinsurancetech.com/aca-reporting/>*
*Want to see our ACA Reporting Packages?
<http://skyinsurancetech.com/aca-reporting/>  *

CONFIDENTIALITY STATEMENT: This message is intended for the use of the
person or entity to which it is addressed and may contain information that
is privileged and confidential, the disclosure of which is governed by
applicable law. If you are not the intended recipient, or the employee or
agent responsible to deliver it to the intended recipient, you are hereby
notified that any disclosure, copying or distribution of this information
is STRICTLY PROHIBITED. If you have received this message by error, please
notify the sender immediately to arrange for return or destruction of these
documents.

CONFIDENTIAL HEALTH INFORMATION: Protected Health Information is personal
and sensitive information related to a person's health care. If Protected
Health Information is being e-mailed or faxed to you, it is being e-mailed
or faxed to you after appropriate authorization from the patient or under
circumstances that do not require patient authorization. You as the
recipient are obligated to maintain it in a safe, secure and confidential
manner. Re-disclosure without additional patient authorization or as
permitted by law is prohibited. Unauthorized re-disclosure or failure to
maintain confidentiality could subject you to penalties under federal and
state law

**Comment by mikehaertl** [comment]
Hmm, I can't really follow. Where does this message appear? What you pasted does not look like an error message but rather a var dump or something. Our code does not generate this.

You should check for errors with `$pdf->getError()`.

**Comment by skyinsurance** [comment]
Thanks for the input.. We were able to figure out the issue... We were
using a variable wrongly...


One more question, While generating large number of pdf files and
compressing them ( files > 1000) , our CPU spikes to 30% . we have 5 CPU's
and 8 GB of Ram, I see spike only in the CPU Usage and not RAM. Is there
any setting or something which can reduce CPU Spike ?

thanks
sampath

*Thank you,*

*Sampath Narayanan*
*88 <813-999-2152>8-663-6503 ext 1011*
*sampath@skyinsurancetech.com <sampath@skyinsurancetech.com>*

*Sky **Insurance Technologies*
www.skyinsurancetech.com

* <http://skyinsurancetech.com/aca-reporting/>*
*Want to see our ACA Reporting Packages?
<http://skyinsurancetech.com/aca-reporting/>  *

CONFIDENTIALITY STATEMENT: This message is intended for the use of the
person or entity to which it is addressed and may contain information that
is privileged and confidential, the disclosure of which is governed by
applicable law. If you are not the intended recipient, or the employee or
agent responsible to deliver it to the intended recipient, you are hereby
notified that any disclosure, copying or distribution of this information
is STRICTLY PROHIBITED. If you have received this message by error, please
notify the sender immediately to arrange for return or destruction of these
documents.

CONFIDENTIAL HEALTH INFORMATION: Protected Health Information is personal
and sensitive information related to a person's health care. If Protected
Health Information is being e-mailed or faxed to you, it is being e-mailed
or faxed to you after appropriate authorization from the patient or under
circumstances that do not require patient authorization. You as the
recipient are obligated to maintain it in a safe, secure and confidential
manner. Re-disclosure without additional patient authorization or as
permitted by law is prohibited. Unauthorized re-disclosure or failure to
maintain confidentiality could subject you to penalties under federal and
state law

**Comment by mikehaertl** [comment]
Sorry, I can not help you with performance questions. This library just executes pdftk. If it uses too much CPU, we can't do anything about it.
