### ISSUE TITLE
saveAs issue

### ISSUE THREAD

**Issue by anthonyPlexuss** [mikehaertl/php-pdftk#69]
Hi there,

I'm using laravel framework and I have an issue with saveAs or send functionality. 

First of all, I couldn't find out what I need to pass to set the directory I want the temporary file to be saved. I went ahead inside of XfdFile.php, and File.php, and harcoded the path I want the temprary file to be saved in.

the xfdf files get saved, but the problem is that pdf file is not getting saved, and I get no error, and the page just keeps loading forever.

After debugging files, it seems like the method that is failing is the following, 
Pdf.php ==> execute method => !$command->execute($filename)

```
public function execute()
    {
        $command = $this->getCommand();
        if ($command->getExecuted()) {
            return false;
        }
        if ($this->_output===false) {
            $filename = null;
        } else {
            $filename = $this->_output ? $this->_output : (string) $this->getTmpFile();
        }
        if (!$command->execute($filename)) { // THIS IS WERE CODE GETS STUCKED.
            $this->_error = $command->getError();
            if ($filename && !(file_exists($filename) && filesize($filename)!==0 && $this->ignoreWarnings)) {
                return false;
            }
        }
        return true;
    }
```

Here's my code:
```
$pdf = new Pdf(storage_path(). '/pdfFiles/form.pdf', [
	        'command' => '/usr/local/bin/pdftk',
    	]);
		// $data = $pdf->getDataFields();
		$pdf->fillForm(array(
	        'name'=>'anthony',
	        'email' => 'a@a.com',
	    ))
	    ->saveAs(public_path().'/filled.pdf');
```

I appreciate everyone's time, I hope to get an answer on what I am doing wrong.

**Comment by mikehaertl** [comment]
> First of all, I couldn't find out what I need to pass to set the directory I want the temporary file to be saved

It should use PHP's temp dir, see http://php.net/manual/en/function.sys-get-temp-dir.php. We didn't add this as another option to `fillForm()` as the signature is already quite lengthy and the tmp dir should work fine usually. If this doesn't work for you, I'd rather try to fix this in the PHP settings.

For your actual problem: Hmm, that's hard to tell from the information you provided. You could maybe first try to paste the command string and try it manually on the command line:

```
echo $pdf->getCommand()->getExecCommand();
```

You have to create your FDF file first as the tmp file from the command string is probably gone.
