### ISSUE TITLE
Combining Multiple PDF Files

### ISSUE THREAD

**Issue by sentiasa** [mikehaertl/php-pdftk#71]
Hi, I am trying to make 1 pdf out of multiple pdfs. I have all my pdfs in an array however I couldn't figure out how to combine them into one.
```
$pdfFiles = ['a.pdf', 'b.pdf', 'c.pdf']

$pdf = new Pdf($dir. '/Combined.pdf');

foreach ($pdfFiles as $form) {
        $pdf->
      // I am stuck here
}
```
How can I perform this task? I just want to take all pages of all pdfs and have one combined pdf; however I couldn't figure it out from the documentation.  Thanks in advance

**Comment by mikehaertl** [comment]
Please check https://github.com/mikehaertl/php-pdftk#cat. 

I'm closing this as this is not an issue report.

**Comment by mohitbirpankar** [comment]
we are using mikehaertl for generating pdf's and we want to combine multiple pdf into a single pdf. we have tried the solution mentioned in https://github.com/mikehaertl/php-pdftk#cat. But it didn't work

$pdf = new Pdf('/path/to/my.pdf');
$result = $pdf->cat(1, 5)
    ->cat([7, 4, 9])
    ->saveAs('/path/to/new.pdf');
if ($result === false) {
    $error = $pdf->getError();
}

above is generating error 
Error: Unable to find file.
Error: Failed to open PDF file:

could you please help?
