### ISSUE TITLE
total number of files for cat

### ISSUE THREAD

**Issue by rps-repo** [mikehaertl/php-pdftk#74]
I am trying to combine many single page PDF files into a single file.
Am I understanding correctly that when adding files for cat I am limited to a total of 26 files (A thru Z)?

**Comment by mikehaertl** [comment]
Sorry, this is not a support forum. Please check the man page of `pdftk` for questions like these.

**Comment by rps-repo** [comment]
This isn't a support request for pdftk.  With pdftk I can simply do

```
                $files = 'pdf1.pdf pdf2.pdf pdf3.pdf';
                exec('pdftk ' . $files . ' cat output combined.pdf');
```
I am not interested in extracting any pages or adding any options.  I just want to combine files as is.
Can this be done with your library when combining a large number of files?

**Comment by mikehaertl** [comment]
`cat` without a page range is not supported by this extension, but `cat(1, 'end', 'AA')` should give you the same result. And AFAIK pdftk > V 2 supports 2 letter handles. Again, please check the pdftk man page for details.
