### ISSUE TITLE
Duplicate pdf and fill data and append

### ISSUE THREAD

**Issue by t-pankajkumar** [mikehaertl/php-pdftk#75]
Hi,
I was stuck at a case,
I have a PDF file with two pages, and i have 10 employees,
All i want is to fill data of 1st employee in two pages then append the 2 pages again and fill 2nd employee data and so on ...
then generate into a single PDF.
is it possible?
Thank you.

**Comment by mikehaertl** [comment]
Sorry, this is not a support forum, but for bug reports only. We don't provide support for specific use cases. Please consult the documentation.

**Comment by simonberger** [comment]
Actually this is a missing feature. You can't concatenate different PDFs and fill form data in one go.
I would like to know if this is a limitation of this package or one from pdftk.
Something like the following would be awesome or just form data operating on the combined pdfs.
```
->formData([
   'fileAlias1' => [
      'firstname' => 'Max'
   ],
   'fileAlias2' => [
      'firstname' => 'Erika'
   ]
]
```

**Comment by mikehaertl** [comment]
> Found that it seems to be a limitation on commandline side :(

Exactly. It's alwasy only one operation per `pdftk` call. While it would be theoretically possible, to have multiple calls to `pdftk` I wanted to avoid this, as this increases complexity quite a bit and makes everything very error prone.

You can still perform multiple operation by piping a Pdf object into a new instance which basically gives you the same result: https://github.com/mikehaertl/php-pdftk#how-to-perform-more-than-one-operation-on-a-pdf
