### ISSUE TITLE
Issue with multiline fields in PDF

### ISSUE THREAD

**Issue by ggavrilut** [mikehaertl/php-pdftk#76]
Hello,

First of all, very nice bundle.

When the input is a pdf that contains multiline fields, I have an error with the $parts variable in DataFields.php on line 92 (no index 1). That is because the $line only contains the value and not the key.

I implemented the following fix, on line 91:

            if (sizeof($parts) === 0 && !empty($key) && empty($value)) {
                $value = $key;
                $key = 'FieldValue';
            }
Are you interested in this?

**Comment by mikehaertl** [comment]
@bravadomizzou Any thoughts on this?

**Comment by bravadomizzou** [comment]
Can you provide an example of the raw string returned by `$pdf->getDataFields()`?

**Comment by ggavrilut** [comment]
So the error (Notice: Undefined offset: 1) is here
            $value = $value ?: trim($parts[1]);

This is the dataString: 
--- FieldType: Text FieldName: adresse FieldFlags: 33558528 FieldValue: 8 Avenue du Stade De France 93218 LA PLAINE SAINT DENIS CEDEX FieldJustification: Left FieldStyleDefault: font: Cambay,sans-serif 10.0pt; text-align:left; color:#000000 ---

and somehow when it explodes after PHP_EOL, maybe because there is a new line between France and 93218, the field value is on two lines, and this generates the error.

**Comment by mikehaertl** [comment]
@allforme3 As said before I've now refactored the data dump class. There still were some issues e.g. if a text value contained a line with `---`. I tried to fix this now, too. Maybe you could help testing and see if the latest version from master works for you?

**Comment by allforme3** [comment]
Hello,

Just ran this testing a few PDF documents for example:
`---
FieldType: Text
FieldName: 1
FieldFlags: 12582912
FieldValue: DN100
FieldJustification: Left
---
FieldType: Text
FieldName: 2
FieldFlags: 12582912
FieldValue: 34, Exeter, DE11 0SD
FieldJustification: Left
---
FieldType: Text
FieldName: 3
FieldFlags: 12582912
FieldJustification: Left
---
FieldType: Text
FieldName: 4
FieldFlags: 12582912
FieldJustification: Left
---
FieldType: Text
FieldName: 5
FieldFlags: 12582912
FieldValue: 
FieldJustification: Left
---
FieldType: Text
FieldName: 6
FieldFlags: 12582912
FieldValue: 
FieldJustification: Left
---
FieldType: Text
FieldName: 7
FieldFlags: 12582912
FieldValue: 
FieldJustification: Left
---
FieldType: Text
FieldName: 8
FieldFlags: 12582912
FieldValue: 
FieldJustification: Left
---
FieldType: Text
FieldName: 9
FieldFlags: 12582912
FieldValue: 
FieldJustification: Left
---
FieldType: Text
FieldName: 10
FieldFlags: 12582912
FieldValue: 
FieldJustification: Left
---
FieldType: Text
FieldName: 11
FieldFlags: 12582912
FieldValue: 
FieldJustification: Left
---
FieldType: Text
FieldName: 12
FieldFlags: 12582912
FieldValue: 
FieldJustification: Left
---
FieldType: Text
FieldName: 13
FieldFlags: 12587008
FieldValue: 
FieldJustification: Left
---
FieldType: Button
FieldName: 14
FieldFlags: 0
FieldJustification: Left
FieldStateOption: Off
FieldStateOption: Yes
---
FieldType: Text
FieldName: 15
FieldFlags: 12582912
FieldValue: 
FieldJustification: Left
---
FieldType: Button
FieldName: 16
FieldFlags: 0
FieldJustification: Left
FieldStateOption: Off
FieldStateOption: Yes
---
FieldType: Button
FieldName: 17
FieldFlags: 0
FieldJustification: Left
FieldStateOption: Off
FieldStateOption: Yes
---
FieldType: Text
FieldName: 18
FieldFlags: 12582912
FieldValue: 
FieldJustification: Left
---
FieldType: Button
FieldName: 19
FieldFlags: 0
FieldJustification: Left
FieldStateOption: Off
FieldStateOption: Yes
---
FieldType: Button
FieldName: 20
FieldFlags: 0
FieldJustification: Left
FieldStateOption: Off
FieldStateOption: Yes
---
FieldType: Text
FieldName: 21
FieldFlags: 12582912
FieldValue: 
FieldJustification: Left
---
FieldType: Button
FieldName: 22
FieldFlags: 0
FieldJustification: Left
FieldStateOption: Off
FieldStateOption: Yes
---
FieldType: Button
FieldName: 23
FieldFlags: 0
FieldJustification: Left
FieldStateOption: Off
FieldStateOption: Yes
---
FieldType: Button
FieldName: 24
FieldFlags: 0
FieldJustification: Left
FieldStateOption: Off
FieldStateOption: Yes
---
FieldType: Text
FieldName: 25
FieldFlags: 12587008
FieldValue: 
FieldJustification: Left
---
FieldType: Text
FieldName: 26
FieldFlags: 12587008
FieldValue: Test
---
Hello
Test
Test

Hello
FieldJustification: Left
---
FieldType: Text
FieldName: 27
FieldFlags: 12587008
FieldValue: 
FieldJustification: Left`

It worked perfectly thank you.

Allan

**Comment by mikehaertl** [comment]
Great, test cases also look good.

Just released 0.4.2 containing the fix.
