### ISSUE TITLE
working example of 'burst.php' 

### ISSUE THREAD

**Issue by Sinan81** [mikehaertl/php-pdftk#78]
Hi! I am an absolute beginner in php. I am wondering if you could provide a working example of one of your example scripts such as 'burst.php'. 

I have a working LAMP stack on a debian system and I also installed pdftk. I installed your plugin as:
`testuser@lamp ~$ composer require mikehaertl/php-pdftk
`
which created the followings:
```
testuser@lamp ~$ ls   
composer.json  composer.lock  vendor
```
I created the following 'burst.php' under /home/testuser where I also provided a sample .pdf document "my.pdf" document:
```
<html>
 <head>
  <title>PHP Test</title>
 </head>
 <body>
 <?php 
   echo '<p>Hello World</p>'; 
   use mikehaertl\pdftk\Pdf;
   $pdf = new Pdf('/home/testuser/my.pdf');
   $pdf->burst('/home/testuser/page_%d.pdf');
 ?>
</body>
</html>
```
I created a symbolic link to 'burst.php' under /var/www/  and when i run it as http://localhost/burst.php "Hello World' is displayed but the individual pages of 'my.pdf' are nowhere to be found.

Thanks for your help.

**Comment by mikehaertl** [comment]
Sorry, this is not a support forum and please understand that I can't help you with learning the basics.
