### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by florianbepunkt** [mikehaertl/php-pdftk#8]
Hey,

I'm sorry if this is a stupid question, but I can't see how to install this library.

I've successfully installed the PDFTk library on my server but if I want to use your script how do I embedd it?

Can you please give some details on how to include and basically use your script. Copying the code pieces you provided did not work for me.

use mikehaertl\pdftk\Pdf
What is this line for?

It doesn't sem to correspond with the file structure provided in the git

Thanks,
Florian

**Comment by sabian2008** [comment]
I'm sorry for this, but I'm not being able to make it work neither.

Everything I tried ends up with a Fatal error of Class not found at the very first couple of lines of the code (line 17 when I try to include Command.php, FdfFile.php or Pdf.php). It's a shame since this seems to be the perfect tool for a simple task I'm trying to accomplish: fill and e-mail certificates for attendants at a meeting.

This is what I'm using

<?php
include ('Pdf.php');
include ('Command.php');
include ('FdfFile.php');

use mikehaertl\pdftk\Pdf;

$pdf = new Pdf('test.pdf');

?>

I write this because besides helping myself (I could eventually use pdftk from the command line) it could potentially help other newbies like me.

Thanks in advance,

**Comment by mikehaertl** [comment]
Please use [composer](https://getcomposer.org/) for installation. You will never have to manually install or include a file. Composer does this for you. I can not give further support on how to use composer.

**Comment by sabian2008** [comment]
Thanks =)

**Comment by rey809** [comment]
Hello Sir can you give an example of splitting the single pdf with having multiple pages into multiple single pages? Thanks for advance sir :)

**Comment by teynon** [comment]
Per the documentation on the main Github repository: 

Burst
Split a PDF file into one file per page.
use mikehaertl\pdftk\Pdf;
$pdf = new Pdf('/path/my.pdf');
$pdf->burst('/path/page_%d.pdf');     // Supply a printf() pattern

**Comment by rey809** [comment]
Yes, but when I try that code it's working but only the last page of the pdf. example if my pdf contents 3 pages only page 3 selected.

**Comment by teynon** [comment]
I use it in my code and it works fine. So it's most likely something you are doing differently. My guess would be that you aren't using the %d in the file name.

`
        $pdf = new PDF(($relative) ? '../app/FileWork/' : '' . $fileName);
        $fields = [];
        // One page per file.
        $fileName = "../app/FileWork/tmpPdf_" . uniqid() . "_%d.pdf";
        $pdf->burst($fileName);
        
        for ($x = 1; $x <= $data['NumberOfPages']; $x++) {
            $file = sprintf($fileName, $x);
            $fields[] = $this->GetPDFDataFields($file, false);
            
            unlink($file);
        }`

**Comment by rey809** [comment]
Thanks, sir but the variable $relative, $fileName, $data, and function GetPDFDataFields not exist.

Here my code at the documentation.

<?php
 require_once('vendor/autoload.php');
use mikehaertl\pdftk\Pdf;

$pdf = new Pdf('TEST RUN.pdf');
$pdf->burst('page_'. uniqid() .'_%d.pdf');     // Supply a printf() pattern

?>

**Comment by shinechandran** [comment]
sir,
I am facing a problem, i am using ubuntu.. I am getting this error... i could not understand the actual problem.. pls if you can help me with this.... no problem with your code firstly.. just i am getting this error 

Uncaught exception #1: Warning: copy(/var/www/html/aggerenergie/Web/requestpdf/b388cb78-c970-4e44-5699-ae5ec20134fa-vertrag.pdf): failed to open stream: Permission denied in /var/www/html/aggerenergie/Packages/Libraries/mikehaertl/php-pdftk/src/Pdf.php line 499

87 TYPO3\Flow\Error\ErrorHandler::handleError(2, "copy(/var/www/html/aggerenergie/Web/requestpdf/b388cb78-c970-4e44-5699-ae5ec20134fa-vertrag.pdf): failed to open stream: Permission denied", "/var/www/html/aggerenergie/Packages/Libraries/mikehaertl/php-pdftk/src/Pdf.php", 499, array|2|)
86 copy("/tmp/tmp_php_pdftk_IG6iGz.pdf", "/var/www/html/aggerenergie/Web/requestpdf/b388cb78-c970-4e44-5699-ae5ec20134fa-vertrag.pdf") 

can you pls help me why this could happen.. what i am doing wrong..

**Comment by rudddy** [comment]
Hello

Can someone help me with the installation? In fact, this one with composing is fine, but in use I still miss the pdftk library... I don't know where to start on composer (they're all deprecated)

Thanks all
