### ISSUE TITLE
Explain "handles" in more detail

### ISSUE THREAD

**Issue by Niksac** [mikehaertl/php-pdftk#81]
I would suggest to explain handles in more detail.

I tried to use numeric and mixed identifiers and PDFTK will fail the task silently.
Only in the source code comments did i find requirements for what a handle can be:
`* @param string|null $handle one or more uppercase letters A..Z to reference this file later.`

I think this should be explained in the Readme and maybe the restricion should be added to all doc blocks.

**Comment by mikehaertl** [comment]
As this is only a wrapper for `pdftk` we will not copy the full documentation of that tool. If in doubt you should always consult the `pdftk` man page where handles are explained.
