### ISSUE TITLE
keep getting "false" in the $data when running getDataFields()

### ISSUE THREAD

**Issue by gadget00** [mikehaertl/php-pdftk#86]
Hi all,

when I try to use the code to open a PDF file and dump the data fields, it gives me a 'false' value instead of the DataFields:

```
$pdf = new Pdf('/Volumes/Macintosh HD/Applications/mampstack-5.6.30-5/apache2/htdocs/coopaceidaan/formularios/deb_dil_coopaceidaan.pdf');

$data = $pdf->getDataFields();
```

I also tried to use a short route for the file:

```
$pdf = new Pdf('./formularios/deb_dil_coopaceidaan.pdf');

$data = $pdf->getDataFields();
```

but it doesnt work. when I do
 
`var_dump($pdf);
`
 I get 

`bool(false)
`
Please help.

**Comment by mikehaertl** [comment]
If you get `false` as return value this usually indicates an error. You should get an error message with `$pdf->getError()`.

**Comment by gadget00** [comment]
can I just echo the error or do I have to do something else to see it on screen?

**Comment by gadget00** [comment]
I get nothing from 

`$pdf->getError()`

**Comment by mikehaertl** [comment]
Make sure, that you have `pdftk` installed and also try to configure the path to the executable in `command` as shown in the "Execute" section of the README: https://github.com/mikehaertl/php-pdftk#execution

**Comment by gadget00** [comment]
Im running on a Windows Server 2008.  I have the pdftk installed, and I know it is in the path because in a DOS console I write `pdftk --version` and it displays the version of the pdftk and the information.

I think that the "phpCommand" is not finding the pdftk.  I had the same problem on a macOS Sierra environment where the pdftk wasn't running

**Comment by gadget00** [comment]
I think I found the problem; as you mention in the #Execution I had to use the aditional commands for the phpShellCommand to be able to call pdftk, eventhough the path was added to the cmd console.

Now, I have another question: do I have to use the full directory route of the PDF file(like 'c:\app\forms\form.pdf') or can I use the 'web' style of directory (like '/forms/form.pdf') ?

**Comment by mikehaertl** [comment]
You should always absolute (full) paths to be on the safe side.

Closing this, as there's nothing to fix.
