### ISSUE TITLE
Failure msg from pdftk returned on php

### ISSUE THREAD

**Issue by brutalcrozt** [mikehaertl/php-pdftk#87]
This is a feature request, i am expecting an error thrown from pdftk-server is returned to php. So we can know what kind of error that happen.

Last week i just fill form with php-pdftk with xfdf file that generated via foxit reader, with pdftk it fail with no messages.  But when i try it directly with pdftk-sever it fail with `java.io.CharConversionException` , sorry i can't reproduce the issue because my problem already gone as i generate xfdf with other UI pdf tools.

**Comment by mikehaertl** [comment]
There already *is* some error reporting:

```
// Check for errors
if (!$pdf->saveAs('my.pdf')) {
    $error = $pdf->getError();
}
```
It's possible that it doesn't catch all errors, but the library already tries as good as it can. If you find that some errors are not reported, I can only help if you profide a (simple!) code example to reproduce the problem.

**Comment by brutalcrozt** [comment]
i already read that, and still it just say it fail without error message.
What i expect is the error thrown in from java. Maybe after my project done i will try reproduce them again, sorry but i think you know some api to catch the response from cli that spawned from php

**Comment by mikehaertl** [comment]
For command execution we use my other library https://github.com/mikehaertl/php-shellcommand. This is where the code for shell execution and error reporting lives.

I think it's better to open an issue there if you find a reliable way to reproduce. It's not really related to this library here, so I'm closing this for now.
