### ISSUE TITLE
Getting Binary data of the PDF [Feature-Request] 

### ISSUE THREAD

**Issue by simonberger** [mikehaertl/php-pdftk#88]
I guess often a user needs the pdf in the binary form to put it on a backup server for example and only then stream it to the user (or not at all).

I now have to do something like this on my side:

```
$tempfile = tempnam(sys_get_temp_dir(), 'pdf');
$pdf->fillForm([
	// ...
])
->needAppearances()
->saveAs($tempfile)
$pdfData = file_get_contents($tempfile);
unlink($tempfile);
// Using data
```

**Comment by mikehaertl** [comment]
Internally we use my https://github.com/mikehaertl/php-tmpfile library so there already is a temporary file. You could save a step as something like this should work:

```
$pdf->fillForm([...])
    ->execute();
$pdfData = file_get_contents( (string) $pdf->getTmpFile() );
```

The temporary file is automatically deleted afterwards.

**Comment by simonberger** [comment]
I saw that internal tmpfile library use but didn't note it is usable from outside and always filled in execution.
I am perfectly fine with this solution. Thank you !

It would be a good idea to put this possibility into the readme as it's not easy to find out.

**Comment by mikehaertl** [comment]
> It would be a good idea to put this possibility into the readme as it's not easy to find out.

Done: https://github.com/mikehaertl/php-pdftk#temporary-file
