### ISSUE TITLE
Lock editable forms

### ISSUE THREAD

**Issue by taitai42** [mikehaertl/php-pdftk#89]
Hi, is there a way to lock the forms / pdf so they are not editable anymore once the file is generated by the server ? 

thanks

**Comment by mikehaertl** [comment]
You could "flatten" your PDF forms with `flatten()` but this will not work well  if you have non ASCII characters in your forms.

Please understand that I can't provide more help on this topic as this is a limitation of pdftk, not our library.

**Comment by taitai42** [comment]
all right thanks for the quick answer,
 i don't have a lot of experience with pdf tho, so sorry if the question sounds idiot, but if i set permissions on the file like this for exemple 
```allow('Printing DegradedPrinting CopyContents ScreenReaders')```

then i'm not allowing edition on the pdf is that right ? so forms shouldn't be editable right ?

**Comment by taitai42** [comment]
by the way flatten does the job thanks, i just don't understand why permissions don't ! if you can light me up !

**Comment by mikehaertl** [comment]
Sorry, I'm not an expert on PDF permissions either so no idea why it doesn't work as expected.
