### ISSUE TITLE
needAppearances() doesn't work

### ISSUE THREAD

**Issue by florianbepunkt** [mikehaertl/php-pdftk#9]
Hi,

I managed on install your library and it works fine – I can manipulate PDFs

But when I want to use the needAppearances() function no PDFs is created anymore. Without the needAppearances() it works just fine. Any ideas?

http://s17326667.onlinehome-server.info/cm-auto/pdf.php

Thank you,
Florian

**Comment by mikehaertl** [comment]
Can you show me some code? Also note this about `need_appearance` from the `pdftk` man page:

>[need_appearances]
>Sets a flag that cues Reader/Acrobat to generate new field appearances based on the form field values. Use this when filling a form with non-ASCII text to ensure the best presentation in Adobe Reader or Acrobat. It won't work when combined with the flatten option.

And does your pdftk version support this option at all? You need pdftk >= 2.x for this, as far as i remember.

**Comment by mikehaertl** [comment]
Closing this as there was no further feedback.
