### ISSUE TITLE
Barcode in document

### ISSUE THREAD

**Issue by David91vlc** [mikehaertl/php-pdftk#93]
I like to add a barcode in a PDF.

I don't read any information to add an image or barcode.

Any suggestion?

Regards

**Comment by mikehaertl** [comment]
AFAIK there's no support for barcodes in pdftk. From a quick search it seems like barcodes are just some special form values: https://askubuntu.com/questions/769812/pdftk-code128-and-utf-8 that require a special font to be rendered.

Apart from the answer given on that question I don't think there's much we can do here about it.

**Comment by Glideh** [comment]
Anyway, barcodes could be added as PNG but the question would then be "Is there a way to add images on an existing PDF" ?

**Comment by mikehaertl** [comment]
As usual: We can't do, what `pdftk` can't do. So: No, there's no way to add images as far as I know.

**Comment by Glideh** [comment]
Understood.
Thank you for your quick answer, I'm actually searching for a way to add some text to an existing PDF with php but that is an other question.

**Comment by Glideh** [comment]
I'll use [FPDF](http://www.fpdf.org/) for that.
Which by the way is also able to generate all sorts of BarCodes and QRCodes.
