### ISSUE TITLE
Multiple Commands not working

### ISSUE THREAD

**Issue by mathieu-gilloots** [mikehaertl/php-pdftk#95]
Hi,
I try to work with : https://github.com/mikehaertl/php-pdftk#how-to-perform-more-than-one-operation-on-a-pdf

I've one PDF layout with a table to fill.
I've read that I can add page and fill so I decide to do like the documentation you gave (thanks !)
```php
fields = [...] //array in my code
foreach ($someDataEntity as $pageFieldData) {
    $pdf = new Pdf($layoutPath);
    $pdf->fillForm(array_merge($fields, $pageFieldData));
    $pdf->execute();
    $pdfs[] = $pdf;
 }

$pdf = new Pdf();
for($i= 0; $i < count($pdfs); $i++){
    $pdf->addFile($pdfs[$i], 'A' . $i);
    $pdf->cat($i, null, 'A' . $i);
}

$pdf->needAppearances()
    ->flatten()
    ->saveAs($this->generatedDirPath . '/' . $name)
;
```

The Command :
```
 pdftk A0='/tmp/tmp_php_pdftk_TVs218.pdf' A1='/tmp/tmp_php_pdftk_33BMwG.pdf' A2='/tmp/tmp_php_pdftk_ExbV8e.pdf' A3='/tmp/tmp_php_pdftk_ygfPuO.pdf' cat A00 A11 A22 A33 output '/tmp/tmp_php_pdftk_6JSGI6.pdf' need_appearances flatten
```
At the first look it's seems good, but, no PDF generated and error to find /tmp/....pdf file : 
```
 Error: Unable to find file.\n
      Error: Failed to open PDF file: \n
         A0=/tmp/tmp_php_pdftk_TVs218.pdf\n
      Error: Unable to find file.\n
      Error: Failed to open PDF file: \n
         A1=/tmp/tmp_php_pdftk_33BMwG.pdf\n
      Error: Unable to find file.\n
      Error: Failed to open PDF file: \n
         A2=/tmp/tmp_php_pdftk_ExbV8e.pdf\n
      Error: Unable to find file.\n
      Error: Failed to open PDF file: \n
         A3=/tmp/tmp_php_pdftk_ygfPuO.pdf\n
      Errors encountered.  No output created.\n
      Done.  Input errors, so no output created.\n
```

Did you have any ideas for a resolution ?
I try a saveAs on each file, it's ok, but I want to go with 'streamed' file (/tmp file).

Thanks !

**Comment by mikehaertl** [comment]
@mathieu-gilloots Hmm, ok, this is a limitation of the library: You can not have multiple calls to `addFile()` to add more than one instance of `Pdf`. Think of it as a pipe where one output can be passed to another input. You can't have two inputs, though.

Could you try the following changes in our library code please? In the `src/Pdf.php` change these two lines:

```
// Change this:
// protected $_pdf;
protected $_pdf = [];
```

And in the `addFiles()` method:

```
// Keep a reference to the object to prevent unlinking
$this->_pdf[] = $name;
```

**Comment by mikehaertl** [comment]
Oh, and you shouldn't have to call `$pdf->execute()` in your first loop. This should happen automatically inside the Pdf that you add your instances to.

**Comment by mathieu-gilloots** [comment]
Hi, thanks for your help.
I tried to modified sources but it's not working. Same errors : 
```
   #_execCommand: "pdftk A0='/tmp/tmp_php_pdftk_hmduRA.pdf' A1='/tmp/tmp_php_pdftk_P1Iwra.pdf' A2='/tmp/tmp_php_pdftk_TqLCpK.pdf' A3='/tmp/tmp_php_pdftk_do4sRk.pdf' cat A00 A11 A22 A33 output '/tmp/tmp_php_pdftk_BuKkNV.pdf' need_appearances flatten"
    #_stdOut: ""
    #_stdErr: """
      Error: Unable to find file.\n
      Error: Failed to open PDF file: \n
         A0=/tmp/tmp_php_pdftk_hmduRA.pdf\n
      Error: Unable to find file.\n
      Error: Failed to open PDF file: \n
         A1=/tmp/tmp_php_pdftk_P1Iwra.pdf\n
      Error: Unable to find file.\n
      Error: Failed to open PDF file: \n
         A2=/tmp/tmp_php_pdftk_TqLCpK.pdf\n
      Error: Unable to find file.\n
      Error: Failed to open PDF file: \n
         A3=/tmp/tmp_php_pdftk_do4sRk.pdf\n
      Errors encountered.  No output created.\n
      Done.  Input errors, so no output created.\
```

**Comment by mikehaertl** [comment]
Hmm, this is weird. I'm sorry, but then there's not an easy fix for this. As you may have seen we use my other library https://github.com/mikehaertl/php-tmpfile internally to automate the handling of temporary files. The key here is that we define a destructor in that temp file instance which will delete the file as soon as there's no object reference in PHP anymore.

This already works with a single file: We keep a reference to the input `Pdf` instance in `protected $_pdf`. Inside that instance there's another reference to `_tmpFile`. This is enough that the destructor is not called to early.

So the recommended fix should actually work as all we changed is to keep a list of references in an array. I currently have no time to dig deeper into this, but maybe you want to give it a try yourself. I would probably start by changing the `__destruct()` here, to find out in which order it's called and whether it's causing the issue at all:

https://github.com/mikehaertl/php-tmpfile/blob/master/src/File.php#L58

Let me know, how it goes.

**Comment by mathieu-gilloots** [comment]
Hi @mikehaertl 
I have debug all my process.
It's a little trick from PDFTK : Aliases can ONLY be a letter.
on my foreach I had :
$pdf->addFile($pdfs[$i], 'A' . $i);
Dynamicaly generate the alias : A + Number.

So I fix by replacing by only letters. and it's works !
No need to change package (or maybe a little mention in doc about that).

Thank you again.

**Comment by guicara** [comment]
> Aliases can ONLY be a letter

Thank you very much @mathieu-gilloots! 👍 

@mikehaertl I think it is important to add in the `README.md` file that aliases can only be a single letter. The `Unable to find file` error message is wrong.

**Comment by mikehaertl** [comment]
@guicara Ok, added a note now here: https://github.com/mikehaertl/php-pdftk#operations

**Comment by guicara** [comment]
@mikehaertl  Thank you!
