### ISSUE TITLE
Bold latter print in Rich Text format

### ISSUE THREAD

**Issue by oepl** [mikehaertl/php-pdftk#97]
Hi Michael

Thanks for share this library for everyone. I am using your code to generate dynamic PDF file. I have one Rich Text box and i want to make some of sting part in bold - Can you help? How can I do? I am using PHP. String Example is below.

Attached is the Doctor Order for patient **Your Name** for your review. Please complete all 5 arrows in the prescription as follows

Thanks
Dipesh

**Comment by mikehaertl** [comment]
Sorry, this library is only a wrapper around [pdftk](https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/). It can not do what `pdftk` can't do. Please also understand that we don't provide support for usage questions.
