### ISSUE TITLE
$data = $pdf->getDataFields(); is Boolean

### ISSUE THREAD

**Issue by tomgs** [mikehaertl/php-pdftk#99]
Hiya, and thanks for this library! Great help.

As the title suggests - `$data = $pdf->getDataFields()` gives `$data` a boolean value, according to php's `gettype()`. Shouldn't it be an array with the loaded pdf's form fields?

Specifically, if I try to get the data as an array - as per the `readme.md` file, I get this:

`Fatal error: Uncaught Error: Call to a member function __toArray() on boolean`

Edit: Got a hint - it's not loading `pdftk` properly: `sh: pdftk: command not found`. If it doesn't find the executable, should `getDataFields()` return a boolean?

2nd Edit: rephrasing question - now i've told the library where the executable is as per [this issue](https://github.com/mikehaertl/php-pdftk/issues/86#issuecomment-325574926), but the script just gets stuck - I can see it's loading, but it never finishes. Thought this might have something to do with [this](https://github.com/mikehaertl/php-shellcommand/issues/20), not sure where this stands right now, and if you rolled back the changes or not. I'll try [this](https://github.com/mikehaertl/phpwkhtmltopdf/issues/250) tomorrow as well, hope it fixes it. 

On a side note - looking through the issues I'm realising how much you guys maintain this thing. Again, thank you, truly - if I'd have to write this from scratch it would be a real pain.

**Comment by mikehaertl** [comment]
Did you try with raw `pdftk` on the command line? Does it work there with the same PDF file?

**Comment by tomgs** [comment]
That is a fine question that I should've explored earlier. Will be in front of it soon and will let you know.

**Comment by tomgs** [comment]
OK, seems like pdftk itself hands for eternity when trying to perform any action. Will try and see what their site have to say about this. If you could leave this open, I'll update if I find something.
